### ISSUE TITLE
sdpFmtpLine isn't very convenient

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1022]
As currently written, it sounds like this attribute should return the _entire_ "a=fmtp" line. For example:

"a=fmtp:96 foo=1;bar=2"

This seems unnecessary. The payload type (96) is already present in RTCRtpCodecParameters. I'd propose this attribute only returns the "format specific parameters" (the thing that comes after "a=fmtp:PT ").

Or, even better, if we can be confident that all codecs will use parameters in a "key=value" form, we could make this attribute a dictionary instead of an opaque string, as it is in ORTC.

**Comment by aboba** [comment]
@taylor-b  I have some more basic questions:

a. What is returned by sender.getParameters().codecs[].sdpFmtpLine?  Is this supposed to represent settings relating to the sender, or capabilities of the sender as reflected in the Offer or Answer?  

For example, if the remote peer offers profile-level-id=42c02a (indicating the maximum it can receive), does the sender's sdpFmtpLine include profile-level-id=42c02a, reflecting what was offered by the remote peer (since that constrains the sender)?  Or is it not present at all since profile-level-id represents a receiver capability and we called sender.getParameters()?

b. Same question for receiver.getParameters().codecs[].sdpFmtpLine

c. Can sdpFmtpLine be modified by sender.setParameters()?  If sdpFmtpLine represents what is in the Offer or Answer, the answer should probably be "no".  But if it represents a sender setting, then maybe it can be set?

**Comment by taylor-b** [comment]
> Is this supposed to represent settings relating to the sender, or capabilities of the sender as reflected in the Offer or Answer?

I would expect for a sender, it's exactly the "fmtp" line from the remote description, and for a receiver, it's exactly the "fmtp" line from the local description.

> For example, if the remote peer offers profile-level-id=42c02a (indicating the maximum it can receive), does the sender's sdpFmtpLine include profile-level-id=42c02a, reflecting what was offered by the remote peer (since that constrains the sender)?

That sounds right.

> c. Can sdpFmtpLine be modified by sender.setParameters()?

I thought codecs could only be reordered, not modified. I'll create a separate issue for that, since I don't see it mentioned anywhere.

**Comment by aboba** [comment]
>I would expect for a sender, it's exactly the "fmtp" line from the remote description, and for a receiver, it's exactly the "fmtp" line from the local description.

I think this makes sense. As a result, for a receiver, sdpFmtpLine will often represent codec capabilities and for the sender, it will represent codec settings.  That is more or less how things worked out with the ORTC codec capabilities/settings.

>I thought codecs could only be reordered, not modified. I'll create a separate issue for that, since I don't see it mentioned anywhere.

We need to spell out whether it is possible to modify codecs[].sdpFmtpLine (and if so, what it means to do so). 

The receiver's sdpFmtpLine can't be modified since there is no receiver.setParameters() method and in any case, since the receiver's sdpFmtpLine represents capabilities, it doesn't seem like modifying it would make sense.

For a sender in ORTC, the equivalent of the codec sdpFmtpLine (e.g. the codec parameter settings) can be changed, and it's not clear to me that this would violate the prohibition against setting the negotiation-needed flag. 

For example, let us say that within the Offer and Answer the Opus fmtp line looks like this: 

       a=fmtp:101 maxplaybackrate=16000; sprop-maxcapturerate=16000;
       maxaveragebitrate=20000; stereo=1; useinbandfec=1; usedtx=0

So both the Offerer and Answerer support stereo and FEC, but neither wants DTX. 

What if the application decides that it doesn't want to encode stereo (e.g. it's a phone call and bandwidth availability is poor)?   Can it set the stereo dictionary entry to 0?  What if it wants to use external FEC rather than Opus internal FEC?  Can it set useinbandfec to 0?

**Comment by aboba** [comment]
@taylor-b This might be a good issue to discuss at the upcoming interim.

**Comment by taylor-b** [comment]
Reminder to myself: the decision at the interim was to leave this as a string, since there definitely *are* codecs that don't use key/value pairs, and nothing prevents more from being defined in the future. So to resolve this issue we just need to clarify that:

* "sdpFmtpLine" represents "everything after payload type"; not the entire line of SDP.
* RtpSender's sdpFmtpLines come from remote description, RtpReceiver's come from local description. Got it backwards in the slides.
