### ISSUE TITLE
Section 11.6: Issue 6

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1053]
In Section 11.6, it says: 

"ISSUE 6
Editors' Note: This example flow needs to be discussed on the list and is likely wrong in many ways."

**Comment by aboba** [comment]
Looking at the diagram, there are a few obvious things that need to be updated: 

* Use of addstream/onaddstream (needs to be updated with addTrack/onTrack)

Are there other aspects that are wrong or otherwise need to be corrected?

**Comment by fippo** [comment]
A general issue with that diagram is that it shows the legacy callbacks instead of promises. That makes it easier to read though so it might be ok.

Is it really the intention to have such a complicated example?

small issues:
communication with Alice's TURN server (steps 11 + 12) typically happens after setLocalDescription (step 14)

If settings 22 intends to restrict the ip addresses gathered to relay addresses it should use setConfiguration with iceTransportPolicy, not the old iceTransports

The TURN allocation in steps 24 + 25 doesn't happen before setLocalDescription.
Step 27: ugh... pranswer. I don't think I got an answer during JSEP last call on why this is still there. I don't think the example should use pranswer.

30: permissions are created either as a result of addIceCandidate (not shown here) or as a result of setRemoteDescription in step 19.

Its wasn't immediately clear to me why ICE is using Bobs TURN server but not Alice's TURN server in steps 35 and 36. But that is because of the iceTransportPolicy which is set to relay... which the reader has probably forgotten by now.

Step 50 is using SRTP without a relay. Switching from relayed to P2P is certainly possible but requires calling setConfiguration again.

step 60: s/callbakc/callback

**Comment by aboba** [comment]
Section 11.6 needs to be reworked :)

![2017-02-06 17 08 37](https://cloud.githubusercontent.com/assets/808811/23730946/730c07d6-041f-11e7-8a51-81188640574a.jpg)

**Comment by stefhak** [comment]
:-)

**Comment by alvestrand** [comment]
Tool that generates the diagrams found in the "ladder" subdirectory.
