### ISSUE TITLE
Need to specify what happens if the browser doesn't implement "negotiate" rtcpMuxPolicy

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1065]
JSEP states:

> Implementations MAY choose to reject attempts by the application to set the multiplexing policy to "negotiate".

So, what does this mean at the API level? A "NotSupportedError" being thrown by the RTCPeerConnection constructor?

**Comment by aboba** [comment]
The specification still includes "negotiate", even though there is a note stating that it is an "at risk" feature due to lack of implementer interest. 

Assuming that we don't remove the "negotiate" value of RTCRtcpMuxPolicy, then an exception should be thrown in the RTCPeerConnection constructor if the implementation doesn't support it.

**Comment by taylor-b** [comment]
Would it be an InvalidAccessError or NotSupportedError? I'm not clear about the difference between

> The object does not support the operation or argument.

and

> The operation is not supported.
