### ISSUE TITLE
Make legacy API optional to implement

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#1086]
The spec should drive users out of using the legacy API.
But it is not clear whether the legacy API is an optional part of the spec.
If it is not already, the legacy API section 4.3.3 should then be made optional.
Something like: 
Implementers MAY support these methods for backward compatibility.

**Comment by fippo** [comment]
👍 

the callback-based API can be just as easily shimmed ontop of the promise-based one (as had to be done the other way round in Chrome for a long time)

**Comment by alvestrand** [comment]
@foolip this seems like the mirror argument of the createObjectURL discussion. Do you want to comment?

**Comment by foolip** [comment]
Most specs have some bits of API that aren't yet implemented everywhere without that being considered a spec violation, so in that way implementations are already free to prioritize implementing other things over the callback-based APIs.

But the interesting question to me is what implementers want to do, and how to [find a path to interop](https://docs.google.com/document/d/1LSuLWJDP02rlC9bOlidL6DzBV5kSkV5bW5Pled8HGC8/edit?usp=sharing). Of the methods in https://w3c.github.io/webrtc-pc/#legacy-interface-extensions, are there any that *aren't* already supported everywhere that RTCPeerConnection itself is?

**Comment by youennf** [comment]
In WebKit, these legacy methods are implemented but some are not aligned with the spec.
WebKit might probably end up not supporting them.

Keeping those APIs in the spec has a cost for implementations (code, testing), the spec itself (already quite large) and users (nicer APIs available anyway).
That seems like a healthy move to try deprecating them by either removing or making them optional.

I am all for a place where legacy APIs would be described in terms of the spec APIs.
For instance onaddstream seems to be quite in use by some web sites and is not described in the spec AFAIK. Such a description could be written in a separate spec or as a JS shim.

**Comment by foolip** [comment]
Are there any of these that can't be expressed in terms of the promise-vending variants? If so, would that be a problem for someone who tries to migrate from callbacks to promises?

There are indeed other APIs that are widely implemented and yet not in the spec. I consider such things in Blink to be bugs, and `onaddstream` specifically is tracked by [an issue to either standardize or remove](https://bugs.chromium.org/p/chromium/issues/detail?id=697059).

**Comment by foolip** [comment]
https://jsbin.com/coqibewate/edit?html,output is a test for existence of the callback-based `createOffer()` that passes in Chrome, Edge (with the "WebRTC 1.0" enabled), Firefox.

In order to remove the callback-based `createOffer()` (or ship `RTCPeerConnection` without it) I would try to understand the usage a bit first. There's actually a use counter for this in Blink which is pretty high: https://www.chromestatus.com/metrics/feature/timeline/popularity/1047

I didn't investigate any of the other methods, but this one seems like a risky undertaking and the upside isn't obvious to me. But I am not the Blink developer that would need to be convinced, just weighing in :)

**Comment by alvestrand** [comment]
When we installed counters, the intent was that we would count all the variants of CreateOffer with respect to constraints and callbacks, so that we could compare the proportions - but the buckets were intended to first of all capture whether or not we had the failure callback (it was declared illegal not to have it); I don't think we have a counter for the promise-version vs the callback version. @guidou would know.

All of the counters are within https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/peerconnection/RTCPeerConnection.cpp?type=cs&q=RTCPeerConnectionCreateOffer+package:%5Echromium$&l=570 - from looking at the code, RTCPeerConnectionCreateOfferLegacyFailureCallback shold catch all of the callbacks.

**Comment by foolip** [comment]
These counters are all for the callback-based createOffer, but you're right that we don't have a use counter for the promise-based createOffer. That's probably OK though, because the risk of removing the callback-based createOffer doesn't depend on the usage of the promise-based one.

**Comment by alvestrand** [comment]
VI: Group agrees to make the legacy APIs optional.

**Comment by stefhak** [comment]
PR: #1119

**Comment by foolip** [comment]
Did the group discuss in detail which methods it believes are needed for web compat and not, and how to write web-platform-tests for things that are optional?

@youennf, can you say whether you intend to keep the callback-based methods in WebKit, or which you intend to remove?

**Comment by youennf** [comment]
WebKit has a runtime flag for the legacy WebRTC API. This covers:
- All RTCPeerConnection callback-based API
- All RTCPeerConnection stream-based API: addStream, onaddstrean, MediaStreamEvent, removeStream, getRemoteStreams, getLocalStreams, getStreamById
- navigator.getUserMedia
addStream/onaddstream seem widely used and might be the most problematic to not ship.
From a web developer point of view, addStream is also much more convenient than addTrack for simple cases. Sadly, addStream/onaddstream are not described anywhere.

**Comment by youennf** [comment]
As of testing, WebKit is trying to only use the latest API for its layout tests.
A few tests are dedicated to the legacy API.
I guess WPT tests could follow the same pattern.
Currently some webrtc tests are using unspecified APIs such as addStream...

**Comment by foolip** [comment]
Thanks @youennf, grouping all the legacy APIs behind one flag probably makes sense, this way we will not end up with (say) all engines supporting everything except WebKit for one or two tiny bits. That'd be a frustrating outcome for interoperability.

> addStream/onaddstream seem widely used and might be the most problematic to not ship.
From a web developer point of view, addStream is also much more convenient than addTrack for simple cases. Sadly, addStream/onaddstream are not described anywhere

Yep, this is a problem. Tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=697059 for Chromium.

> As of testing, WebKit is trying to only use the latest API for its layout tests.
> A few tests are dedicated to the legacy API.
> I guess WPT tests could follow the same pattern.

Yep, writing all tests using the new APIs except a few specifically targeting the old APIs makes sense. Unfortunately, the tests would become more convoluted when not having the APIs at all should also pass. Concretely, I think the only way to turn https://jsbin.com/coqibewate/edit?html,output into a per-spec test for createOffer would be to just pass the test where it would otherwise timeout, but that'd make real regressions invisible. AFAIK, there's no mechanism in web-platform-tests to mark a test as optional, or making the pass condition be implementation-defined so that regressions cannot go unnoticed.

> Currently some webrtc tests are using unspecified APIs such as addStream...

Filed https://github.com/w3c/web-platform-tests/issues/5533
