### ISSUE TITLE
When should RTCRtpContributingSource#audioLevel be null?

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#1090]
https://w3c.github.io/webrtc-pc/#dom-rtcrtpcontributingsource-audiolevel

The definition of the attribute does not mention a case where null should be returned. Is there such a case?

@taylor-b

**Comment by aboba** [comment]
What if the mixer-client extension is not negotiated?

**Comment by foolip** [comment]
Does one of the referenced RFCs have a notion of null that makes this obvious to an implementer who knows this stuff? I don't, and would expect to see somewhere in the WebRTC spec's prose "If *condition*, then the value is null."

**Comment by taylor-b** [comment]
I believe the intention is that:

- For SSRC `RTCRtpContributingSource`objects, the level comes from the RFC6464 extension if present, and otherwise is computed by the browser.
- For CSRC `RTCRtpContributingSource` objects, the level comes from the RFC6465 extension if present, and otherwise is `null`.

Assuming my interpretation is correct, this could definitely be specified more clearly.

**Comment by alvestrand** [comment]
Related: I worry about this writeup a bit because the use case of a single CSRC has turned out to be important (I thought it would be an edge case).
The problem is that when there's a single CSRC present, the text isn't clear about whether the SSRC, the CSRC or both are present in the list; when there is no CSRC, the SSRC is present (and has a computed volume); when there are two CSRCs, the CSRCs are present (and volume is null when not presented by an RTP extension). When there is one CSRC, there is .... what?

One solution might be to pull the RTCRtpContributingSource information for the SSRC (which will always have a volume) out into a separate attribute, and never have it present in the ContributingSources.

**Comment by taylor-b** [comment]
A smaller change would be to just say that the SSRC RTCRtpContributingSource object is always updated. This is a slightly separate topic though, so I created a new issue: https://github.com/w3c/webrtc-pc/issues/1091

**Comment by aboba** [comment]
@alvestrand Agree that the single CSRC case is turning out to be important (am seeing this in forwarded audio conferences).  In that scenario, there would be no audiolevel for the CSRC, because there is no mixer.  So it would be helpful to get the SSRC and a computed audiolevel, but it needs to be clear that this is not a CSRC and mixer-client audiolevel.
