### ISSUE TITLE
When exactly is an SSRC RTCRtpContributingSource object updated?

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1091]
Current text:

> Each time an RTP packet is received, the RTCRtpContributingSource objects are updated. If the RTP packet contains CSRCs, then the RTCRtpContributingSource objects corresponding to those CSRCs are updated. If the RTP packet contains no CSRCs, then the RTCRtpContributingSource object corresponding to the SSRC is updated.

Is this meant to imply that the RTCRtpContributingSource object corresponding to the SSRC is *only* updated if a packet contains no CSRCs? I'd suggest having it always updated. There's no extra implementation burden and applications may want to know the SSRC audio level even when CSRCs are present.

**Comment by alvestrand** [comment]
I think this makes sense.
I'm not sure it makes sense to have the SSRC listed in the contributing sources (it's not, after all, a contributing source), but having the level information consistently available is definitely useful.
(The SSRC doesn't seem otherwise available on an RTPReceiver.)

(Another puzzling question is what happens if we have both simulcast and CSRC. The RTP protocol header layout seems to indicate that CSRC happens per encoding. Is this yet another distraction?)

**Comment by taylor-b** [comment]
> Another puzzling question is what happens if we have both simulcast and CSRC

WebRTC doesn't support receiving simulcast, though. Or am I misunderstanding something?

**Comment by aboba** [comment]
In the case where there are CSRCs (a mixer), there also would presumably be a mixer-client extension which would provide audiolevels for the CSRCs.  In this case the browser would not be required to compute the audio-level for the SSRC. 

In the P2P case, there would only be an SSRC, so the browser is required to include the audiolevel for that SSRC. 

Given this, the code to compute the audiolevel for the SSRC is going to be there in either case.  And one could argue that the SSRC could be included (though not in the list of CSRCs, as Harald pointed out), and if it is, the audiolevel could be computed as well (e.g.  it could be used to provide UI for the overall audiolevel of the conference)

**Comment by aboba** [comment]
> Another puzzling question is what happens if we have both simulcast and CSRC

I've seen a number of applications that have implemented Opus forwarding instead of mixing.  Typically this is supported by forwarding up to N streams, each of which goes to its own receiver, with mixing in the browser.  

In this scenario (which is *not* simulcast), the packets may arrive with CSRCs, representing the sources that contributed to the packet (usually only one), with the SSRC being one of the N allocated by the SFU.  Since there is no mixing, there will likely be no mixer-client extension, yet there would be a (single) CSRC and it would be useful to have the audiolevel corresponding to the SSRC, since this would be used to show the level originating from the CSRC.
