### ISSUE TITLE
Describe update strategy on variables

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1111]
We should put in wording somewhere that says "all variables are conceptually read when the UA is in a stable state" or something similar - that they dont' change within the frame of a single JS execution.

**Comment by taylor-b** [comment]
Note that this kind of explanation exists currently for `RTCDataChannel.bufferedAmount`: 

> The bufferedAmount attribute must return the number of bytes of application data (UTF-8 text and binary data) that have been queued using send() but that, as of the last time the event loop started executing a task, had not yet been transmitted to the network. (This thus includes any text sent during the execution of the current task, regardless of whether the user agent is able to transmit text asynchronously with script execution.)

Meaning that within an individual task execution, the value of `bufferedAmount` doesn't change, unless `send()` is called, causing it to increase.

Here's one idea for what to say: "Unless otherwise stated, all `readonly` attributes must behave as though they return the value of an internal slot, which is only updated inside a queued microtask."

**Comment by taylor-b** [comment]
Another thing we should specify is that all _related_ attributes, which the application might compare against each other, must be updated in the _same_ microtask checkpoint. For example, with `getContributingSources`, which brought up this topic: an application may compare `RTCRtpContributingSources` against each other to find out, for example, who is the most recent speaker. So, all the `RTCRtpContributingSources` for a single `RTCRtpReceiver` should be updated at the same time. Otherwise, the application may think "this person stopped speaking", when really they're just looking at stale data.

It would be difficult to generalize this principle, so I suggest adding something to the description of `getContributingSources` itself, and any other place we think is relevant.

**Comment by taylor-b** [comment]
Created issue #1124 to address my last comment, so this issue can remain editorial.
