### ISSUE TITLE
does MSID still work? (was: example 13: getReceivers semantics)

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1128]
http://w3c.github.io/webrtc-pc/#peer-to-peer-example-with-media-before-signaling
essentially does this:
```
    pc.addTrack(...)
    pc.addTrack(...)
    pc.getReceivers().forEach(...)
```
Firefox returns an empty array of receivers at this point. Chrome 59 (after addStream) returns an empty array as well.

Is the example wrong or the implementations?

@jan-ivar @henbos

**Comment by jan-ivar** [comment]
That's post-transceiver behavior. Firefox is adding transceivers now in [bug 1290948](https://bugzilla.mozilla.org/show_bug.cgi?id=1290948).

Step 8.2 of [addTrack](http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addtrack) creates a receiver, so the implementations are wrong (as of [last year](https://github.com/w3c/webrtc-pc/commit/2852f0b3515acacdf80a6b125f96e5d2fa3ea608)).

**Comment by fippo** [comment]
Thanks. Now the next question, bear with me:
The receiver that is created and has a track. This track has a random id "randomA".
Media is received on that track (I assume this is possible if the MID header extension is used)
Now a remote answer arrives. The SDP contains two along the lines of 
    ```a=msid:remoterandomstreamid remoterandomaudio```

Does the receivers track id change?
Does ontrack fire with a track that has track.id=remoterandomaudio?
If yes: should the application replace the srcObject with the stream/track from that event?

**Comment by taylor-b** [comment]
The reason Chrome doesn't return any receivers is that since it uses "Plan B" SDP, each m= section could be used to receive 0 to N streams. So there's no way to tell how many receivers are needed before the remote description is set.

To answer your questions:

> Does the receivers track id change?

No; the receiver already had a track before `setRemoteDescription`, so that would mean changing the ID of an existing track.

> Does ontrack fire with a track that has track.id=remoterandomaudio?

It would be with "randomA", but the event *would* be fired on setting the remote description. This issue is related: https://github.com/w3c/webrtc-pc/issues/1013

**Comment by fippo** [comment]
so setRemoteDescription with an a=msid:streamid trackid only fires ontrack with a track whose id is 'trackid' only with an offer but not with an answer?! This doesn't make sense...

Not that track ids are useful but this seems to make the msid concept rather useless.

**Comment by ibc** [comment]
> No; the receiver already had a track before setRemoteDescription, so that would mean changing the ID of an existing track.

Why? I expected that `RtpReceivers` (and their internal `tracks`) would just be created upon receipt of the remote SDP...

**Comment by taylor-b** [comment]
> so setRemoteDescription with an a=msid:streamid trackid fires ontrack with a track whose id is 'trackid' only with an offer but not with an answer?! This doesn't make sense...
>
> Not that track ids are useful but this seems to make the msid concept rather useless.

I agree it doesn't make sense. But signaling track IDs is redundant in the first place, now that we have MIDs. So, from my perspective, this is just legacy baggage we have to deal with, and it doesn't really matter what we do as long as the behavior is predictable.

> Why? I expected that RtpReceivers (and their internal tracks) would just be created upon receipt of the remote SDP...

But then the early media example wouldn't work. The RtpReceiver and track should be available right after `addTransceiver`, so it can immediately be hooked up to a `<video>` tag, before the remote SDP is received.

**Comment by jan-ivar** [comment]
@taylor-b Did something get lost in refactoring in https://github.com/w3c/webrtc-pc/pull/1016 ? That PR is titled "Ensure that "track" event is only fired for "send" direction m-sections." which sounds like a spec change to me.

[Before](https://rawgit.com/w3c/webrtc-pc/c77e984fe0fb94b76f79f51fc1761d845b63592c/webrtc.html#set-description), 2.2.7. said: *"If description is set as a remote description with new media descriptions [JSEP] (section 5.7.2.), the User Agent MUST dispatch a receiver for all new media descriptions."* - where *dispatch a receiver* would always fire a track event.

This is why [the following](https://jsfiddle.net/jib1/qx3esnb3/) works in both Firefox and Chrome today.

[After](https://rawgit.com/taylor-b/webrtc-pc/78d828dd972b22aaf0905eaaf3618767b3b3cf5c/webrtc.html#set-description) the refactor, the spec no longer seems to fire the track event in this case. Was that intentional?

**Comment by taylor-b** [comment]
After the refactor the track event would still be fired. But only for `pc1`, since only `pc1` is receiving media. Isn't that what we want? Here's the relevant step in "applying a remote description":

> If the direction of the media description is `sendrecv` or `sendonly`, and `transceiver.receiver.track` has not yet been fired in a `track` event, [process the remote track](https://www.w3.org/TR/webrtc/#process-remote-track) for the media description, given transceiver.

"Process the remote track" may be a bad name for the series of steps, but the steps will add the track to the indicated stream(s) and fire the `track` event.

**Comment by jan-ivar** [comment]
@taylor-b Makes sense. I got my streams mixed up. Sorry for the distraction, and thanks for the fix.

**Comment by jan-ivar** [comment]
> But then the early media example wouldn't work.

So to double-check, with early media, the offerer still gets a track event fired when  setRemoteDescription is called, with the local track (and id) they already have. They basically need to ignore it since they've already set everything up, and avoid fiddling srcObject again, is that right?

**Comment by fippo** [comment]
> I agree it doesn't make sense. But signaling track IDs is redundant in the first place, now that we have MIDs. So, from my perspective, this is just legacy baggage we have to deal with, and it doesn't really matter what we do as long as the behavior is predictable.

If signaling track ids is such legacy should it be removed? As Byron pointed out, replaceTrack is another example of where things become inconsistent.

**Comment by henbos** [comment]
I don't understand why the spec suggests creating receivers for locally sourced tracks.

**Comment by taylor-b** [comment]
@jan-ivar Yes, that sounds right.

**Comment by taylor-b** [comment]
@jan-ivar Yes, that sounds right.

> If signaling track ids is such legacy should it be removed?

It seems too late to change, but we could ask rtcweb.

> I don't understand why the spec suggests creating receivers for locally sourced tracks.

It's not intuitive. But when you add a track, you also automatically offer to receive a track, since you offer a sendrecv m= section. It may or may not end up receiving something, depending on what the answerer does.

**Comment by jan-ivar** [comment]
So in the common case of both sides doing addStream/Track/Transceiver before connecting, neither stream.id nor track.id will match anymore, right? I.e. they'll stop matching [like they do today](https://jsfiddle.net/jib1/y3cbLrj2/)?

**Comment by fippo** [comment]
so previously I assumed that this would hold:
- call SRD with some 'a=msid:stream track'
- get a ontrack with track.id = 'track'
However, it does not hold if the receiver called addTrack before calling setRemoteDescription which causes a RTPReceiver to be creating with a random track id which is then used in ontrack.

I'm going to remove the wpt test which made that assertion. *sigh*

**Comment by taylor-b** [comment]
> So in the common case of both sides doing addStream/Track/Transceiver before connecting, neither stream.id nor track.id will match anymore, right?

Calling `addTrack` on both sides before connecting is very different than calling `addTransceiver` on both sides. If you call `addTransceiver` on both sides before creating an offer, you'd end up with two offer/answer exchanges and two m= sections.

But otherwise, you're right. `track.id` wouldn't match the SDP, though `stream.id` would (if we're talking about the stream created from the SRD call and fired in the `"track"` event).

**Comment by jan-ivar** [comment]
[addTrack](http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addtrack) in step 8 implicitly creates a transceiver, a sender, and [a receiver](http://w3c.github.io/webrtc-pc/#dfn-create-an-rtcrtpreceiver) which in turn creates a remote track (step 2) available immediately. So calling `addTrack` on both sides seems sufficient to render at least `track.id`s moot. 

I suppose `stream.id` will continue to work for people who ignore the early tracks. But they won't benefit from early media. Once people realize this, they'll instead hook the early tracks up to their own `new MediaStream([videotrack, audiotrack])` with its own `stream.id` as shown in the [spec example](http://w3c.github.io/webrtc-pc/#peer-to-peer-example-with-media-before-signaling). Once this gets copied around the web `stream.id` is effectively moot as well.

Not sure what you mean with "very different" and "two offer/answer exchanges". In my experience people don't use `pc.onnegotiationneeded`.

**Comment by taylor-b** [comment]
> Not sure what you mean with "very different" and "two offer/answer exchanges".

My point is that `addTrack` will try to latch onto existing m= sections, while `addTransceiver` will always create a new m= section. So here's what would happen:

1. Alice calls `addTransceiver`
2. Bob calls `addTransceiver`
3. Alice initiates the offer/answer exchange
4. Offer/answer exchange completes. Alice can send a track to Bob, but Bob can't, because it's attached to a transceiver that's not negotiated yet.
5. Bob initiates second offer/answer exchange adding the second m= section

I don't imagine this will be a common scenario.

Anyway, I agree with the rest of your comment. If an application is optimized for early media (or is just transceiver-aware), it has no use for track or stream IDs.

**Comment by fippo** [comment]
another case which doesn't work anymore:
* call SRD
* call addTrack
* the track id is not reflected by the rtpsender

Now suppose I added a video track, the remote sends me two video m-lines (so two senders get created on my side) and later I add a screensharing track. how would I find the rtpsender associated with my screensharing to call replaceTrack(null)?

(speaking practically i would probably just stop() the screensharing track)

**Comment by taylor-b** [comment]
You could use the `track` attribute to find the sender of the track. Or hold on to the sender returned by `addTrack`.

Just to check: is there anything discussed in this issue that requires a change to the spec, or that we should talk about in the virtual interim? The issue has diverged a bit from "getReceivers semantics".

**Comment by fippo** [comment]
changed title accordingly

**Comment by fippo** [comment]
i'm not sure my comment https://github.com/w3c/webrtc-pc/issues/1128#issuecomment-297639748 is correct. SRD will create a transceiver and therefore a RTPSender but the RTPSender track is nullable (however, as currently specified, it is always created with a track. @aboba ORTC seems to allow creating with trackOrKind which would be good).

The RTPReceiver track is not nullable. Should it be? If yes: how would a receiver without a track be created by addTrack change its track from null to non-null?

**Comment by taylor-b** [comment]
> however, as currently specified, the RTCRtpSender is always created with a track

Well, the "Create an RTCRtpSender" algorithm takes a track as input. But it can be null, and it will be if it's created by SRD. The relevant statement is "Create an RTCRtpSender, sender, from the media description.", which doesn't mention creating a track.

> The RTPReceiver track is not nullable. Should it be?

No; there should be a 1:1 relationship between the `RTCRtpReceiver` and its track. Or, was your idea to have `addTrack` produce an `RTCRtpReceiver` with a `null` track, such that a track with the correct ID will be produced if the next thing that happens is `setRemoteDescription`? I don't think this is worth the added complexity. Though maybe it's what we'd need to do if we really wanted to avoid breaking existing apps that have expectations about track IDs.

**Comment by ibc** [comment]
Guys, I haven't read all the comments, but having a remote track that doesn't exist and later changes its id is crazy.

**Comment by jan-ivar** [comment]
@ibc Stream and track `id`s are [immutable](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediastreamtrack-id). **TL;DR:** Can't have both early tracks and correlated `id`s.

@taylor-b A `null` track is no longer early media.

@fippo I think we're fine if SRD is called first. It's the other way around that hurts.

A revisit of the compatibility cost of early-media transceivers at the virtual interim seems prudent, as the consequences weren't apparent to everyone the first time around it seems. Basically, it breaks `track.id` correlation.

`stream.id` correlation can be saved I think, as the earliest JS learns of a remote stream is on firing the `track` event (provided we rid implementations of `getRemoteStreams()`!).

**Comment by jan-ivar** [comment]
Here's why it sucks: Any moderately complex website today is going to want to correlate remote streams and tracks to local streams and tracks. They'll need to use msid for that today.

As an example, take this [simple Firefox fiddle](https://jsfiddle.net/jib1/aanj0zay/) that sends two videos, and swaps them after 3 seconds. Without correlating streams, there's no telling which video ends up on the left vs. right. Thus the fiddle correlates streams like this today:
```js
  let videos = {[streamA.id]: videoA, [streamB.id]: videoB};

  pc2.ontrack = ({streams: [stream]}) => {
    let video = videos[stream.id];
    if (!video.srcObject) video.srcObject = stream;
  }
```
vs. like this tomorrow:
```js
  let videos = {[transceiverA.mid]: videoA, [transceiverB.id]: videoB};

  pc2.ontrack = ({transceiver, streams: [stream]}) => {
    let video = videos[transceiver.mid];
    if (!video.srcObject) video.srcObject = stream;
  }
```

Luckily, both should continue to work, since I'm correlating streams not tracks.

What's not intuitive is that the same does not hold for track.ids, even though we'll continue to have them. I don't have a fiddle that swaps tracks, but you can easily imagine one I hope.

**Comment by jan-ivar** [comment]
To be clear, there's no doubt the "tomorrow" version is superior. It was pointed out to me that the "today" version can suffer id collisions when receiving streams from multiple peers.

[This fiddle](https://jsfiddle.net/jib1/L2auhsh5/) shows Firefox creating two streams with the same id in this case; not ok, a bug.

Yet how can we deprecate this approach when transceivers aren't available yet in any implementation?

**Comment by taylor-b** [comment]
So, what's the expected behavior when two PeerConnections see the same stream ID? Do the tracks from different PeerConnections get added to the same stream?

**Comment by fippo** [comment]
> Do the tracks from different PeerConnections get added to the same stream?

😭

I just remembered how I used these ids in talky. Basically, you entered a room and got a list of participants.  Each participant had an associated stream id.
Then I fed an SDP blob with multiple streams/track into SRD. This caused multiple onaddstream events to be emitted and looking at the id of the stream allowed me to look up the video element of the participant.

i'm ok with track ids being broken-ish but stream ids (or rather: this mapping mechanism) must continue to work

**Comment by jan-ivar** [comment]
@taylor-b In cases of accidental collisions, highly unexpected and undesirable I think. Were it done on purpose, I wouldn't expect implementations to pull off synchronization anyway, even if things came from the same place, like in my fiddle experiment. There are only bad choices here. I mean, this is why we moved to `transceiver.mid`, isn't it?

I think my preference would be to note this pitfall in the spec, and mark `stream.id` as legacy. Then, as to what should happen, probably what already happens. I'll test how Chrome handles it.

**Comment by jan-ivar** [comment]
Yup Chrome does the same. https://jsfiddle.net/jib1/L2auhsh5/7/

**Comment by taylor-b** [comment]
What ID does the second stream get, then? Is it ok to have two streams with the same ID?

**Comment by jan-ivar** [comment]
@taylor-b The output of the fiddles show both browsers create two stream objects with the same id.  A spec violation for sure, yet may actually cause the least pain. We could change it to give the second stream a unique id, breaking people differently than we do now in this edge case.

**Comment by taylor-b** [comment]
@jan-ivar Is this actually a spec violation, though? I don't see anything that explicitly requires unique stream IDs. If that was the intent of mediacapture-main, we may want to make it more clear.

**Comment by jan-ivar** [comment]
@taylor-b You're right, it appears they're not! (it only says "good practice"). So immutable yes, unique not.

I also found this note in [WebRTC](https://w3c.github.io/webrtc-pc/#rtp-media-api): 

***... Doing this implies that at the receiving end of the peer-to-peer connection there are several MediaStreamTracks with an identical id."***

Though from what we now know in this thread, this is only unavoidable if SRD is called first.

**Comment by jan-ivar** [comment]
Though when SRD is ***not*** called first, nothing protects the implicit receiver.track.id (created by the local UA's UUIDs algorithm) from colliding with future tracks renegotiated where SRD ***is*** called first. Though I'd file that under rare.

> It's not intuitive. But when you add a track, you also automatically offer to receive a track, since you offer a sendrecv m= section.

@taylor-b Which step in addTrack sets transceiver.direction to "sendrecv"? I don't see it, and direction doesn't appear to be intitialized anywhere or have a default value.

**Comment by jan-ivar** [comment]
Ah found the missing piece. Filed https://github.com/w3c/webrtc-pc/issues/1206.

**Comment by fippo** [comment]
so another issue which came up [here](https://bugs.chromium.org/p/webrtc/issues/detail?id=7933):
addTrack allows adding a track without a stream

How is this signaled in the SDP? https://tools.ietf.org/html/draft-ietf-mmusic-msid-16#section-2 doesn't allow an empty msid-id

**Comment by taylor-b** [comment]
@fippo 

> https://tools.ietf.org/html/draft-ietf-mmusic-msid-16#section-2 doesn't allow an empty msid-id

Section 3 does though (this was a relatively recent change; I know we don't implement it yet):

> The special value "-" indicates "no MediaStream".

**Comment by markandrus** [comment]
I agree with @fippo's [comment](https://github.com/w3c/webrtc-pc/issues/1128#issuecomment-294522434) from early in this thread:

> so setRemoteDescription with an a=msid:streamid trackid fires ontrack with a track whose id is 'trackid' only with an offer but not with an answer?! This doesn't make sense...
>
> Not that track ids are useful but this seems to make the msid concept rather useless.

I just hit this behavior while evaluating Safari 11 Tech Preview. Safari does not currently implement `offerToReceiveAudio`, and this spec says `offerToReceiveAudio` should behave ["as if addTransceiver('audio') had been called once prior to the createOffer() call"](http://w3c.github.io/webrtc-pc/#dom-rtcofferoptions-offertoreceiveaudio), but if you shim it this way your MediaStreamTrack ID will not match your MSID attribute. See [JSFiddle](https://jsfiddle.net/gd159o0m).

@taylor-b 

> I agree it doesn't make sense. But signaling track IDs is redundant in the first place, now that we have MIDs. So, from my perspective, this is just legacy baggage we have to deal with, and it doesn't really matter what we do as long as the behavior is predictable.

I have not yet read up on how to use MIDs in the newer APIs yet. Track IDs may be redundant and brittle, but my application expected them to behave in a predictable manner according to the MSID attribute. I found this new behavior surprising.

I think it could be nice if there were a way to get the previous behavior when shimming `offerToReceiveAudio` in terms of `addTransceiver`, e.g. an extra member in RTCRtpTransceiverInit. It could be optional in order to enable early media in the default case.

**Comment by taylor-b** [comment]
> I think it could be nice if there were a way to get the previous behavior when shimming offerToReceiveAudio in terms of addTransceiver, e.g. an extra member in RTCRtpTransceiverInit. It could be optional in order to enable early media in the default case.

In other words: by default, `addTransceiver` will immediately create a receiver and a track (for early media). But with this extra flag, it would only create the receiver's track after a remote description is set? Hmm. Seems feasible at least.

**Comment by markandrus** [comment]
@taylor-b yes, that's what I was thinking. I'm still working through the implications (need to look through the other examples shared here), but basically some way to retain deterministic MediaStreamTrack IDs would be useful. My application signals additional information about each MediaStreamTrack out-of-band by keying off ID. This has gotten us far (especially since we stay away from things like `replaceTrack`), but I'm not yet sure how to update our usage to handle this MSID change.

Anyway, thanks for the reply! And apologies if I'm barking up the wrong tree/too late here. Just wanted to share my experience in the hopes it improves the spec.

**Comment by jan-ivar** [comment]
@markandrus Why do you stay away from `replaceTrack`? What you propose doesn't work with it.

If the goal is to solve legacy (code already written) then no need to change the public API. When the spec says "as if", browsers don't actually have to call `addTransceiver` like JS does, just the internal equivalent.

I hesitate making legacy APIs desirable, as we've seen this hurt spec convergence in the past.

**Comment by markandrus** [comment]
@jan-ivar in my application, we want to be able to associate MediaStreamTrack additions on one end of a PeerConnection to "track" events on the other. Stamping an MSID attribute in the SDP for each track added and then getting MediaStreamTracks on the other end with IDs corresponding to the MSID attribute was good enough for us to tie these two together. `replaceTrack`, as I understand it, won't necessarily (ever?) update the MSID attribute, so that's one reason we haven't made use of it.

> If the goal is to solve legacy (code already written) then no need to change the public API. When the spec says "as if", browsers don't actually have to call addTransceiver like JS does, just the internal equivalent.

OK, maybe the `offerToReceiveAudio`/`offerToReceiveVideo` can be handled differently. I'm still more concerned with @fippo's original observation that

> setRemoteDescription with an a=msid:streamid trackid fires ontrack with a track whose id is 'trackid' only with an offer but not with an answer

Shimming `offerToReceiveAudio` was the first place I saw this behavior change WRT MSID.

**Comment by jan-ivar** [comment]
> we want to be able to associate MediaStreamTrack additions on one end of a PeerConnection to "track" events on the other.

@markandrus You'll be able to correlate by `event.transceiver.mid` instead as [mentioned](https://github.com/w3c/webrtc-pc/issues/1128#issuecomment-298394432). See [blog](https://blog.mozilla.org/webrtc/the-evolution-of-webrtc/).

It uses [`a=mid`](https://tools.ietf.org/html/rfc5888#section-4).

**Comment by markandrus** [comment]
@jan-ivar Thanks for the article and blog. If I had to update our application to handle this behavior today, I think I'd actually opt for the MediaStream ID approach you shared. It is nice because the MediaStream ID can be known in advance. So my application can say, "Hey, expect to receive MediaStream X" in advance of sending any offer, sending any answer, or even custructing an RTCPeerConnection. With MID, I cannot know the RTCRtpTransceiver's `mid` until applying a description, so I don't know how I could signal what to expect ahead of time.

**Comment by jan-ivar** [comment]
@markandrus That works, I guess, assuming you never have more than one video and one audio track per stream, though you'd still run the risk of (rare, theoretical) stream `id` collisions.

But note that `transceiver.mid` is set by both [`setLocalDescription` and `setRemoteDescription`](http://w3c.github.io/webrtc-pc/#set-description).

The [recommended](http://w3c.github.io/webrtc-pc/#simple-peer-to-peer-example) time to send signaling these days is *after* `setLocalDescription` ([tab-demo](https://jsfiddle.net/jib1/80xcgwmc/)), e.g.:
```js
  await pc.setLocalDescription(await pc.createOffer());
  // pc.getTransceivers()[0].mid is available here! <---
  sc.send({sdp: pc.localDescription});
```

**Comment by markandrus** [comment]
@jan-ivar thanks for taking the time to address my comments. I think I can see some ways forward with this behavior.

I have one more question/suggestion. Assume I wanted to signal a "menu of tracks" in my application. The idea is that this menu represents metadata about each of the MediaStreamTracks that might be shared once I negotiate, and the menu is always shared before negotiation:

```js
const menu = {
  'track-1': 'metadata 1',
  'track-2': 'metadata 2'
}
```

During negotiation, I get some "track" events with MediaStreamTrack IDs that aren't necessarily in the menu, so I can't lookup my metadata:

```js
pc.ontrack = event => {
  console.log(menu[event.track.id])
  // => undefined
}
```

However, I do have `event.transceiver.mid`, so I ought to be able to recover the MSID by parsing the SDP. I could write a function `bad` that looks up the corresponding MSID and returns `remoteId`, allowing me to lookup my metadata:

```js
pc.ontrack = event => {
  const remoteId = bad(event.transceiver.mid, pc.remoteDescription.sdp)
  console.log(menu[remoteId])
  // => "metadata 1"
}
```

But the function `bad` is bad... so would it make sense to instead add a property to the RTCRtpReceiver? e.g.,

```webidl
interface RTCRtpReceiver {
    // ...
    readonly attribute string? remoteTrackId;
    // ...
};
```

Then, my example code becomes

```js
pc.ontrack = event => {
  console.log(menu[event.receiver.remoteTrackId])
  // => "metadata 1"
}
```

Thanks again,
Mark

**Comment by jan-ivar** [comment]
@markandrus The track ids in the SDP won't match those in the menu. Switch out the ids for mids:

```js
  const renamer = (o, f) => Object.keys(o).reduce((o,k) => (o[f(k)] = menu[k], o), {});

  await pc.setLocalDescription(await pc.createOffer());
  menu = renamer(menu, id => pc.getTransceivers().find(t => t.sender.track.id == id).mid);
  sc.send({menu});
  sc.send({sdp: pc.localDescription});
````

**Comment by markandrus** [comment]
Thanks, @jan-ivar.

> The track ids in the SDP won't match those in the menu.

AFAICT, this is true if

* The remote end calls [`addTransceiver(kind)`](http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addtransceiver), in which case its `direction` defaults to "sendrecv", its `sender.track` is `null`, and therefore JSEP says it should generate `a=msid:- random`. (If I'm reading [5.2.1](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-21#section-5.2.1) correctly...)
* The remote end calls `replaceTrack` in some subsequent round of negotiation.

**Comment by jan-ivar** [comment]
@markandrus I see what you're saying. You're willing to forgo those two features. In a sense `receiver.remoteTrackId` is a step down from "why don't we just update `track.id`?" - without the issues that would entail.

**Comment by markandrus** [comment]
@jan-ivar yes. I'm not sure it's a good idea, but that's what I was exploring. Although I'd like to use the new features, I'm trying to figure out the interop story. My team needs to support existing Plan B/MSID clients as well as future WebRTC 1.0 clients. Since our application is already translating between Plan B and Unified Plan SDPs, we should probably go all-in on MIDs where available. But then we have to support "hybrid" clients, too, like Safari 11  (which has introduced the new MSID behavior without MID support).

**Comment by aboba** [comment]
Consensus at the September interim was to close this issue and revert PR 1567 (via PR 1598).
