### ISSUE TITLE
Issue 1: Key shortening

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1156]
Issue 1 says: "[[!RFC7635]] doesn't explicitly define how keys are shortened; there is only a brief reference to this in Appendix B. This needs to be addressed in the IETF TRAM working group."

We will use this Issue to track progress (rather than putting an Issue in the specification itself, which causes Issue at Risk numbering to start with 2).

**Comment by taylor-b** [comment]
FYI, I'm not sure this is really an issue. Copy of email I sent to @misi and @juberti:

> I don't think this is an issue after all... because RFC2104 already defines how HMAC keys are shortened:
> 
>> The authentication key K can be of any length up to B, the
>> block length of the hash function. Applications that use keys longer
>> than B bytes will first hash the key using H and then use the
>> resultant L byte string as the actual key to HMAC.
> 
> So if anything, the issue with RFC7635 is that it seems to assume the SHA1 key must be 20 bytes, when it can be up to 64 bytes and there's a defined procedure for shortening it if it's too large.
> 
> Or have I missed something? Is there a crypto expert in the working group we could check with?

**Comment by misi** [comment]
@taylor-b I am also not a crypto expert, but I see the same way as you. 
RFC2104 defines how to short a longer key for HMAC algs in general.
I think You find the missing puzzle piece RFC, and so the algorithm definition that we missed earlier.

I don't see the issue, you have mentioned here:
> So if anything, the issue with RFC7635 is that it seems to assume the SHA1 key must be 20 bytes, when it can be up to 64 bytes and there's a defined procedure for shortening it if it's too large.

AFAIU RFC7635 is correct and describes according RFC2104, 
HMAC-SHA-256-128 use 256bit key https://tools.ietf.org/html/rfc4868#section-2.6
20byte is correct as the output of SHA1(256bit key) that will be used as input for the final SHA1.

After clarification of this I don't see any issue here, and I think we could close this issue.

**Comment by taylor-b** [comment]
The issue I see with RFC7635 is this snippet:

> The key length of 160 bits MUST be supported (i.e., only the 160-bit key is used by HMAC-SHA-1 for message integrity of STUN messages).

This is incorrect, since any size key can be input into HMAC-SHA-1.

**Comment by misi** [comment]
AFAIU RFC7635 allows any input key length. This sentence AFAIU is just declaring that the implementation should implement/support 160 bit input key length for sure (because of the key shortening SHA1 output is a fixed 160bit..). 
And latter in next sentence it reefers to the hash agility of STUN.
I don't see your point. Could you clarify it more. .

**Comment by taylor-b** [comment]
Maybe that was the intent, but the statement "only the 160-bit key is used by HMAC-SHA-1" is just wrong, and (in my opinion) misleading. This misconception seems to also exist in Appendix B, which talks about shortening a 256-bit key to 160-bits, which is unnecessary since the block size of SHA1 is 512 bits.

**Comment by misi** [comment]
You are correct, I see your point now.

> Applications that use keys longer than B bytes will first hash the key using H and then use the
   resultant L byte string as the actual key to HMAC.

SHA1 block size is 512 bit (B=64 byte), and so the key shortening is not needed for a key that has only 256 bit length (or even 512 bit), because it is shorter than the Block size of SHA1 (512bit). (according the sentence above RFC2104 )

The stun-bis actual agility plan use SHA1 and SHA-256 algorithms.
AFAIU actually no key shortening is needed according RFC2104.

I agree that there is a conflict between RFC 7635 Appendix B, and RFC2104.

Open an errata about it?

**Comment by aboba** [comment]
I agree that RFC 2104 provides the required detail here.

**Comment by misi** [comment]
Any thoughts?
> Open an errata about it?

**Comment by taylor-b** [comment]
I just submitted errata reports (for section 6.2 and Appendix B), and created a PR to remove the incorrect note (https://github.com/w3c/webrtc-pc/pull/1453).
