### ISSUE TITLE
Do we need getAlgorithm() ?

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1159]
Now that it is no longer possible to retrieve the pre-configured certificates via getConfiguration(), is the original reason for adding getAlgorithm (described in Issue https://github.com/w3c/webrtc-pc/issues/496) still valid?

Since the only certificates retrievable via getConfiguration() are those the application created itself, the application could presumably store the algorithms used to create those certificates on its own.

**Comment by henbos** [comment]
Removing getAlgorithm() sounds good to me considering questions of having to serialize the AlgorithmIdentifier. It doesn't seem very useful and if you need it you can store it yourself.

**Comment by aboba** [comment]
@martinthomson @taylor-b Does it make sense to remove getAlgorithm()?

**Comment by taylor-b** [comment]
Sounds reasonable to me.

**Comment by aboba** [comment]
Original Issue: https://github.com/w3c/webrtc-pc/issues/496

**Comment by aboba** [comment]
@alvestrand (If you are not fishing ;)  Since you raised the issue originally, do you have an opinion on whether it is ok to remove getAlgorithm()?

**Comment by henbos** [comment]
I'm guessing he is out fishing. :)

From the original issue by @alvestrand in #496,
> A question was raised on whether we could tell if a given cert was RSA or ECDSA - there doesn't seem to be one.

Default generated certificates are not be included in getConfiguration() (based on [this discussion](https://github.com/w3c/webrtc-pc/issues/1120#issuecomment-294987310)) and remote side certificates [are byte arrays](https://w3c.github.io/webrtc-pc/#dom-rtcdtlstransport-getremotecertificates). Since RTCCertificate only exist for certificates that _you_ generated with generateCertificate(), you would know if you care to keep track of that information.
