### ISSUE TITLE
RTCIceCandidate: component attribute missing?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1167]
https://tools.ietf.org/html/rfc5245#section-15.1 has a component-id which however is missing in
    https://w3c.github.io/webrtc-pc/#rtcicecandidate-interface
Given the lack of enthusiasm for non-mux was that intentional?

If this is missing and should be added should this be
```readonly attribute unsigned short?         component;```
or
```readonly attribute RTCIceComponent? component;```

**Comment by fippo** [comment]
@taylor-b can you take a look? You added that in #325

**Comment by taylor-b** [comment]
I think it was simply overlooked. I'd suggest just using an integer type; we could use `byte` since it only goes from 1 to 256.

**Comment by aboba** [comment]
Perhaps the reason it was left out is because we have `RTCIceTransport.component`:
https://w3c.github.io/webrtc-pc/#rtcicetransport

So all candidates returned by `RTCIceTransport.getLocalCandidates()` have a component of `RTCIceTransport.component`.  

While in WebRTC we also have `RTCIceTransport.component`, there is no `RTCIceTransport.onicecandidate` EventHandler, only `RTCPeerConnection.onicecandidate`. Since in WebRTC `RTCIceTransport` objects do not necessarily have a unique `ufrag`, you can't use `RTCIceCandidate.ufrag` to determine the related `RTCIceTransport` object.

**Comment by fippo** [comment]
I think the reason is that in ORTC those candidates are emitted from a gatherer which doesn't have a component (i remember wondering about that...)

@aboba do you mean there should be a way to determine which ice transport caused a candidate event to be fired? That would indeed be solved by adding a component (look up the transceiver based on mid, then use the candidate component to determine whether its the rtp or rtcp transport). The heavier alternative would be to add an ice transport to every ice candidate event... overkill?

**Comment by taylor-b** [comment]
> Perhaps the reason it was left out is because we have RTCIceTransport.component:

I don't think that's the reason. Remember that this API may also be used for remote candidates:

```
function onRemoteCandidate(candidateInit) {
  candidate = new RTCIceCandidate(candidateInit);
  // Inspect candidate's attributes for whatever reason.
  pc.addIceCandidate(candidate);
}
```

It's basically meant to offer a more convenient way of inspecting the fields in the candidate SDP string. And "component" is one of them, so I don't see any harm in adding it.
