### ISSUE TITLE
Are camelCase codec parameters useful at all?

### ISSUE THREAD

**Issue by ibc** [w3c/webrtc-pc#1179]
Currently EDGE does not use camelCase RTP codec parameters (it uses `packetization-mode` rather than `packetizationMode` and so on). Also, there is no proper "conversion rule". In SDP land we have parameters such as `sprop-maxcapturerate`, `useinbandfec` and `L` that are mapped to `spropMaxCaptureRate`, `useInbandFec` and `l` forcing the implementation to keep a map of them (as [here](https://github.com/versatica/mediasoup/blob/master/lib/extra/index.js#L3)).

But, at the end, not even EDGE implements the ORTC camelCase syntax. Given that having a different naming provides zero benefit here, why not keep untouched the SDP naming?

**Comment by aboba** [comment]
@ibc Did you mean to file this bug against ORTC?  Because WebRTC 1.0 keeps the SDP codec parameters in sdpFmtpLine, I don't think it has this problem, does it?

However, I do think there is an issue in ORTC.  Since Edge implements both WebRTC 1.0 and ORTC, developers found it very confusing to convert SDP codec parameters back and forth from camelCase.

**Comment by ibc** [comment]
Opss sorry, indeed I wanted to report this issue in ORTC (wrong bookmark).

Proper issue in [ORTC](https://github.com/w3c/ortc/issues/689).
