### ISSUE TITLE
Spec-compliant way to get remote streams and tracks?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#1182]
An RTCRtpSender has an associated set of streams, which makes up the relationship between streams and tracks on a per-sender basis. RTCRtpSender exposes its track, but not its streams. For local tracks you can know which streams a track belongs to by remembering which streams were used as an argument in addTrack, but for remote tracks you just have the transceiver.sender/receiver.track, no streams.

1: The ontrack event does fire an RTCTrackEvent containing which streams the remote track belong to, but why not just expose the streams in transceiver.sender? Also, is there any way the streams could change without an event firing with the updated information, or does that result in a new transceiver/sender/receiver/track?

2: MediaStreamTrack does not know about the streams it belongs to, but a MediaStream knows of its tracks. Is stream.getAudio/VideoTracks() separate from the relationship formed by senders, or what does it return if multiple streams are used by multiple senders? And if a transceiver stops sending/receiving, does it stop counting towards streams.getAudio/VideoTracks()?

**Comment by henbos** [comment]
The way for me to make the most sense of this is that the stream's collection of tracks is completely separate from a sender's collection of streams and its track. But then a stream's tracks could be empty when it in fact has tracks due to sender(s).

**Comment by fippo** [comment]
> but for remote tracks you just have the transceiver.sender/receiver.track, no streams.

You can remember this just the same way you do for addTrack? But yes, why bother.

also when calling addTrack can you specify a stream that does not contain the track you're adding?

**Comment by fippo** [comment]
> also when calling addTrack can you specify a stream that does not contain the track you're adding?

This has a particularly relevant use-case.
1. call GUM with audio only-constraints
2. addTrack, negotiate a peerconnection
3. call GUM again with video-only constraints
4. addTrack. Since that should be sync I would expect this to be added to the first stream but the stream returned from GUM is different.

**Comment by henbos** [comment]
The spec does not ensure that the track is added to the stream when you do addTrack (and it doesn't add the track to the stream), I don't know if that is on purpose or a mistake.

**Comment by jan-ivar** [comment]
Taking a step back, the pivot to tracks in the API did two things for me:
 1. It lets us organize around what's being sent. E.g. when sending two video streams with a shared audio track, it's obvious we're sending three tracks, not four, yet we still reconstitute *two* video streams with a *shared* audio track remotely.
 
I think of the remote streams as managed by the remote *RTCPeerConnection* as a whole, not any individual receiver, since receivers are per track (a many-to-one or a few relationship).

 2. It decouples peer connection controls from `stream.addTrack` and `stream.removeTrack`, avoiding action at a distance.

Local stream makeup is irrelevant, because the stream makeup projected to the other side is made up entirely from the arguments to `pc.addTrack` et all. Therefore it matters little what stream(s) a track being sent is truly in. To illustrate:
```js
let track = stream.getTracks()[0];
pc.addTrack(track, stream); // no need to check if track is in stream here,
stream.removeTrack(track);  // because we may remove it right after anyway.
```

It sounds like `pc.getRemoveStreams()` did what you want, though we removed it in the spec. It truly is redundant though, as everything is exposed already in the `track` event.

**Comment by jan-ivar** [comment]
I do think it's important though that we remove remote tracks from their remote stream when they end, and that we end remote tracks when they're renegotiated away like [Chrome does today](https://jsfiddle.net/jib1/xrwsp7o9/). We're discussing this in https://github.com/w3c/webrtc-pc/issues/1161#issuecomment-300215486. That way people can use `pc.ontrack` combined with `track.onended` to see a track come and go, or even use `remoteStream.onaddtrack` and  `remoteStream.onremovetrack` on the stream they picked up from the first `track` event.

**Comment by jan-ivar** [comment]
The remaining issue here should be covered by https://github.com/w3c/webrtc-pc/pull/1402.

**Comment by jan-ivar** [comment]
Closing since https://github.com/w3c/webrtc-pc/pull/1402 is merged.
