### ISSUE TITLE
createAnswer does not guard against invalid remoteDescription or signaling state

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1183]
The current spec for `createAnswer` have the statement:

> If connection's remoteDescription is null return a promise rejected with a newly created InvalidStateError.

However `remoteDescription` can have the type `answer` on the offerer side and this statement allows it to pass through.

The statement also allows `createAnswer` to still be called on the anwerer side after `setLocalDescription` is called and the signaling enters `stable` state. Unlike `createOffer`, repeated call to `createAnswer` cannot be used again with `setLocalDescription` because doing so is invalid in `stable` state.

The statement should be updated to check for the type and signaling state as well.

**Comment by aboba** [comment]
@soareschen Can you submit a PR?

**Comment by jan-ivar** [comment]
I see two statements here:
 1. `createAnswer` needs `remoteDescription` to be an offer in order to do its job.
 2. `createAnswer` is useless outside of `"have-remote-offer"` and `"have-local-pranswer"` states.

(1) seems true, uncontroversial, and without compatibility issues.
(2) might be true, I don't know.
