### ISSUE TITLE
addIceCandidate may add ice candidate to the wrong remote description

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1227]
In step 2 and 3 of 4.6.2:

> 2. Let `remoteDescription` be connection's `pendingRemoteDescription` if not null, otherwise connection's `currentRemoteDescription`.
> 3. Add candidate to `remoteDescription`.

An `RTCPeerConnection` object could have both `pendingRemoteDescription` and `currentRemoteDescription` set with different ufrags, i.e. during ICE restart. If `addIceCandidate` is called with ufrag of previous ICE generation, i.e. `currentRemoteDescription`, the step still adds the candidate to the current generation, i.e. `pendingRemoteDescription`.

**Comment by soareschen** [comment]
With the concept ufrag identifying from multiple ICE generations and remote descriptions, it is not very clear how various other steps would behave `addIceCandidate` when called with old ufrags not belonging to `remoteDescription`.

- As mentioned, one could attempt to add candidate to `currentRemoteDescription` when there is a `pendingRemoteDescription`.
- `pendingRemoteDescription` can be updated multiple times with different ufrags, but the older remote descriptions are not saved. So if calling with older ufrags, do they still get "remembered" by the ICE agent and get applied accordingly? And if so on success do the candidate get added to the latest `pendingRemoteDescription`?

It seems that the current description for `addIceCandidate` is only applicable to the particular SDP in `remoteDescription`, thus only a particular ICE generation. If so is the statement _"Use candidate.ufrag to identify the ICE generation"_ and then proceed to process the candidate still make any sense?

**Comment by taylor-b** [comment]
This step should be changed such that the candidate is added to whatever remote description is applicable: possibly neither, and possibly both. Why both? Because if a "rollback" remote description is applied, wiping out `pendingRemoteDescription`, any candidates added while `pendingRemoteDescription` was non-null should still be present in `currentRemoteDescription`. The same goes for local candidates added to `currentLocalDescription`/`pendingLocalDescription`.

> So if calling with older ufrags, do they still get "remembered" by the ICE agent and get applied accordingly?

Meaning, older than both the "current" and "pending" remote descriptions? I don't see any situation where those candidates would be processed; the ICE agent only needs to keep track of two ICE generations, maximum, for the situation where a "pending" description initiates an ICE restart but is rolled back. This should be explained somewhere in the spec, since it's not a part of standard ICE.

> If so is the statement "Use candidate.ufrag to identify the ICE generation" and then proceed to process the candidate still make any sense?

This statement still makes sense.

**Comment by soareschen** [comment]
The situation I can think of is where one repeatedly set the `pendingRemoteDescription` with different ufrags without going back to stable state. The ICE agent might need to keep track of more than two ICE generations, but we could leave that to the implementation.

Agree that the change needed is just to add the candidate to whatever remote description that is applicable. It makes sense to me now.
