### ISSUE TITLE
which ice-tcp types will a browser emit?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1238]
http://w3c.github.io/webrtc-pc/#rtcicetcpcandidatetype-enum

describes the different types of ICE-TCP candidates that exist. IIRC nobody really wants to have browsers talking ice-tcp to other browsers (for example Chrome sets the port on the tcp candidates it emits to 9), this might be a good place to set the expectations about what browsers are required to implement

**Comment by taylor-b** [comment]
I agree that the expectations/recommendations for what candidates a browser gathers should be described somewhere.

> for example Chrome sets the port on the tcp candidates it emits to 9

This just means it's an "active" TCP candidate, and will only be used to make an outgoing connection if a "passive" remote candidate is added. Which *is* something that should be supported, so that the browser can make a TCP connection to an Internet-accessible server when that's the only option available.

**Comment by aboba** [comment]
@fippo Can you submit a PR?
