### ISSUE TITLE
maximum bandwidth: TIAS or AS?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1249]
http://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-maxbitrate mentions TIAS. Does that imply support for AS is not required?

Or does JSEP suggest internally processing everything as TIAS here:
```
For any specified "TIAS" bandwidth value, set this value as a constraint on the maximum RTP 
bitrate to be used when sending media, as specified in [RFC3890]. If a "TIAS" value is not 
present, but an "AS" value is specified, generate a "TIAS" value using this formula:
```
if yes this might require some wordsmithing to recognize this here.

**Comment by taylor-b** [comment]
I believe `maxBitrate` is only referring to TIAS because it needs some definition for what bitrate is being constrained. But this doesn't relate directly to SDP parsing. I assumed `maxBitrate` was intended to be orthogonal to any SDP bitrate constraint, and that if both "b=TIAS" and `maxBitrate` are used, the implementation should use the minimum of the two maximums. I think of it this way: one value is a limit imposed by the receiver, and the other a limit imposed by the sender.

So, if my assumption above is correct, we should just change the description of `maxBitrate` (and `maxFramerate`) to make this more clear.

**Comment by fluffy** [comment]
Yes, the maxBitrate there is just an additional constraint - we should update the text to say it is defined the same way that TIAS is (but it's not an override of TIAS value). So if SDP TIAS said 1000 and this said 2000, the combined limit is still 1000.

**Comment by stefhak** [comment]
I don't think we need to do anything. The current text includes
```Other things, like bitrate, are controlled using limits such as maxBitrate, where the user agent needs to ensure it does not exceed the maximum bitrate specified by maxBitrate, while at the same time making sure it satisfies constraints on bitrate specified in other places such as the SDP.``` 

I think that is clear enough.

**Comment by fluffy** [comment]
Have a look at #1329 and see if make it clear it is not the TIAS from SDP but is compute the same ways  as that.

**Comment by aboba** [comment]
@fluffy Looks good, thanks.
