### ISSUE TITLE
RTCConfiguration.iceServers with undefined?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1251]
a question that came up while writing tests ('cause branch coverage)

How does the [setConfiguration algorithm]( https://w3c.github.io/webrtc-pc/archives/20170515/webrtc.html#dom-rtcpeerconnection-setconfiguration)
> If configuration.iceServers is defined, then run the following steps for each element:
> Let server be the current list element.

deal with this:
```
new RTCPeerConnection({iceServers: [undefined]})
```

Chrome throws a TypeError (Failed to construct 'RTCPeerConnection': Malformed RTCIceServer).
Firefox throws a InvalidAccessError (RTCPeerConnection constructor passed invalid RTCConfiguration - missing urls). Looking for urls seems like the way to go.

nit: configuration.iceServers must be defined and an array?

**Comment by jan-ivar** [comment]
[WebIDL](https://heycam.github.io/webidl/#es-dictionary) says: *"An ECMAScript value V is converted to an IDL dictionary type value by running the following algorithm (where D is the dictionary type): 1. If Type(V) is not Undefined, Null or Object, then throw a TypeError. 2. Let dict be an empty dictionary value of type D; ..."* which gets us past the first `TypeError`. In other words, this is equivalent to:
```js
new RTCPeerConnection({iceServers: [{}]})
```

Then later it says *"if value is undefined and member is a [required dictionary member](https://heycam.github.io/webidl/#required-dictionary-member), then throw a TypeError."*

So Chrome is right, because [urls](http://w3c.github.io/webrtc-pc/#dom-rtciceserver-urls) is a required member. Firefox is [missing](https://dxr.mozilla.org/mozilla-central/rev/bdb2387396b4a74dfefb7c983733eed3625e906a/dom/webidl/RTCConfiguration.webidl#16) the required keyword. But,

sadly, it's not possible to `require` `urls` without dropping legacy support for `url`, something we'll experience if we end up putting `url` back in the spec for webcompat reasons. We'll have to [kludge it](https://bugzilla.mozilla.org/show_bug.cgi?id=1369563).

**Comment by jan-ivar** [comment]
So the spec is clear. The only issue is if we ever bring back `url` for webcompat then we'll need prose to throw `TypeError` for backwards compat.

**Comment by fippo** [comment]
thanks @jan-ivar!

**Comment by foolip** [comment]
Chromium has both as optional and throws TypeError if both are missing. This isn't much of a burden and spec'ing it would be trivial.
