### ISSUE TITLE
Section 11: Examples

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1295]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

Has someone tested these examples? I gave them a quick skim and saw some stuff that seems like it might be concerning, but maybe it's already been tested...

If nothing else, it would be good to:

- Refactor out the common code
- Explicitly state what's different

**Comment by stefhak** [comment]
We should test the examples eventually, but they use things that are not implemented yet so we can't test really.

**Comment by stefhak** [comment]
Noting that @adam-be is working on a patch that adds eslinting of the examples.

**Comment by adam-be** [comment]
That's done and pushed. @dontcallmedom is looking into moving the code from this repo to https://github.com/w3c/webrtc-respec-ci.

Since this issue was filed, @Jxck has, with the help of a few others, worked through and modernized all the examples. The currently pass our linting script which means that they parse OK and meet our specified style.

**Comment by Jxck** [comment]
I started working on fixing example, but not finished personally.
I think example should eventually tested over implementation, but its impossible now.
but we can separate examples in each file for starting point of that, also easy for maintenance.
