### ISSUE TITLE
Ambiguous connection state when list of transports are empty

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1305]
For `RTCIceGatheringState`, `RTCPeerConnectionState`, and `RTCIceConnectionState`, the appropriate state is ambiguous when the list for a peer connection's `RTCIceTransport` and `RTCDtlsTransport` are empty.

**Comment by taylor-b** [comment]
They should all be `new`. For `RTCIceGatheringState` this is already explicit: 

> new: Any of the RTCIceTransport s are in the new gathering state and none of the transports are in the gathering state, **or there are no transports**.

For the others, it's less obvious. For example:

> new: Any of the RTCIceTransport s are in the new state and none of them are in the checking, failed or disconnected state, or all RTCIceTransport s are in the closed state.

"No transports" could be thought to satisfy the condition "all transports are in the closed state", for some definition of the word "all". But we might as well make it explicit like it is for the gathering state.

@pthatcherg, maybe you have an opinion since you wrote this.
