### ISSUE TITLE
setLocalDescription algorithm for rejecting modification

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1330]
http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-setlocaldescription
contains an algorithm for rejecting modifications.

In the operations section we already have something in the "To set an RTCSessionDescription". In particular this:

> If elements of the SDP were modified, then reject p with a newly created InvalidModificationError and abort these steps.

Given that the SLD executes the algorithm as the last step how can InvalidModificationError happen in "set an RTCSessionDescription" anymore?

(the way things are currently written the algorithm will also operate in closed state)

The algorithm should execute as part of the "set an RTCSessionDescription", not call it as the last step.
Replacing step 2 of "set an RTCSessionDescription" should do the trick:

> If description is set as a local description, then run the following steps:

[... steps 1 to 7 from the algorithm]

**Comment by aboba** [comment]
@fippo Agree that InvalidModificationError can no longer happen in "set an RTCSessionDescription". 
Also, since description.sdp can now be null it appears that the steps in "set an RTCSessionDescription" could result in an "sdp-syntax-error" even when SLD is called correctly. 

In JSEP Section 5.5, the check against the last call to createOffer/createAnswer is done after checking the type against the current state (e.g. after Step 3 in "set an RTCSessionDescription").  So I would propose the following:

a. Delete Step 2 in "set an RTCSessionDescription". 
b. Move steps 6 and 7 in SLD to after the new step 2 in "set an RTCSessionDescription"
c. Change step 8 in SLD to "Return the result of setting the RTCSessionDescription indicated by the (potentially modified) description."

**Comment by fippo** [comment]
That sounds like a quite elegant solution!
