### ISSUE TITLE
What happen to RTCDtlsTransport during ICE restart?

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1357]
This might be explained in other specs but I don't get the time to find it. 

- During ICE restart, what would happen to `RTCDtlsTransport` and its underlying DTLS connection? 
- Do the DTLS connection get transparently switch over to the new candidate pair?
- Do existing connections such as data channel and transceiver get interrupted?
- After restart, do the `transport` attribute of `RTCDtlsTransport` get switched to a new `RTCIceTransport`?

**Comment by ibc** [comment]
> Do the DTLS connection get transparently switch over to the new candidate pair?

Sure, otherwise this would not be "ICE restart".

> Do existing connections such as data channel and transceiver get interrupted?

No. RTP packets may be lost during the transition, but SCTP protocol will ensure that datachannel packets are not lost.

> After restart, do the transport attribute of RTCDtlsTransport get switched to a new RTCIceTransport?

I'm not sure whether performing ICE restart means dropping the previous `RTCIceTransport` and replacing it with a new one. If so, `RTCDtlsTransport.transport` should point to the new one.

**Comment by fippo** [comment]
Mind you that an ice restart may change the remote fingerprint.
Does that change the DTLS transport? How do the state transitions look like?

@aboba

**Comment by taylor-b** [comment]
An ICE restart doesn't completely blow away the ICE state; the existing ICE candidate pair continues to be used while the ICE restart is going on. So I think it would make more sense logically, and be simpler, for ICE restarts to not create new `RTCIceTransport` objects.

But there's also a question of what happens when a new DTLS association is formed. We could say that when a remote description is applied that indicates a new DTLS association, you get a new `RTCDtlsTransport` object. But if we do that, we really need some way of informing the application. I'd be  fine with just saying "the DTLS transport is like the ICE transport; multiple DTLS associations are conceptually handled by a single DTLS transport object". I think that's what people have assumed until now.

**Comment by nils-ohlmeier** [comment]
As @fippo pointed out since ICE restarts can result in getting connected to a new endpoint with a different certificate. Therefore after an ICE restart, if it suceeded, I think should result in a new DTLS connection getting established.

I guess you could try to be smart and compare old and new fingerprint to figure out if you are still connected to an endpoint with the same cert and therefore can keep using the DTLS connection.

My understanding is that an ICE restart basically means you do start from scratch again. In other words: ICE restart = restart the whole transport of the peer connection.

**Comment by nils-ohlmeier** [comment]
@taylor-b on the signaling layer I think it is pretty clear that you request a new DTLS association by providing a new tld-is value in your SDP.

But I agree that people so far seem to have assumed that the ICE transport and DTLS transport objects for a given PeerConnection stay the same even over ICE restarts or DLTS restarts.

**Comment by aboba** [comment]
@fippo Are you imagining a scenario where an Offer encapsulating an ICE restart might fork to a different destination?  In that situation, yes, the remote DTLS fingerprint could change - and the RTCIceTransport would actually be established to a different remote peer.  In ORTC, you'd have to create a new RTCIceTransport (based on a new RTCIceGatherer) as well as a new RTCDtlsTransport (because you can't call start twice).  So it wouldn't surprise me if this was also true in WebRTC 1.0.

**Comment by fippo** [comment]
@aboba yes, also since ORTC can't call [dtlsTransport.start](http://draft.ortc.org/#dom-rtcdtlstransport-start) again with different remote parameters. Internally this means the keying material of a dtls transport can not change which sounds quite sane. I don't expect 1.0 to be any different here, just not to expose details like *start*. 

(note that we've had a discussion in ORTC [here](https://lists.w3.org/Archives/Public/public-ortc/2017Mar/0007.html) which has some relevance, even though more at the ICE layer)

In the case of the remote fingerprint changing, when does the JS layer learn about the new DTLS transport object? The first chance is after SRD and I would also expect it to be available in [onselectedcandidatepairchange](http://w3c.github.io/webrtc-pc/#dom-rtcicetransport-onselectedcandidatepairchange).

I would expect the ice transport not to change during an ice restart. This is also consistent with the ability to query past candidates in getStats.

**Comment by aboba** [comment]
@fippo It makes sense that the changes would become visible after SRD.  However, exactly what happens is not well specified at present.  For example, does the old RTCDtlsTransport.state transition to "closed"?  Is there a new RTCDtlsTransport created in the "new" state?  Does the onstatechange EventHandler for the old RTCDtlsTransport get moved to the new RTCDtlsTransport automagically, or does the application somehow need to figure out that the RTCDtlsTransport has changed and set the EventHandler itself? 

And lastly:  will any implementers actually handle this corner case??

b.

**Comment by aboba** [comment]
Since this question has morphed into Issue https://github.com/w3c/webrtc-pc/issues/1406 I am closing it.
