### ISSUE TITLE
When is the dtmf attribute in RTCRtpSender set?

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1415]
I am preparing to write tests for the DTMF section, which require obtaining an instance of `RTCDTMFSender`. The `dtmf` field in `RTCRtpSender` is defined to be nullable. This leaves a few questions:

- Can the `dtmf` attribute be initially null and then become not null at a later time?

- The only place DTMF support is mentioned in JSEP is when setting remote description with m= section having telephone-event lines. Does this means under that condition we can expect `sender.dtmf` to be set?

- When calling methods such as `addTransceiver('audio')`, can we expect the returned `sender.dtmf` to be set?

**Comment by taylor-b** [comment]
> The only place DTMF support is mentioned in JSEP is when setting remote description with m= section having telephone-event lines. Does this means under that condition we can expect sender.dtmf to be set?

I think that was the intention. We talked about RTCDTMFSender in the last virtual interim, and this was briefly brought up.

However... what happens if you apply another remote description that removes the "telephone-event" format? Does `dtmf` become null again? What happens if the application holds onto the `RTCDTMFSender` object and tries to call `insertDtmf` in this state? I think we still need to answer those questions.

**Comment by aboba** [comment]
One way to address the problem would be to add a `canInsertDTMF` attribute as in [ORTC](http://draft.ortc.org/#rtcdtmfsender*).
