### ISSUE TITLE
setConfiguration({ peerIdentity }) when there is no initial peerIdentity

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1456]
`setConfiguration` says:

>  If configuration.peerIdentity is set and its value differs from the target peer identity, throw an InvalidModificationError.

`setRemoteDescription` says

> The target peer identity cannot be changed once set.

If a peer connection is initially constructed without a `peerIdentity`, there is no target peer identity established, so it is not set. So when `setConfiguration()` is called with a new `peerIdentity`, is there error thrown?

**Comment by aboba** [comment]
I would assume not, because `peerIdentity` was not set when `setConfiguration()` was called.

**Comment by taylor-b** [comment]
So basically, we want to say "If `configuration.peerIdentity` is set, and `[[Configuration]].peerIdentity` is not set..."?

**Comment by aboba** [comment]
@jan-ivar If `peerIdentity` is not set on construction, can it be added later?

**Comment by jan-ivar** [comment]
That's my best reading of: The (presence of the) [peerIdentity](http://w3c.github.io/webrtc-pc/#dom-rtcconfiguration-peeridentity) dictionary member *"Sets the target peer identity for the RTCPeerConnection."*- and *"The target peer identity cannot be changed once set."*

Check with @martinthomson though if this was the intent, in case there's some security reason to not allow this.

**Comment by martinthomson** [comment]
To @aboba's question, yes, you could set it later, but only if it agrees with the current target peer identity.

So the challenge with `setConfiguration()` is that it can be called after the session is established.  If the current peer is unidentified, then we have a problem because the session now disagrees with the configuration.

It seems like the right solution here is to define an internal slot `[[TargetPeerIdentity]]`, which can three states: unspecified, null, and a string value.  This is initially unspecified.  Specifying a value using `setConfiguration()` sets the value to null/string.  Connecting sets the value to null/string.  If `setConfiguration()` attempts to set a value and it isn't either the same as the current value, or the current value is unspecified, then `setConfiguration()` fails.  The same process applies when connecting.
