### ISSUE TITLE
setLocalDescription() with empty string sdp is allowed to pass without calling createOffer/createAnswer

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1463]
#1333 adds the `[[LastOffer]]` and `[[LastAnswer]]` slots, which is initialized to `''`. In the new steps for set session description, `InvalidModificationError` is thrown based on string equality comparison with `[[LastOffer]]` and `[[LastAnswer]]`. This means user can pass empty string sdp without calling `createOffer`/`createAnswer`.

**Comment by aboba** [comment]
I don't think it will be "allowed to pass". Instead of being rejected with an `InvalidModificationError`,  step 5 indicates it would be rejected with `RTCError`: 

"5. If the content of description is not valid SDP syntax, then reject p with an RTCError (with errorDetail set to "sdp-syntax-error" and the sdpLineNumber attribute set to the line number in the SDP where the syntax error was detected) and abort these steps."

**Comment by soareschen** [comment]
Hmm that is correct, though a bit unexpected. Does this means setLocalDescription with null sdp without first calling createOffer/createAnswer also rejects with `RTCError`?

**Comment by aboba** [comment]
Since this isn't an invalid SDP modification, rejection with `RTCError` is the expected behavior.
