### ISSUE TITLE
Transceiver kind definition is circular.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1472]
@fippo asked: "so i can determine the kind of an RTCRtpSender by looking at `sender.track.kind`, right? - now... what if I called `sender.replaceTrack(null)`?"

Interestingly, the [replaceTrack algorithm](http://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-replacetrack) says: *"If `withTrack` is non-null and `withTrack.kind` differs from the [transceiver kind](http://w3c.github.io/webrtc-pc/#dfn-transceiver-kind) of transceiver, return a promise rejected with a newly created `TypeError`."*

Encouraging, except [transceiver kind](http://w3c.github.io/webrtc-pc/#dfn-transceiver-kind) is defined as: *"The* ***transceiver kind*** *of an RTCRtpTransceiver is defined by the kind of the associated RTCRtpReceiver 's MediaStreamTrack object."*

A circular definition.

We should fix transceiver kind to be an internal slot, so the kind information is not lost, to outlaw:
```js
let sender = addTrack(stream.getVideoTracks()[0], stream);
await sender.replaceTrack(null);
await sender.replaceTrack(stream.getAudioTracks()[0], stream); // circumvents TypeError

**Comment by taylor-b** [comment]
It's not a circular definition, because (as currently specced) an `RTCRtpTransceiver` has a 1:1 mapping with an `RTCRtpReceiver`, which has a 1:1 mapping with a `MediaStreamTrack`. `sender.replaceTrack(null)` will not make the receiver's track `null`. `transceiver.receiver.track.kind` will still be `"video"`.

Though, with some things being proposed recently (such as https://github.com/w3c/webrtc-pc/issues/1181), those 1:1 mappings could change. So defining the `kind` independently probably wouldn't hurt us.

**Comment by jan-ivar** [comment]
Thanks @taylor-b I read it wrong. Closing. As for https://github.com/w3c/webrtc-pc/issues/1181 I'm hopeful we'll get https://github.com/w3c/webrtc-pc/pull/1402 merged which may suffice.

**Comment by fippo** [comment]
my original use-case is that I'd like to search a sender of the same kind by iterating getSenders() to call replaceTrack on it. It might be easiest to expose `kind` on the sender as well.
