### ISSUE TITLE
Direction of newly created transceiver in setRemoteDescription

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1473]
In the tip of tree draft, Step 2.2.8. says:

> 1. Let direction be an RTCRtpTransceiverDirection value representing the direction from the media description, but with the send and receive directions reversed to represent this peer's point of view.

> 3.3. Create an RTCRtpTransceiver with sender, receiver and direction, and let transceiver be the result.

But section 5.9. of JSEP says:

> If no RtpTransceiver was found in the previous step, create one with a recvonly direction.

Not sure if that is a mistake in JSEP, or I have missed something else.

**Comment by taylor-b** [comment]
JSEP is correct. If I get a "sendrecv" offer, but I don't intend to send anything, I should respond with "recvonly".

**Comment by soareschen** [comment]
Hmm my interpretation for JSEP is that if there is no suitable transceiver exist, the newly created transceiver has `recvonly` direction regardless of direction specified in the m= section. 

For example in a fresh state, `setRemoteDescription(offer)` with one m= section with direction `recvonly` (meaning `sendonly` for the local peer right?), it still result in creating a transceiver with direction `recvonly`. The same applies to m= sections with `inactive` direction.

If JSEP is correct then step 2.2.8. in section 4.4.1.6. of webrtc-pc is inconsistent with it, because it simply creates new transceiver with direction reversed from what's specified in the m= section.

**Comment by taylor-b** [comment]
That's correct. So if a JSEP endpoint gets a "recvonly" offer, it will send an "inactive" answer. But `transceiver.direction` (the "desired" direction) will still be `recvonly`, so if a re-offer changes the m= section to "sendrecv" or "sendonly", the re-answer will be "recvonly".

So this is all intentional, and carries over the behavior from before things got rewritten in terms of transceivers. And yes, the step that says "Create an RTCRtpTransceiver with sender, receiver and direction" is incorrect; it should be "Create an RTCRtpTransceiver with sender, receiver and a `recvonly` direction".

**Comment by soareschen** [comment]
> And yes, the step that says "Create an RTCRtpTransceiver with sender, receiver and direction" is incorrect; it should be "Create an RTCRtpTransceiver with sender, receiver and a recvonly direction".

Got it. So the spec need to be updated to reflect that. Thanks for explaining!
