### ISSUE TITLE
Validation of reordered readonly parameters in setParameters

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1492]
Step 7 of setParameters says:

> If parameters.encodings.length is different from N, or if any parameter in the parameters argument, marked as a Read-only parameter, has a value that is different from the corresponding parameter value returned from sender.getParameters(), abort these steps and return a promise rejected with a newly created InvalidModificationError. Note that this also applies to transactionId.

And the description for `codec` field for `RTCRtpParameters` says:

> When using the setParameters method, the codecs sequence from the corresponding call to getParameters can be reordered and entries can be removed, but entries cannot be added, and the RTCRtpCodecParameters dictionary members cannot be modified.

This seems to require step 7 to handle reordering/dropping of readonly parameters as well, but it is a bit ambiguous in step 7 whether reordering/dropping is allowed. Even if it allows, does this mean that `encodings` elements can be reordered, and `headerExtensions` elements can be reordered/dropped as well?

**Comment by aboba** [comment]
My take would be that reordering/dropping of `encodings` should not be allowed.  Reordering `headerExtensions` does not make a difference, so I'm not clear this (or dropping) should be allowed either. 

@taylor-b What do you think?

**Comment by taylor-b** [comment]
The order of the encodings is equivalent to their precedence, which is negotiated in SDP via "a=simulcast". So it doesn't make sense to try to reorder them, because it would require renegotiation, which none of the other things you can change in `setParameters` require.

We _could_ say "the order in 'a=simulcast' isn't absolute, it's a 'proposed preference', so the sender can choose to override it." Similar to what we did for codecs. But this would still be getting into "new feature" territory, so unless there's a good use case I'd suggest just not allowing this.

**Comment by soareschen** [comment]
One more thing to note for reordering validation is that current algorithm do not take into account repeated elements in the array. The clause _"If parameters.encodings.length is different from N"_ seems to be specifically added to prevent repeated elements in `encodings`, but the same is not applied to `codec`.

**Comment by aboba** [comment]
@stefhak Can we close this issue since there is a merged PR?
