### ISSUE TITLE
Support for RRID and FEC/RTX RIDs?

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1496]
As noted in the message below,  it is suggested that FEC/RTX streams can have their own RIDs and that the RRID is needed in order to support robustness (RTX/FEC) in simulcast:

See: https://www.ietf.org/mail-archive/web/mmusic/current/msg18035.html

Does it make sense to expose the RRID somewhere, such as in `RTCRtpRtxParameters` and `RTCRtpFecParameters` ?  What about FEC/RTX RIDs?

**Comment by stefhak** [comment]
@aboba what would be the use of the exposed RRID?

**Comment by aboba** [comment]
The link indicates that the RRID links RTX/FEC protection/retransmission streams to the corresponding simulcast streams.

**Comment by pthatcherg** [comment]
If there were an .rrid on the rtx or fec parameters, it would have to be equal to the encoding .rid, would it not?  So doesn't that mean it's really a bool of .usesRrid?  And if so, why is that useful for the app to know?

**Comment by stefhak** [comment]
In response to https://github.com/w3c/webrtc-pc/issues/1496#issuecomment-317640021: I understand that the UA must be able to associate what encoding FEC and RTX streams belong to in order to be able to use the FEC/RTX data to recover from packet losses. But it's still not clear to me why it would be helpful for the app to have this info.

**Comment by aboba** [comment]
Discussion on the MMUSIC mailing list: https://www.ietf.org/mail-archive/web/mmusic/current/msg18062.html
