### ISSUE TITLE
Default identity provider

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1509]
There are numerous mentions that if no identity provider is set, the browser may use a default IdP configured. How do application know whether there is a default IdP set, and the details of that IdP?

I also feel that there are some privacy implications of having a default IdP. Does this means any website can find out the identity of a user if they are logged in to a default IdP?

**Comment by soareschen** [comment]
Having default identity provider could also cause problems for applications that do not care about IdP. If the user is not logged in to the default IdP or if the IdP produce error, `createOffer()` and `createAnswer()` would fail.

This means pretty much almost all of existing WebRTC apps today would fail on browsers with default IdP and unlogged in users.

**Comment by fluffy** [comment]
The assumption has been that for a given website, the browser would ask use user if it wanted to grant permission to use a given default provider. I imagine it would  be similar to the UI for deciding when to show client certs to a website.

**Comment by martinthomson** [comment]
I'm going to propose that we remove the notion of a default identity provider from the current specification.  If we ever reach the point that we have one, then we can add the idea back.  The problem here is that it has all sorts of far-reaching consequences, particularly if you start to consider interactions with permissions.
