### ISSUE TITLE
Ordering of stream "addtrack"/"removetrack" events vs. "track" event

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1599]
This is equivalent to https://github.com/w3c/webrtc-pc/issues/1568, but for the "addtrack" and "removetrack" events rather than "mute".

The "When the User Agent initiates adding/removing a track" algorithm we reference implicitly from mediacapture-main queues a task, which means events will happen after the "track" event rather than before. If we want them to fire before, we need to make the algorithm in mediacapture-main more flexible (see comments towards the end of https://github.com/w3c/webrtc-pc/pull/1519).

This is desirable, because `event.streams` are fully populated by the time the `"track"` event fires:
```js
pc.ontrack = event => console.log(event.streams[0].getTracks().length); // 2
```
...so you'd expect an `onaddtrack` added at that point to only hear about future tracks:
```js
pc.ontrack = event => event.streams[0].onaddtrack = () => console.log("even more tracks!");
```
This is how [implementations work](https://jsfiddle.net/jib1/5wzj6a7h/). You would **not** expect to hear about those already in there (spec).

**Comment by fippo** [comment]
I just encountered this issue fixing a bug in my shim and what jib describes here makes a lot of sense.

**Comment by henbos** [comment]
Same comment as I put in https://github.com/w3c/webrtc-pc/pull/1667#discussion_r153076052:

- When we update which tracks belong to which stream we should enqueue a task streamAddTrack/streamRemoveTrack to streamAddTracks/streamRemoveTracks.
- We proceed to update all states of the PC (meaning the state of transceivers, senders, receivers, streams and tracks) so that by the time we fire these events, it is safe to inspect the state of the PC without assumptions about order of events.
- We do not schedule a task to do anything, this must all be synchronous, or else the events fires after the promise resolves or the state of the PC may become obsolete (imagine calling SRD twice in a row, if you schedule to fire a task when that task fires for the first SRD you will see the effects of the second SRD when you inspect the PC).
- Before resolving the SRD promise, loop through all tasks and fire them.

Doing it any other way has observable side-effects.

**Comment by jan-ivar** [comment]
@henbos Given my concerns in https://github.com/w3c/webrtc-pc/pull/1667#discussion_r155406891, I'm going to submit a PR fixing the original probme here (moving events ahead of the "track" event), since I sense we're in agreement there. I suggest we open a new issue to discuss whether to go further than that.
