### ISSUE TITLE
Message text not localizable

### ISSUE THREAD

**Issue by r12a** [w3c/webrtc-pc#1605]
[from Addison Phillips, endorsed by the i18n WG]

http://w3c.github.io/webrtc-pc/#rtcpeerconnectioniceerrorevent

Error values can contain an attribute:

```
    readonly attribute USVString      errorText;
```

This appears to use the text defined [here](https://www.iana.org/assignments/stun-parameters/stun-parameters.xhtml#stun-parameters-6) and doesn't allow for localization of the error message. Shouldn't it allow for localization (complete with language and bidi support)

**Comment by adamroach** [comment]
The field you're referring to comes directly from the STUN/TURN server, and is not generated locally. It is completely analogous to the `XMLHttpRequest.statusText` field, and the same l18n considerations apply (i.e., it's a server issue, not an API issue).

**Comment by aboba** [comment]
Since this is a server, not an API issue, I am closing it.

**Comment by aphillips** [comment]
I don't agree that this is strictly a server issue. The server does generate the message, but it can know what language and base direction the error is generated in; it is incredibly useful to transmit this information with any human readable string--cf. our document [String-Meta](https://w3c.github.io/string-meta/). Because we didn't notice that this issue was unresolved and because this is not the first or last spec to have unadorned strings for error messages, I don't propose to block webrtc over it. But I would prefer if natural language strings were provided with metadata.

**Comment by dontcallmedom** [comment]
right now, the [protocol used by the server to send the error doesn't support localization metadata](https://tools.ietf.org/html/rfc8489#section-14.8), so there is really nothing the API itself could report as far as I can tell.
