### ISSUE TITLE
RTCDataChannel::send() steps are not proper.

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#163]
> Originally reported on W3C Bugzilla [ISSUE-25102](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25102) Thu, 20 Mar 2014 04:52:17 GMT
> Reported by Kiran
> Assigned to 

step 2: should be changed from 
2. If channel’s readyState attribute is connecting, throw an InvalidStateError exception and abort these steps.

to

2. If channel’s readyState attribute is closing or closed, throw an InvalidStateError exception and abort these steps.

If readyState attribute is new or connecting state, then step 4: "If channel’s underlying data transport is not established yet" will give sufficient support.

Since chances are there to get the readyState converted from connecting to open, during the time of buffering, it is better to follow this order.

**Comment by stefhak** [comment]
In response to Kiran: It seems that if the data could not be sent, the application will be notified: "Attempt to send data on channel's underlying data transport; if the data cannot be sent, e.g. because it would need to be buffered but the buffer is full, the user agent MUST abruptly close channel's underlying data transport with an error."
Does this sound OK?

**Comment by stefhak** [comment]
No feedback from the person raising the Issue. I'm closing.
