### ISSUE TITLE
OAUTH-POP-KEY-DISTRIBUTION IETF draft has been replaced by ACE-CWT-PROOF-OF-POSSESSION

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/webrtc-pc#1642]
The IETF RTCWeb WG chairs (Sean Turner and Ted Hardie) indicated to the W3C WebRTC WG chairs that the [OAUTH-POP-KEY-DISTRIBUTION](https://datatracker.ietf.org/doc/draft-ietf-oauth-pop-key-distribution/) draft (now marked as "expired Internet-Draft / no longer active" ) was being replaced by the [ACE-CWT-PROOF-OF-POSSESSION](https://datatracker.ietf.org/doc/draft-ietf-ace-cwt-proof-of-possession/).

I filled an issue on speref for that: https://github.com/tobie/specref/pull/413

Looking at our doc the changes that are required are more than just `s/[[OAUTH-POP-KEY-DISTRIBUTION]/[ACE-CWT-PROOF-OF-POSSESSION]/` so someone familiar with those concept should look at this.

> > On Oct 19, 2017, at 14:17, Ted Hardie wrote:
> > 
> > The situation with the OAUTH draft is more complicated, as the draft expired and the work was taken up in the ACE working group at the Prague meeting (by the same authors).  I believe that means the reference should be updated to draft-ietf-ace-oauth-authz, but Sean should be able to confirm or provide a correct reference.
> > 
> > regards,
> > 
> > Ted
> 
> This summary is correct. But, this is the draft to refer to:
> https://datatracker.ietf.org/doc/draft-ietf-ace-cwt-proof-of-possession/
> 
> spt

**Comment by fluffy** [comment]
@bifurcation - this might relate to update of rtcweb security drafts. Right now the W3C spec normatively refs the ACE-CWT-PROOF-OF-POSSESSION and that likely needs to change.

**Comment by misi** [comment]
**HTTP vs CoAP?**
RFC7635 refers to OAUTH-POP-KEY-DISTRIBUTION in the non normative part. 
In my understanding it refers mainly as the http transport between AS and OAuth client. 
Please notice that RFC7635 defines an _own defined special binary token_ (It does not use JWT!) so I think it may misleading to say that  that ace-cwt-proof-of-possession is the relevant replacement of the OAUTH-POP-KEY-DISTRIBUTION (at least from the RFC7635 point of view).
The ace-cwt-proof-of-possession is relevant only if we  want to totally update RFC7635 to use CWT instead of the binary token that is defined in https://tools.ietf.org/html/rfc7635#section-6.2. 

IMHO the OAUTH-POP-KEY-DISTRIBUTION replacement it the draft-ietf-ace-oauth-authz
And the main difference in my understanding is the request-response protocol replacement, so draft-ietf-ace-oauth-authz use CoAP, as the http replacement because of the constrained environment.

> CoAP is an application layer protocol similar to HTTP, but
>    specifically designed for constrained environments.

I think WebRTC 1.0 main use case is audio/video chat and most use case depends on http, so I don't think it would be big benefit to move this TURN auth credential information request form HTTP to CoAP in most cases!
+1 CoAP as a new UDP protocol may could cause new firewall traversal problems..


**Options:**
1. do nothing stick as it is actually with http and OAUTH-POP-KEY-DISTRIBUTION 
2. step back little bit in webrtc-pc spec and express that the OAUTH-POP-KEY-DISTRIBUTION (so http credential distribution) is only one way and so we give one example, and specify in normative part only that we need three information Access-Token, mac-key, kid and not define what protocol the client will use to get this information. 
3. Update RFC7635 wit a new RFC to use CWT instead of own binary token.

I could go along with all, but prefer 1 or 2 because of  focus on stability, (avoid new features) and we because there is already a working implementation of RFC7635 in coTURN. 

The right solution maybe to rewrite RFC7635, 
so considering the option 3, but IMHO we should keep it back and do it in WebRTC-NV.

Please let me know your thoughts!

**Comment by alvestrand** [comment]
Rewriting RFC 7635 is an IETF action, not a W3C action.
So we need to toss that idea over the wall (and then run to the other side of the wall to catch it :-) )

**Comment by misi** [comment]
@alvestrand I fully agree. 

RFC7635 authors are mostly from Cisco. 
@fluffy do you know any plan that the Authors want to to update it, or should I try to start work on it?

**Comment by fluffy** [comment]
I think the Cisco people had very little to do with that and it was basically written by Justin. I'd ping him.

**Comment by misi** [comment]
@fluffy Sorry then, I just saw the 3 authors (T. Reddy, P. Patil, R. Ravindranath) from Cisco on RFC7635 and only Justin in other hand, and I wrongly assumed it. thx.

**Comment by tireddy2** [comment]
OAuth 2.0 framework does no impose any specific format or structure, at the time of developing the specification, proof-of-possession for JWT (JSON) was not picked as it would significantly increase the size of the access token (Proof-of-Possession Key Semantics for JSON Web Tokens (JWTs) https://tools.ietf.org/html/rfc7800 also points to the obsolete reference).

ACE WG has started discussing using OAuth 2.0 for constrained devices using COAP (runs over both UDP and TCP) and CBOR, and hence CWT (CBOR) binary web token came into play. 
https://tools.ietf.org/html/draft-ietf-ace-cbor-web-token-14, https://tools.ietf.org/html/draft-ietf-ace-cwt-proof-of-possession-02 and https://tools.ietf.org/html/draft-ietf-ace-oauth-authz-11 are going through changes and not even close to WGLC. 

Using ACE-CWT-PROOF-OF-POSSESSION only requires changes to the format of the access token and does not require any changes to STUN protocol updates done in RFC7635. 

We can publish a new draft to use CWT instead of the binary access token defined in RFC7635.  The new draft will have to wait for a long time for the above drafts to finalize. In addition, both W3C and TURN server will have to agree to use CWT(CBOR).

The best way to move forward immediately as per the suggestion from Harald is for the purposes of W3C webrtc-pc document, is to say that when RFC 7635 is used the details of the token format are not further described here but left to the deployment to decide.

**Comment by misi** [comment]
I think decision has made. => PR needed.
@alvestrand will you make it, or shall I make it?

@tireddy2 
From WebRTC + RFC7635 point of view I still miss an RFC that describes the OAuth PoP key distribution over HTTP. As it was mentioned draft-ietf-oauth-pop-key-distribution-03 draft is no longer active.
I understand that OAuth PoP key distribution interest is moved to COAP, but  I don't know why the HTTP OAuth PoP isn't it finished => dead. 
I know HTTP in a constrained env is to expensive, but for a system that encodes media http shouldn't be a problem.
Correct me if I am wrong, but according RFC7635 Appendix example, and because WebRTC is strongly related to browsers, so I feel that we are still interested in OAuth PoP key distribution over HTTP.

OAuth Client<=>AS communication  over HTTP

On the wire:
- either RFC7635 or CWT token
- kid
- session key

IMHO Key distribution over COAP does not fit perfectly, complicates more the communication, and so I prefer to use HTTP.

Could you shade on it light, or point me where I could find more information about why OAuth PoP over HTTP idea is not finished and totally dropped?

Thanks in advance!

**Comment by tireddy2** [comment]
https://datatracker.ietf.org/doc/draft-ietf-oauth-pop-architecture/history/
shows the draft was ready from the WG and was sent to ISEG review (Security
AD had approved the spec).
You may want to contact Hannes Tschofenig (OAuth WG) chair to figure out
the actual reason.

Cheers,
-Tiru
