### ISSUE TITLE
Provide changelog for the spec in new editors draft workflow

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#1648]
With the [new editors draft workflow](https://lists.w3.org/Archives/Public/public-webrtc-editors/2017Oct/0001.html), we need a new approach to manage changelogs, some of which are discussed in the thread starting in [this message](https://lists.w3.org/Archives/Public/public-webrtc-editors/2017Oct/0004.html)

**Comment by adam-be** [comment]
We haven't provided cleaned-up change logs for a while now and I haven't seen any complaints about it. So the question is how much work we should put into this if it's not used by the group. For now I think we should just keep PR titles tidy and informative, and not be afraid to edit those who aren't.

**Comment by benjamingr** [comment]
@adam-be I would read changelogs. I'm not an implementor but I'm working a lot with the technology and changes are relevant to me.

**Comment by adam-be** [comment]
Glad to hear that at least someone are reading them. :)

Let's do some manual updates, like before, and then see what we can automate.

**Comment by aboba** [comment]
Can we close this issue?

**Comment by stefhak** [comment]
Nothing has been added to the change log section since October 2 2017, it seems like a lot of work to be able to do a decent update. Given that we've not heard complaints (even though I'm noting @benjamingr's [comment](https://github.com/w3c/webrtc-pc/issues/1648#issuecomment-351717205) above) I'm closing this issue now. Feel free to re-open if you think that is wrong.
