### ISSUE TITLE
enqueue an operation: is executing async?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1711]
step 5 of [enqueue an operation](http://w3c.github.io/webrtc-pc/#enqueue-an-operation) says
> If the length of [[Operations]] is exactly 1, execute operation.

Is this synchronous or async? In terms of code (see [fiddle](https://jsfiddle.net/dgvdg7xj/1/)):
```
var pc = new RTCPeerConnection();
navigator.mediaDevices.getUserMedia({audio: true})
.then(stream => {
  var p = pc.createOffer();
  pc.addTrack(stream.getTracks()[0], stream);
  return p;
})
.then(offer => {
  console.log(offer.sdp);
})
```
Does offer have an m-line? Currently the answer in Chrome is "no" and in Firefox it is "yes".

editorial drive-by nit: the paragraph above that section that describes the operations queue should be placed inside the section

**Comment by jan-ivar** [comment]
It's synchronous ***and*** the offer should have an m-line.

That's because `createOffer` and `createAnswer` [were written to loop](https://github.com/w3c/webrtc-pc/pull/875) as long as state changes:

*"If connection was modified in such a way that additional inspection of the system state is necessary, or if its configured indentity provider is no longer provider, then in parallel begin the steps to create an offer again, given p, and abort these steps."*

**Comment by jan-ivar** [comment]
@fippo. I hope this clarifies your question. Again, the difference you're seeing is a bug in Chrome, unrelated to this line in the spec.

The drive-by nit is merged in https://github.com/w3c/webrtc-pc/pull/1715

Please re-open if you see an unresolved issue.

**Comment by fippo** [comment]
@jan-ivar explained things to me a bit more.

createOffer turned out to be a bad example. The reason this must be synchronous can be seen in [addIceCandidate](http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addicecandidate):
It inspects the state of the peerconnection (remoteDescription) and reject with InvalidStateError.
The Promise returned is already rejected -- https://stackoverflow.com/a/35820220/918910 offers a fancy hack to inspect that
