### ISSUE TITLE
"track" event will fire extra times if applying multiple remote offers

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1729]
> If direction is "sendrecv" or "recvonly", and transceiver's [[CurrentDirection]] slot is neither "sendrecv" nor "recvonly", process the addition of a remote track for the media description, given transceiver and trackEvents.

If I follow these steps to the letter, then if I apply multiple remote offers in a row (which JSEP does allow), I'll get multiple track events, because [[CurrentDirection]] will still be null.

Is the solution to replace "[[CurrentDirection]]" with "the direction of the corresponding m= section in the last applied remote description," or something along those lines? Remember that the purpose of this rule is to get an event when the direction changes from "sending" to "not sending" and back again.

**Comment by docfaraday** [comment]
It might be best to treat applying multiple descriptions in a row as having a rollback in between, and fix issue #1706. That could avoid this problem, and others.

**Comment by taylor-b** [comment]
> It might be best to treat applying multiple descriptions in a row as having a rollback in between

If this were the intention, then why support additional offers in the "have offer" state in the first place? We could just say "this isn't allowed" and let the application do the rollback itself. Plus, I think doing this would have its own problems. The rollback would remove the previously created transceiver, and the new remote offer would create a new one, which seems counter-intuitive.

Also, when you say "fix issue #1706," do you mean "fire events on rollback" or not?

**Comment by docfaraday** [comment]
> If this were the intention, then why support additional offers in the "have offer" state in the first place? We could just say "this isn't allowed" and let the application do the rollback itself.

Syntactic sugar.

> Plus, I think doing this would have its own problems. The rollback would remove the previously created transceiver, and the new remote offer would create a new one, which seems counter-intuitive.

_Not_ doing this seems counter-intuitive to me. A second SRD(offer) doesn't make any sense to me unless it means "disregard that previous SRD (ie; rollback), and instead use this new one". Maybe we could word-smith this a little bit by deferring all of the various track/stream/transceiver updates until the new offer is applied.

> Also, when you say "fix issue #1706," do you mean "fire events on rollback" or not?

I mean fire the events on rollback. Consider a scenario where we do a subsequent SRD(offer) that disables the send bit on some m-sections, and maybe adds some m-sections; I would expect that we would see removetrack/mute events for the old offer, and then some track events for the new tracks. Or, for even more fun, consider a SRD(offer) that adds an m-section, and a subsequent SRD(offer) that doesn't have it.

**Comment by taylor-b** [comment]
Hmm. I guess I always thought of setting multiple offers as being comparable to setting multiple PR-answers. Also, changes to JSEP may be required to do what you describe, since JSEP does deal with transceivers and doesn't say anything about removing a transceiver when calling `setRemoteDescription(offer)` twice.

**Comment by jan-ivar** [comment]
We seem to agree that relying on [[CurrentDirection]] here is wrong.

That reliance could also mess up setting the media stream associations, which technically can change in a second SRD (through sdp fiddling, since the sender side API surprisingly seems to offer no way to change stream associations once a transceiver has been created).

I'd planned on fixing this by lifting the call to [set the associated remote streams](http://w3c.github.io/webrtc-pc/#set-associated-remote-streams) out one level, basically always call it with the msids (or empty list if send-bit is off), since the consequent actions are idempotent (`muted`, `addtrack` and `removetrack` won't fire twice).

Not so for the `track` event, and a track may have zero stream associations, so maybe we need a [[PendingDirection]] which we set at end of SRD?

As to implicit rollback, an argument against it is the availability of explicit rollback. OTOH it might simplify to have fewer behaviors.

**Comment by taylor-b** [comment]
> Not so for the track event, and a track may have zero stream associations, so maybe we need a [[PendingDirection]] which we set at end of SRD?

If it's not too complex, that may be preferable to "the direction of the corresponding m= section in the last applied remote description" like I suggested earlier.

**Comment by alvestrand** [comment]
What's the language that permits applying multiple descriptions in a row and not setting [[CurrentDirection]] between each application?

**Comment by stefhak** [comment]
Regarding https://github.com/w3c/webrtc-pc/issues/1729#issuecomment-357493553 I think it is clear from JSEP that multiple remote offers can be applied in sequence (also from the state diagram in sectio 4.3.1). And [[CurrentDirection]] would not be updated until SLD(answer) is done IIUC.

To comment on https://github.com/w3c/webrtc-pc/issues/1729#issue-287276834 : If I read correctly, you'd also get a new track event each time you (from a stable state with a "sednrecv" or "sendonly" transceiver) change direction to "recvonly" / "inactive", followed by associated signaling, and then back to "sendrecv"/"sendonly", createOffer, SLD(offer), send off, and the remote endpoint applies the offer.

Is that what we want?

**Comment by jan-ivar** [comment]
> If I read correctly, you'd also get a new track event each time you ...

If you mean remotely, then yes, that's the design I believe, and doesn't count as "extra" wrt this issue (in that if you'd additionally applied SRD twice in your example, you'd get twice as many track events as you would otherwise).

**Comment by stefhak** [comment]
@jan-ivar sorry for derailing (I agree this is not the scope of this Issue), but for clarity the spec now says that (assume a stable state, a "sendrecv" pair of transceivers (one at each endpoint), the remote track event has been fired):
- setting direction to "recvonly", followed by SDP O/A, would (when the offer is set at the remote side) give a "mute" event on that remote track
- then, changing direction back to "sendrecv" followed by SDP O/A, would (when the offer is set at the remote side) give a "track" event on the remote PeerConnection
This is not what I would have expected, I would (naïvely) have expected an "unmute" event on the track. I have no desire to propose changes if this is what have agreed on, it just seems strange. BTW, in this example, what would the mute attribute of the track of the track event read?

**Comment by jan-ivar** [comment]
@stefhak [See](http://w3c.github.io/webrtc-pc/#dom-rtcrtpreceiver-track) *"If and when packets are received again, the `unmute` event is fired at `track`."*

The `unmute` event will fire once packets come in, which due to early media, may happen before the OA negotiation is complete (on the offerer side this can happen before or after SRD has been called; on the answerer side I believe it can only happen before SRD if currentDirection says it's listening).

Let me turn the question around: Why would you only expect the `track` event on the initial OA exchange (keeping in mind that in the transceiver model, the remote track often exists prior to that first event as well)?

**Comment by stefhak** [comment]
@jan-ivar 

>Why would you only expect the `track` event on the initial OA exchange (keeping in mind that in the transceiver model, the remote track often exists prior to that first event as well)?

I guess I had the mental model that you get the `track` event when there is a new incoming track to consider. But never mind that, I guess you can design your code so that getting the event several times is no problem, e.g.
* check if the track is already handled - no need to do anything
* add it to a MediaStream used for rendering (or recording or whatever) - if the track is already a member this would be a no-op (from mediacapture-main: `If track is already in stream's track set, then abort these steps.`)

But that actually brings me back to the [first post here](https://github.com/w3c/webrtc-pc/issues/1729#issue-287276834): if multiple track events for the same is already handled by the app, why would getting it from multiple SRD(offer) be an issue?

**Comment by jan-ivar** [comment]
@stefhak The extra `track` event is probably fine. I think the remaining issue here is similar to https://github.com/w3c/webrtc-pc/issues/1706 in that double SRDs may leave things in an unexpected state. I've opened https://github.com/w3c/webrtc-pc/issues/1744 for that, so I think we can close this.
