### ISSUE TITLE
RTCRtpContributingSource.audioLevel has different type and range than similar fields in webrtc-stats 

### ISSUE THREAD

**Issue by na-g** [w3c/webrtc-pc#1734]
The [audioLevel](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcontributingsource-audiolevel) field of RTCRtpContributingSource is a byte with a range range of 0 to 127. The audioLevel field of [RTCRTPContributingSourceStats](https://w3c.github.io/webrtc-stats/#dom-rtcrtpcontributingsourcestats-audiolevel) and [RTCAudioStreamTrackStats](https://w3c.github.io/webrtc-stats/#dom-rtcaudiostreamtrackstats-audiolevel) are doubles with a range of 0.0 to 1.0. Is there compelling reason that RTCRtpContributingSource.audioLevel should differ in this regard? Should the same transform noted in the fields in the audioLevel fields webrtc-stats be applied to RTCRtpContributingSource.audioLevel so that they are directly comparable?

**Comment by jan-ivar** [comment]
@alvestrand @taylor-b Thoughts?

Firefox 59 goes to beta in 10 days, so we're considering pref'ing off `getContributingSources` and `getSynchronizationSources` until this is resolved.

**Comment by taylor-b** [comment]
I can't recall a good reason for making it a `byte`. I'd be fine with changing it; it's not implemented in Chrome yet.

**Comment by dontcallmedom** [comment]
the reason for making it a `byte` is documented in the spec:
> Both RFCs define the level as an integral value from 0 to 127 representing the audio level in negative decibels relative to the loudest signal that the system could possibly encode. Thus, 0 represents the loudest signal the system could possibly encode, and 127 represents silence.

(I have no opinion on whether this is a good or bad reason - @fluffy @alvestrand and @aboba [seem to have been involved in the design discussion back then](https://lists.w3.org/Archives/Public/public-webrtc/2015Jul/0109.html)

**Comment by foolip** [comment]
Hi all,

@rakuco and I are looking at [normative spec change without tests](https://docs.google.com/document/d/1kFYTqUMEbo9p87i6wAzORoicMWgHsuYwL2CgtvdhDaE/edit?usp=sharing) every week this quarter, and this week I took a look at https://github.com/w3c/webrtc-pc/pull/1736, since I'm a bit familiar with the tests that were written.

There are tests for `audioLevel` being a byte written by @soareschen (reviewed by @rwaldron) that now contradict what the spec says, in [RTCRtpReceiver-getSynchronizationSources.https.html](https://github.com/w3c/web-platform-tests/blob/524bea1dd8d0ad58733072bd4e8b8044042f589e/webrtc/RTCRtpReceiver-getSynchronizationSources.https.html#L64) and [RTCRtpReceiver-getContributingSources.https.html](https://github.com/w3c/web-platform-tests/blob/524bea1dd8d0ad58733072bd4e8b8044042f589e/webrtc/RTCRtpReceiver-getContributingSources.https.html#L77). (Found by grep.)

I've filed https://github.com/w3c/web-platform-tests/issues/9108 to keep track of the fact that the tests are now wrong, and looking through https://github.com/w3c/web-platform-tests/labels/webrtc before process transitions would probably be a good idea since the test results could otherwise be misleading, *especially* if someone has implemented the old behavior and passes those tests.

[CONTRIBUTING.md](https://github.com/w3c/webrtc-pc/blob/master/CONTRIBUTING.md#tests) suggests at least filing an issue like that, but this is a case where I think blocking the spec change on the test update would have been less work overall.

But I'm not just here to nag, if there are any bits of infrastructure that you all think would be useful to make it harder to overlook testing, I'd love to hear some ideas.

https://github.com/whatwg/html/issues/1849#issuecomment-351359904 describes the current state of this "project", and of particular interest could be the auto-filing of bugs, which in the best case can mean that if Chrome was passing a test and test was changed to fail, a bug would be automatically filed.

**Comment by alvestrand** [comment]
we have enabled auto-filing of Chromium bugs on both the webrtc component and the mediacapture-main component, but haven't seen any bugs yet. Good point! @jan-ivar can you take care of the test?
(We're pretty sure that nothing passes the test in its old form - it's not possible to  generate test data using a browser, and we don't know of anyone who's created RTP-generating tools that make it possible.)

**Comment by foolip** [comment]
@jan-ivar, can I assign https://github.com/w3c/web-platform-tests/issues/9108 to you?

**Comment by foolip** [comment]
> We're pretty sure that nothing passes the test in its old form - it's not possible to generate test data using a browser, and we don't know of anyone who's created RTP-generating tools that make it possible.

Sounds like a serious problem. Would a browser that implements more of the spec pass these tests, or would they still fail? If so, aren't the tests plainly broken?

**Comment by alvestrand** [comment]
If the test is written correctly, browsers should pass when not implementing audioLevel, when implementing audioLevel according to the old spec, and when implementing audioLevel according to the new spec - because "missing" is a legal value under the test conditions we can generate using the present test framework.
It would be correct to test the negative - contributingSource MUST NOT be present when the source is another browser.

**Comment by foolip** [comment]
Ah, right, it's an optional dictionary member, so if it's not there, unless some prose says otherwise, that's allowed.

So, in order to really test this, there must be something that sends RTP with this header present. Is this part of a bigger collection of untestable things, and should I file an "untestable" issue on web-platform-tests for tracking?

**Comment by alvestrand** [comment]
Do file an "untestable" issue. It's testable in KITE if they find an open source MCU that does media mixing to add to the test enviroment.

**Comment by foolip** [comment]
I have filed https://github.com/w3c/web-platform-tests/issues/9213, please comment there if that seems like a good or not so good idea.

**Comment by agouaillard** [comment]
Yes guys, by all means make a list as we are working an such media MCU / SFU and other tools specifically to address them in KITE. Copy either sergio or myself and/or harald on google side, to make sure we are aware of it. cheers. We have decided this week to start working on Media server needing task with harald next week anyway (unified plan, simulcast, ..)

**Comment by foolip** [comment]
Made some guesses in https://github.com/w3c/web-platform-tests/issues/9213#issuecomment-361001489, corrections welcome. If any software is written for test purposes, it would be good if it could be run as part of wpt as well. https://github.com/w3c/web-platform-tests/issues/9213 is as concrete as my "plans" are now, just like to keep track of why testing isn't working well across the web platform.
