### ISSUE TITLE
Add direction change as reason for "mute" event

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1737]
Section 5.3, description of the `track` attribute has
```When one of the SSRCs for RTP source media streams received by receiver is removed (either due to reception of a BYE or via timeout), the mute event is fired at track.```

in its text. However, https://w3c.github.io/webrtc-pc/#set-description can also lead to the track becoming muted ("`For each track in muteTracks, set the muted state to the value true.`") for certain changes of `direction`. Should we add this reason for firing `mute` to the `track` attribute description in 5.3?

**Comment by alvestrand** [comment]
I think the problematic thing here was that if the track is muted due to setRemoteDescription, and there were packets straggling in late, it could be unmuted while the transceiver direction is invalid for unmuting.

I think the proper solution is to guard the unmuting in 5.3 by a check on the transceiver state: "If packets are received again, the track is muted, and the associated transceiver's direction is still sendrecv or recvonly, unmute the track".

**Comment by jan-ivar** [comment]
I believe that's what https://github.com/w3c/webrtc-pc/issues/1707 is about.
