### ISSUE TITLE
Private key access?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1739]
From discussion of #1723 it emerges that it's reasonably clear that retrieving a certificate requires that you can use the private key it belongs to, but Javascript shouldn't give access to the actual keying material.

We need to review whether the requirements we have in the spec are the right ones here.

**Comment by alvestrand** [comment]
Privacy and security considerations section might want to have text about key storage too.

**Comment by aboba** [comment]
While there is an internal slot for the private key, there is no way for the JS to access it.  Since the RTCCertificate represents a handle to both the X.509 certificate and the private, both need to be provided when the RTCCertificate is stored and retrieved.  The specification doesn't say anything about the format in which the material is to be stored, but it doesn't need to - any format capable of storing both certificates and private keys would suffice (e.g. PKCS12, PEM, etc.).
