### ISSUE TITLE
need to clear [[AssociatedMediaStreams]] in removeTrack?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1756]
[addTrack](http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addtrack) adds to the [[AssociatedMediaStreams]] but [removeTrack](http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-removetrack) does not set them to an empty list.

Should it? This came up in [in firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1427162) but even ignoring getLocalStreams() legacy one doesn't want to keep a reference to the streams anymore.

cc @henbos too

**Comment by jan-ivar** [comment]
@fippo It shouldn't, because the stream association is still tied to the transceiver. E.g. If I then do
```js
await sender.replaceTrack(trackB);
sender.direction = "sendrecv";
```
Then remotely (after renegotiation) the receiver.track would again pop up in the same-id remote stream.

Confused? See https://github.com/w3c/webrtc-pc/issues/1758 which I just filed.

What I think is true however, is that we probably don't need to keep a reference to the streams themselves, just their ids. Since keeping a stream open has side-effects (local camera staying on) that seems like an improvement (remember what's being sent may come from an entirely different stream).

**Comment by alvestrand** [comment]
Why should the stream association be tied to the (local) transceiver?

The fact that if you're using replaceTrack, you're having odd effects on the stream associations is the biggest reason why using replaceTrack() together with streams is going to be a headache. The WG accepted that in the name of making replaceTrack() possible without a negotiation cycle.

If you let removeTrack() remove the track and clear the streams list, you let addTrack/removeTrack-based applications continue to behave consistently, and make it easy to shim addStream/removeStream on top of them - in fact perfectly in the case of "one track is added only as part of one stream".

removeTrack() triggers a negotiation cycle.

**Comment by jan-ivar** [comment]
> Why should the stream association be tied to the (local) transceiver?

Because you added it with `tc = addTransceiver(track, {streams})` and you haven't `tc.stop()`ed it?

**Comment by fippo** [comment]
if you call removeTrack you can call replaceTrack on that sender? Surprising but I can see how your code would work.

But how does this work then:
```
When the other peer stops sending a track in this manner, the track is removed from any remote MediaStreams that were initially revealed in the track event
```
I assume that the stream ids come back when you set the sender direction to active?

**Comment by jan-ivar** [comment]
@fippo The clue is in the end of that sentence:
```
, and if the MediaStreamTrack is not already muted, a muted event is fired at the track.
```

Importantly, it is muted, not ended. I.e. `receiver.track` still very much [alive](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediastreamtrackstate), it's just (temporarily) removed from its stream(s).

**Comment by fippo** [comment]
@jan-ivar but does replaceTrack(theTrack) re-add to the stream? I assume this is signaled in SDP by changing stream in the a=msid line to -

I suspect the answer is "no" and this is done by the subsequent change to direction and ONN?

**Comment by jan-ivar** [comment]
No, replaceTrack [by design](http://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-replacetrack)¹ never affects SDP, and never fires ONN. `sender.direction` does.

<sub>1. *"To avoid track identifiers changing on the remote receiving end when a track is replaced, the sender MUST retain the original track identifier and stream associations and use these in subsequent negotiations."*</sub>

**Comment by taylor-b** [comment]
> Why should the stream association be tied to the (local) transceiver?

Because there's a 1:1 mapping between local transceiver and remote track. That's just how the transceiver/receiver/track object model ended up, to support early media and replacing tracks.

> If you let removeTrack() remove the track and clear the streams list, you let addTrack/removeTrack-based applications continue to behave consistently

That will happen without clearing `[[AssociatedMediaStreams]]`, because the track will be removed from the stream on the *remote* side after SDP exchange. And a subsequent `addTrack` will use a new m= section, so it can be part of a different stream.

So I don't see any problem that clearing `[[AssociatedMediaStreams]]` would solve. It would just render a transceiver permanently stream-less.

**Comment by fippo** [comment]
but don't we have an (out of scope) issue defining the legacy removeStream ontop of removeTrack then? I assumed it would be "remove every sender whose track is in the stream" but that might be a bit too simplistic

**Comment by henbos** [comment]
When I redefined legacy removeStream() on top of RTP Media API for M66 (https://chromium-review.googlesource.com/c/chromium/src/+/899346), I implemented it as:
```
for (track : stream.getTracks()) {
  sender = sender in getSenders() with track == track and
           [[AssociatedMediaStreams]] == [stream]
  removeTrack(sender)
}
Stop observing tracks being added/removed to stream
```

**Comment by henbos** [comment]
I don't think we need to clear [[AssociatedMediaStreams]] slot, rather getLocalStreams() implemented on top of getSenders() should filter out any senders whose transceiver's direction is not sendonly or sendrecv. This is compatible with all the other ways of manipulating senders/transceivers and makes sense for what getLocalStreams() is supposed to do; get streams which are "actively" associated with the PC.

This is better than hunting down places where [[AssociatedMediaStreams]] might otherwise have to be updated. If you pause and resume a transceiver by changing its direction for example, it would be unexpected that the streams have been reset. If we make [[AssociatedMediaStreams]] mutable we would have to introduce a bunch of stream APIs to the sender/transceiver.

Speaking of which, it would be helpful to have it exposed as sender.streams, but readonly as to not increase the complexity of this already complicated model.

**Comment by jan-ivar** [comment]
Does that mean we can close this issue?

**Comment by fippo** [comment]
I think so. We have left spec-territory.
