### ISSUE TITLE
Inconsistency over active member in receiver's "encoding" parameters.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1806]
While working on https://github.com/w3c/webrtc-pc/issues/1493, I found this inconsistency over whether
```js
pc.getReceivers()[0].getParameters().encodings[0].active // is true/false or undefined
```
Receiver's [getParameters()](https://w3c.github.io/webrtc-pc/#dom-rtcrtpreceiver-getparameters) says:

*"Every member of the RTCRtpEncodingParameters dictionaries other than the RID fields is left undefined."*

whereas [active](https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-active) says:

*"For an RTCRtpReceiver, a value of true indicates that this encoding is being decoded. A value of false indicates this encoding is no longer being decoded."*

The latter seems on purpose.

**Comment by aboba** [comment]
@jan-ivar I think the latter text may have been left over from a time before we clarified how direction worked. Since there is no RTCRtpReceiver.setParameters, it is not possible to set encodings[].active and the specification doesn't say much if anything about when encodings[].active would toggle. So I'm not clear that active is of much use for an RTCRtpReceiver in WebRTC 1.0 (though in ORTC it does have the meaning indicated by the latter sentence).
