### ISSUE TITLE
Does direction matter for rejected m= sections?

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1812]
The direction of an m= section in a remote description affects what happens to remote tracks; for example:

> If direction is "sendonly" or "inactive", and transceiver's [[CurrentDirection]] slot is neither "sendonly" nor "inactive", process the removal of a remote track for the media description, given transceiver.

But what if the m= section is rejected? In that case, it seems odd that the direction would make a difference, since it affects nothing underneath. It doesn't matter if a rejected m= section has "a=sendrecv"; none of its streams will be sent or received regardless.

So, would it be appropriate to treat rejected m= sections as implicitly having an `inactive` direction?

**Comment by ibc** [comment]
Kill the SDP.

**Comment by murillo128** [comment]
I have not yet dig much into transceivers, but shouldn't m=section rejection have the same effect a if transceiver.stop() had been called?

**Comment by taylor-b** [comment]
Yes. The question is whether it should also have the effects that "a=inactive" would cause; namely, removing the remote track from its stream.

**Comment by jan-ivar** [comment]
See discussion in https://github.com/w3c/webrtc-pc/pull/1845.

**Comment by aboba** [comment]
@jan-ivar Should we close this issue?

**Comment by jan-ivar** [comment]
[Turns out](https://jsfiddle.net/jib1/zroe80px/) I missed that Firefox offers `a=inactive` after `transceiver.stop()`—apparently to avoid interop headaches—which somewhat wrecks my [earlier argument](https://github.com/w3c/webrtc-pc/pull/1845#issuecomment-385675103) for closing this. Re-opening.

I suggest we enshrine that behavior in the spec, and open a bug on Firefox to add the missing events (Firefox still doesn't fire the respective `mute` and `removetrack` events on the other end from it).

Chrome doesn't implement transceiver.stop() yet AFAIK. @henbos Does that sound good?

**Comment by alvestrand** [comment]
Discussion is done, and the test bug exists. Closing.
