### ISSUE TITLE
Possible to lose data with a reliable, pre-negotiated data channel?

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1879]
One might expect that a "reliable" data channel (the default behavior, where `maxRetransmits` and `maxPacketLifeTime` are left unset) is guaranteed to be, well, reliable. But in current implementations, the first messages may be lost if the application is negotiating the channels out-of-band (setting `negotiated` to `true`), and creates the receiving channel too late.

Here's a fiddle that demonstrates this (happens with Chrome and Firefox): https://jsfiddle.net/o2m8tp20/

Normally, the sequence is something like:

1. Offerer creates channel.
2. Sends offer.
3. Answerer receives offer, creates channel.
4. Sends answer.
5. SCTP handshake completes, channels become open and start sending data.

But if the SCTP handshake is already complete when one side creates a new channel (or the other side just creates its channel too late), then the channel may be "open" before the other's is even created. So when usrsctp receives a message and delivers a message to the WebRTC stack there's no data channel to deliver it to, and it's just dropped.

Is this expected behavior? Or should implementations be buffering this data until the channel is created? If it's expected behavior, the spec should clarify this somewhere.

**Comment by lgrahl** [comment]
I don't see this being well-defined at the moment. But here is what [DCEP, chap 6](https://tools.ietf.org/html/draft-ietf-rtcweb-data-protocol-09#section-6) states:

    If the DATA_CHANNEL_OPEN message doesn't satisfy the conditions
    above, [...], the receiver MUST close the corresponding Data Channel
    using the procedure described in [I-D.ietf-rtcweb-data-channel] [...]

Based on that, I would say it makes sense to close the data channel. I would prefer that over ignoring incoming messages on unassigned stream IDs. If there's agreement, this should probably be added to [rtcweb-data-channel-13, chap 6.6](https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13#section-6.6).

@tuexen Thoughts?

**Comment by tuexen** [comment]
I would expect that when a user creates a reliable data channel, data is transferred reliably. If some buffering has to be done, then it should happen... What should not happen, is that the user has no indication that something went wrong...

**Comment by lgrahl** [comment]
We could of course also buffer the data but that will add some complexity: There would have to be some timer running that discards the messages and closes the data channel once it fires. So, basically I see the following solutions:

When receiving a message on an unassigned stream ID...

1. discard it. Breaks the reliability promise.
2. run the closing procedure (reset incoming/outgoing stream). An easy fix but will not fix the problem with `createDataChannel` being useless after the connection has been established, since both would have to synchronise the opening or it would be a race.
3. buffer the messages for X seconds. If a negotiated channel has been created with the same ID, deliver the messages. Once the timeout fires, run the closing procedure. As mentioned, this will not be trivial to implement but would be the most satisfactory solution. We only have to determine *X*. :slightly_smiling_face:

**Comment by jan-ivar** [comment]
Should we maybe leave X implementation dependent, or maybe a minimum value?

**Comment by lgrahl** [comment]
Yeah, I think we should make a suggestion based on potential use cases. The only use case I can see is creating a negotiated channel on both sides once they have negotiated that via another data channel or some other arbitrary signalling channel. Therefore, I would base a safe *X* on a typical TCP send timeout.

**Comment by taylor-b** [comment]
For that use case, I don't see any reason why you wouldn't just create an in-band negotiated data channel instead. So I'd lean towards a simple solution like just running the closing procedure.

Either way, technically I think this behavior would fall under the [rtcweb-data-channel](https://datatracker.ietf.org/doc/draft-ietf-rtcweb-data-channel/) specification. So I'll raise this topic on the rtcweb mailing list.

**Comment by lgrahl** [comment]
If that variant is chosen, I think we should throw an exception in case a negotiated channel is being created after connection establishment. And I'm not sure I like that idea.
