### ISSUE TITLE
RTCPriorityType is not documented for simulcast

### ISSUE THREAD

**Issue by ibc** [w3c/webrtc-pc#1888]
When using simulcast, N encodings must be provided to `RtpSender.send()`. Each encoding may have a different `priority` field with value "very-low", "low", "medium" or "high".

As per https://w3c.github.io/webrtc-pc/#dom-rtcprioritytype:

> low
> See [RTCWEB-TRANSPORT], Section 4. Corresponds to "normal" as defined in [RTCWEB-DATA]

In https://tools.ietf.org/html/draft-ietf-rtcweb-transports-17#section-4:

> For media, a "media flow", which can be an "audio flow" or a "video flow", is what [RFC7656] calls a "media source", which results in a "source RTP stream" and one or more "redundancy RTP streams".  This specification does not describe prioritization between the RTP streams that come from a single "media source".

But it happens that simulcast is about RTP streams coming from a **single media source**.

So, to be perfectly clear, the meaning of `RTCPriorityType` is not documented at all. AFAIS people usually assigns "low" priority to the minor bitrate stream and "high" priority" to the largest bitrate stream without too much rationale behind.

**Comment by alvestrand** [comment]
The meaning (what you do if you get this value) is documented in sections 4.1 and 4.2. That's why they are subsections of section 4.

**Comment by alvestrand** [comment]
What people SHOULD be doing in the simulcast case when congestion is expected is to assign high priority to the minor bitrate stream (so that it will always be sent) and low priority to the largest stream (so that its packets will be dropped first).

**Comment by ibc** [comment]
> The meaning (what you do if you get this value) is documented in sections 4.1 and 4.2. That's why they are subsections of section 4.

Sure, but those subsections do not even mention "simulcast" use case.

> What people SHOULD be doing in the simulcast case when congestion is expected is to assign high priority to the minor bitrate stream (so that it will always be sent) and low priority to the largest stream (so that its packets will be dropped first).
The effect of wrong settings is probably mitigated by the fact that nobody does prioritization well (if at all) yet.

Thanks.

**Comment by taylor-b** [comment]
> What people SHOULD be doing in the simulcast case when congestion is expected is to assign high priority to the minor bitrate stream (so that it will always be sent) and low priority to the largest stream (so that its packets will be dropped first).

I don't think I understand the definition of `RTCPriorityType`, then. The two example implementation strategies are:

>    o  When the available bandwidth is known from the congestion control
>       algorithm, configure each codec and each data channel with a
>       target send rate that is appropriate to its share of the available
>       bandwidth.

Meaning the "minor bitrate stream" would be configured with a higher bitrate? And the other is:

>    o  When congestion control indicates that a specified number of
>       packets can be sent, send packets that are available to send using
>       a weighted round robin scheme across the connections.

This sounds like it would result in the higher bitrate layer either losing too many packets to be decodable (if the sender drops packets), or building in latency (if it doesn't).

What we actually want is for the higher bitrate layer to be turned off completely when there's too much congestion. `RTCPriorityType` doesn't accomplish this.

Maybe it was never intended for simulcast at all, and should be moved up to the `RtpParameters` level (instead of `RtpEncodingParameters`)? It's pretty odd that it explicitly says "this isn't defined for multiple streams coming from a single media source", and that's exactly how we're appearing to use it.

**Comment by ibc** [comment]
Given that the discussion is open, I don't think the documentation of this parameter is good enough.

**Comment by aboba** [comment]
@ibc Perhaps we should provide examples for how this (and other encoding attributes) can be used with simulcast.  But there are some practical questions to answer first. When simulcast is used, we see multiple video streams (originating from different SSRCs) outbound on the same IP address and port.  Marking these streams differently typically requires resetting the socket options on each packet.  I am curious whether the performance of this has been measured - it is not something that is encouraged on Windows, where it would cause multiple user mode/kernel mode transitions on each packet.  So yes, the API allows this to be done, but does it actually work??

Another area of confusion relates to degradationPreference.  Is this expected to influence the encoder behavior when sending simulcast and/or SVC?  For example, if degradationPreference is set to "maintain-resolution" will temporal layers be dropped first, then higher resolution simulcast layers?  Also, does degradationPreference affect encoding optimizations?   Overall, degradationPreference seems considerably more fuzzy to me than the Priority API. 

BTW, RtpSender does not have a send() method in WebRTC 1.0. :)

**Comment by ibc** [comment]
> Marking these streams differently typically requires resetting the socket options on each packet. 

Why? I assume that the sender can apply different sending/retransmit policies per stream without requiring QoS or DSCP (regardless what [section 4.2](https://tools.ietf.org/html/draft-ietf-rtcweb-transports-17#section-4.2) states).

> BTW, RtpSender does not have a send() method in WebRTC 1.0. :)

Opps :)

**Comment by aboba** [comment]
@ibc I was referring only to DSCP marking.  Differential RTX or FEC (e.g. only protecting the lowest resolution simulcast or SVC layer) makes sense to me.

**Comment by ibc** [comment]
Ok. Just to simplify, my initial concern is which priority to assign to each simulcast encoding. I've just talked to some other developers and no one knows the answer. Harlard explained it above but I don't think the spec describes it properly.

**Comment by alvestrand** [comment]
I agree that more explanation of this use case is better.
To @aboba's concern: The DSCP spec (which is a result of a desire to not reopen the IETF transport spec at the time the question came up) specifies how to set priority without affecting DSCP.
Agree that the "configure the codec" language lacks context - when I wrote it, I intended it to mean "within the range that configuration permits" - ie a low bandwidth, high priority stream should be almost guaranteed to never experience congestion as long as there are bits to be had.

Thought: One possibility in the "split things up" movement would be to take the entire priority extension and move it into what's currently called the DSCP spec, so that it's its own body of work. It's obviously had less implementation experience than a lot of other stuff!

**Comment by aboba** [comment]
I am marking this issue with the "Simulcast" tag to indicate that the relationship of `RTCPriorityType` to simulcast needs to be better defined.  There are no doubt other Issues in this category (not sure we fully understand what *any* of the encoding parameters do in the case of simulcast). 

One thing to understand before submitting a PR is whether implementations are prepared to modify the simulcast congestion control behavior (e.g. which simulcast layers to drop on insufficient bandwidth) based on the RTCPriorityType values.  Also, I'd note of specification might not extend to SVC very well (e.g. you can't drop the base temporal layer before extension layers). 

I have submitted a PR to make the section references (to Sections 4.1 and 4.2) more precise.

**Comment by alvestrand** [comment]
No longer relevant, so closing.
