### ISSUE TITLE
Can RTCStatsReport use a union type instead of object?

### ISSUE THREAD

**Issue by saschanaz** [w3c/webrtc-pc#1905]
Currently RTCStatsReport uses object:

http://w3c.github.io/webrtc-pc/#rtcstatsreport-object

```webidl
[Exposed=Window]
interface RTCStatsReport {
    readonly maplike<DOMString, object>;
};
```

...where the object means a finite set of subdictionaries of RTCStats defined in [WEBRTC-STATS](https://www.w3.org/TR/webrtc-stats/).

How about:

```webidl
typedef RTCTypedStats = (
  RTCCodecStats or
  RTCInboundRtpStreamStats or
  ...
);

[Exposed=Window]
interface RTCStatsReport {
    // replace object with RTCTypedStats
    readonly maplike<DOMString, RTCTypedStats>;
};

dictionary RTCStats {
    required DOMHighResTimeStamp timestamp;
    // replace enum RTCStatsType with DOMString
    required DOMString           type;
    required DOMString           id;
};
```

... so that we can remove vague `object`s from IDL?

**Comment by alvestrand** [comment]
This idea requires keeping an union type that is updated every time a new stats type gets added. That union type would have to live in the webrtc-stats document, or maintenance would be unmanageable.

But it doesn't work anyway, because all these types are dictionaries, and two dictionaries aren't distinguishable enough to be included in the same union type:

https://heycam.github.io/webidl/#dfn-distinguishable

**Comment by saschanaz** [comment]
Yeah... multiple dictionaries shouldn't be in a union. Thanks for clarification.
