### ISSUE TITLE
Move [[WEBRTC-IDENTITY]] to its own repo

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1931]
This seems more convenient

**Comment by dontcallmedom** [comment]
I've created https://github.com/w3c/webrtc-identity and populated it with the identity document and the identity related issues.

What remains to be done (ideally by someone else since I'll be away for a few days):
* [ ] close the identity related issues
* [ ] remove `identity.html` and `identity.js` from this repo
* [ ] let the identity editors know (thus pinging @martinthomson @fluffy )

**Comment by dontcallmedom** [comment]
other todos for me:
* [ ] link new repo from WebRTC WG home page
* [ ] add repo to github notifcations & digest
