### ISSUE TITLE
transceiver.direction doesn’t respond, if out-of-sync.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1940]
Assuming ONN, whenever JS changes `direction` on a transceiver, renegotiation happens and results in `currentDirection` tracking.

However, when SLD(answer) sets `currentDirection`, it leaves `direction` alone.

I think this means `direction` can get out of sync with `currentDirection`.

This seems bad the given the [direction](http://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-direction) setter algorithm:

  6. *If newDirection is equal to transceiver's [[Direction]] slot, abort these steps.*

**Comment by stefhak** [comment]
The same is true for SRD(answer). It seems that `direction` is only updated by the app - and perhaps that is the way it should be? IIUC `direction` is only used for creating offers or answers. So basically if you want to both send and receive on a transceiver you will offer that every time you re-negotiate, but ONN will only fire when `direction` is changed.

I'm afraid I don't see the problem.

**Comment by alvestrand** [comment]
I think our intention was that [[direction]] would reflect the current intention, as would be reflected in the next CreateOffer. If the SLD/SRD cycle has the other party agreeing to our proposed direction, it will set currentDirection = direction; the case where it is different is the case where the remote end reduces the functionality (sendrecv => sendonly / recvonly / inactive, for instance).
In this case, I think it is correct to set [[direction]] when setting [[currentDirection]] as part of SRD(answer).

SLD(answer) with unchanged answer should always have [[direction]] and [[currentDirection]] be the same value after SLD(answer) is applied, since the answer was generated based on [[direction]].

**Comment by jan-ivar** [comment]
But it causes ill behavior: it may prevent `transceiver.direction = newValue` from working.

**Comment by dontcallmedom** [comment]
can we move this to a WPT issue?
