### ISSUE TITLE
Superfluous union in addIceCandidate.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1954]
From https://github.com/w3c/webrtc-pc/issues/1952#issuecomment-410289502:
> An `RTCIceCandidate` instance is valid input to a function expecting `RTCIceCandidateInit`, because they have the same members.

This means we can simplify the spec. AFAICT, the union used to be needed because the argument was nullable once upon a time, but it no longer is, so we can remove it in favor of just `RTCIceCandidateInit`.

**Comment by jan-ivar** [comment]
@aboba AFAIK all the information `addIceCandidate` needs is in `RTCIceCandidateInit`, and the extra properties of `RTCIceCandidate` merely parse the `candidate` string, and already don't show up in the signaling channel, because they're explicitly [not enumerated](http://w3c.github.io/webrtc-pc/#dom-rtcicecandidate-tojson).

**Comment by aboba** [comment]
@jan-ivar That is correct, but there may be some other archeological remains to be sorted out.
Do you recall why `RTCIceCandidate` was defined as an interface instead of a dictionary (as it is in ORTC)?

I seem to recall that the union arose from the desire to enable existing implementations to continue to work while moving toward `RTCIceCandidate` as the argument to ICE-related methods.  But if `RTCIceCandidate` had been a dictionary, would this have been needed??

I would note that extension specifications such as WebRTC-ICE utilize `RTCIceCandidate` as an argument to added methods (see: https://w3c.github.io/webrtc-ice/), so I'd like to figure out whether this change has implications for other specification as well.

**Comment by jan-ivar** [comment]
@aboba See https://github.com/w3c/webrtc-pc/pull/407. In short, because of [RTCPeerConnectionIceEvent](http://w3c.github.io/webrtc-pc/#idl-def-rtcpeerconnectioniceevent). A [dictionary](https://heycam.github.io/webidl/#dfn-partial-dictionary) cannot be an attribute.

AFAICT the union was never necessary; an overlooked simplification. I don't find anything pointing to there ever having been a desire to move to interfaces as arguments, quite the opposite. Instead of:
```js
addIceCandidate(new RTCIceCandidate(msg.candidate));
```
...I recall we preferred the less cumbersome and more direct:
```js
addIceCandidate(msg.candidate);
```
I remember we did the same to `RTCSessionDescription` and its various uses in method.
