### ISSUE TITLE
Describe consistency model between *{local|remote}*Description attributes

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1965]
The spec doesn't enforce a particular consistency model between the localDescription, currentLocalDescription, pendingLocalDescription and their remote counterparts.
These descriptions can potentially change over the time of execution of Javascript, meaning that their values could be observed inconsistently by a script.

Suggestion: Specify that all the six attributes are observed from a single consistent snapshot. (In theory, we could specify that this is observed at the time of script startup, but I think that increases overhead for functions that don't observe these attributes, so I think we should leave the exact time of observation implementation-defined.)

CC @foolip

**Comment by foolip** [comment]
The way that HTML deals with many similar situations is the incantation "when the event loop last reached step 1" or "the last time the event loop reached step 1". https://html.spec.whatwg.org/multipage/media.html#dom-media-ended is an example of this.

**Comment by steveanton** [comment]
I don't think I'm understanding the issue.

Setting the session description (local or remote) happens on the operation queue (step 4.4.1.6) so each SLD/SRD should be serialized against themselves (and other things that go on the operation queue).

The (current|pending)(Local|Remote)Description slots only get changed in a task queued on the main thread once the task on the operation queue finishes.

To me it looks like just the last step is enough to ensure consistency. How can it change over the time of execution of JavaScript (unless this means something different than "within a task")?

**Comment by foolip** [comment]
It's possible that the way this is described in the spec already makes this a non-issue. The use of slots and updating those in tasks is certainly a better situation that for media elements in HTML. @alvestrand, perhaps this is at this point only a Chrome bug?

Testing stuff like this is a bit tricky, it would requiring busy-waiting and looking for changes as well as checking frequently for an inconsistent state that should be impossible to observe, but such a test will still sometimes spuriously pass due to good (bad?) luck.

**Comment by henbos** [comment]
I haven't looked at the spec yet but I don't think this is an issue in the spec considering it has an operations queue and is normally clear about when to update things and doesn't run into thread synchronization issues. The comment I made at https://bugs.chromium.org/p/chromium/issues/detail?id=851421#c3 was referring to Chrome's implementation doing things incorrectly across threads, not that the spec was inconsistent.

**Comment by henbos** [comment]
Chrome's bug can be triggered in WPT, it's just a matter of not waiting for the async operation (setLocal/RemoteDescription) to complete before reading the value of the current/pending local/remote descriptions.

**Comment by henbos** [comment]
These attributes are defined in terms of internal slots that are updated in setLocalDescription() or setRemoteDescription() along with signaling states and other things.

The only thing I'm wondering about is if there is a race between SLD/SRD and the ICE agent generating candidates, since this is supposed to queue a task that amongst other things:

> 5. If connection.[[CurrentLocalDescription]] is not null, and represents the ICE generation for which candidate was gathered, add candidate to the connection.[[CurrentLocalDescription]].sdp.

This is vague and and the modification of the description could be overwritten by SLD/SRD setting it to the offer/answer SDP. Is that intended?

@alvestrand Should we create a new bug for the above and close this, or what did you have in mind?

**Comment by alvestrand** [comment]
I note that the internal slots don't have an unified place to list their behavior the way attributes have; they're defined by scattered pieces of text.
I'm trying to add text to the "operation" section that describes this set of variables and the intended behavior.
