### ISSUE TITLE
Sort out meaning of "Fire event with OperationError exception"

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1970]
In step 2.2.5.3 of the `set an RTCSessionDescription` algorithm it is said:
`Fire an event named error with an OperationError exception at channel.`

I'm not sure what that means. Should we add the error "operation-error" to `RTCErrorDetailType` and use that?

**Comment by alvestrand** [comment]
I think it's supposed to mean "fire an event containing a DOMError with the name OperationError".
We have a "throw an OperationError exception" down in createDataChannel. But I'm not sure what firing it as an event (as opposed to throwing it as an exception or rejecting a promise with it) means.

**Comment by jan-ivar** [comment]
As to intent, @alvestrand's guess is also mine. But *RTCErrorEvent*'s `error` member is of type *RTCError*, and incompatible with *DOMException*, so that won't work.

However, the surrounding steps, the closing of the data channel, looks identical to [data-channel-failure](http://w3c.github.io/webrtc-pc/#dfn-data-channel-failure), so my guess is this is what we want here. Maybe we can reuse that algorithm even?
