### ISSUE TITLE
Use PSK key exchange in DTLS transport instead of certificates

### ISSUE THREAD

**Issue by reklatsmasters** [w3c/webrtc-pc#2007]
If i understand correctly, the way of establish secure connection is:

* generate self-signed certificate with ECDSA key
* share certificate fingerprint through exising secure channel inside SDP
* check certificates in dtls handshake process

I think certificates is complex and absolutely unneeded part of WebRTC. The `PSK` key  exchange is much easier and do the same thinks. The ideal cipher suite to use in WebRTC is [RFC8442](https://tools.ietf.org/html/rfc8442) wich provides Perfect Forward Secrecy (ECDHE_PSK) and modern cipers (AEAD).

Besides, the `PSK` key exchange makes dtls handshake faster, see [RFC4279](https://tools.ietf.org/html/rfc4279#section-2):

> The Certificate and CertificateRequest payloads are omitted from the response.<...> If no hint is provided, the ServerKeyExchange message is omitted.

**Comment by martinthomson** [comment]
Certificates are suboptimal, yes, because they are used as glorified contains for public keys.  Using PSK would  be a terrible idea for the same reason we don't use security descriptions: it makes impersonation by entities with access to signaling trivial.  

I think you really want to ask for is raw public keys (RFC 7250).  The reason we don't use those is that they aren't very widely implemented in stacks, which makes deployment tricky.  I'm not opposed to someone working out how to signal use of raw public keys in SDP, but it's a non-trivial part to deploying something like that.  Motivating the change isn't that simple because certificate overheads aren't that terrible in practice.

DTLS 1.3 should fix the handshake latency problems without the associated compatibility risk.

**Comment by alvestrand** [comment]
This issue is a protocol issue, and should therefore be discussed in the IETF.
If you want to develop an addendum to draft-ietf-rtcweb-transport and associated documents that permit the use of other handshake mechanism, please propose it in that forum.

I'm closing this issue in the W3C.
