### ISSUE TITLE
Clarify how codecs should be prioritized.

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2009]
[RFC 3264](https://www.ietf.org/rfc/rfc3264.txt) sections 5.1 and 6.1 says offer/answer contains codecs that we are willing to send/recv/sendrecv, depending on direction.
It says the answer MAY change the order of the codec list depending on priority, but that it is RECOMMENDED not to change the order if it does not have a preference, such that the original priority is preserved.

Implicit about this, I think, is that we'll pick the first codec that both offerer and answerer supports.
The offerer has a say of priority by proposing the list of codecs, and the answerer has a say of priority by being able to modify the order in the answer. The order is based on setCodecPreferences().

This is my understanding based on current spec status:
- If offerer used setCodecPreferences() but the answerer didn't, the offerer's priority will be respected.
- If the answerer used setCodecPreferences(), the answerer's priority will override any priority that the offerer may have asked for.

Is this what is intended?

**Comment by henbos** [comment]
If any codec is excluded from setCodecPreferences() on either the offerer or the answerer side this will be respected in the sense that it will definitely not be picked, whether the priority will be respected or not as described above refers to codecs that are on both the offerer's and the answerer's list.

**Comment by aboba** [comment]
@henbos Will you prepare the slides for discussion of this issue at TPAC?

**Comment by henbos** [comment]
Yes, done.

**Comment by aboba** [comment]
@henbos setCodecPreferences() is used to modify the codecs and order provided by createOffer() and createAnswer().  Since this only affects the potential result of the negotiation, O/A is required for those preferences to influence the codecs in use.  In contrast, setParameters() can be used to immediately change the sending codec within the set that the Offerer and Answerer have in common. 

By "picking the first codec" I think you mean that the Answerer will send using the first codec in its list. However, since RFC 3264 allows the Answerer to send using any codec in its list, it is legal to call setParameters() to change the sending codec without having to do another O/A negotiation.

**Comment by henbos** [comment]
setParameters() we can override any priority by explicitly sending any codec as long as it has been negotiated.

But there is language about priority of codecs based on order, and anyone not explicitly setting the codec does rely on the default, so which codec is the default has significance.

We should either be clear about which the default is or be clear that it is up to the implementation. Right now there is language about the order in the SDP being the same as that you specified and that the order is tied to priority without being clear about what that means.

**Comment by jesup** [comment]
normally this is up to the implementation - it knows things about the relative costs/performance/resolution//bandwidth constraints/etc that the application can't know, and which changes in realtime.  And the UA is allowed to switch among the common list of codecs at will on a packet-by-packet basis (though doing it that fast would be very silly).

**Comment by aboba** [comment]
@henbos Can you prepare a PR?

**Comment by henbos** [comment]
Yes will do!
