### ISSUE TITLE
Not clear how to set # of layers when answering an offer with a track

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2014]
The process for reusing an m-line is only referenced in the spec under addTrack:

http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addtrack

In particular, it's not referenced under addTransceiver, which is our only API point for saying how many layers we wish to send.

This means that I don't know what decides the number of layers available for sending on a transceiver that was created as a result of an incoming offer.

**Comment by fippo** [comment]
see also https://lists.w3.org/Archives/Public/public-webrtc/2017Apr/0040.html ?

**Comment by aboba** [comment]
@fippo @alvestrand  This seems like quite an important question to answer. In a typical conference the SFU sends the Offer because it alone knows how many participants are in the conference. The SFU will typically not have simulcast configured in its Offer m-lines (because the browser typically won't support receiving simulcast).  Yet the browser may be sending simulcast to the SFU, so it needs to be able to configure how many simulcast streams it will send in the Answer. 

In such a situation, the application will receive a track event providing the transceiver that has been created as a result applying the SFU's Offer in setRemoteDescription(). To configure that transceiver to send simulcast, the only viable mechanism is transceiver.sender.setParameters(). In such a situation, I wouldn't expect that transceiver.sender.getParameters() would return much information of interest since the sender hasn't been configured and transceiver.receiver.getParameters() provides minimal information on what was Offered (only the number of encodings to be received and the rid). 

The part that makes me uncomfortable is that while an Offer to send simulcast can be responded to by an Answer with an indication of willingness to receive, an Answer specifying simulcast sending cannot. So what happens if the browser want to send simulcast to the the SFU, but the SFU doesn't want it to do so? 

Section 5.4.1 says "This specification does not define how to configure createOffer to receive multiple RTP encodings."  I believe this statement should be expanded to apply to createAnswer as well, since there is no receiver.setParameters() method.

**Comment by alvestrand** [comment]
adding a=rid:x lines in the offer from the SFU, and reflecting the number of RIDs in the transceiver configuration presented, would make sense. This requires modifying the setRemoteDescription() step that creates transceivers, I believe - this is a minimal change, and doesn't impact API surface. But someone still needs to write a test to go along with it.

**Comment by fippo** [comment]
We currently send offers including a=simulcast from our SFU to Firefox:
```
a=rid:hi recv
a=rid:mid recv
a=rid:lo recv
a=simulcast: recv rid=hi;mid;lo
```
Works fine and there must be a way to indicate support for receiving simulcast streams (rid should be covered by the extmap line). It is somewhat ugly since we still need to then call sender.setParameters with the target bitrates and scaledown ratios we want and basically have to hardcode the rids.
This wouldn't be drastically different from adding the transceiver before setRemoteDescription with the hardcoded rids though.

**Comment by aboba** [comment]
I would feel better about writing a PR for this if there was a section in JSEP that we could cite. Unfortunately, JSEP Section 5.2.1 (Initial Offers) only talks about a=rid send lines and JSEP Section 5.3.1 (Initial Answers) doesn't mention a=rid lines at all. So this case does not appear to be covered.

**Comment by aboba** [comment]
@fippo Good to hear that it is working in Firefox.  There really is no alternative to sender.setParameters .

**Comment by aboba** [comment]
The `ontrack` event provides `e.transceiver`. `transceiver.sender.getParameters()` provides the send `rid` values as well as the # of layers.

**Comment by amithilbuch** [comment]
And you should use setParameters() (after getting them) to set parameters for all the layers (like scale_resolution_down_by ).
You should also be able to reduce the number of layers via a call to setParameters()
One reasonable way to achieve this without actually changing the number of layers is to mark a layer as inactive (paused) indefinitely.
You **should not** be able to increase the number of layers.
