### ISSUE TITLE
Redundant queuing in connection state computations. 

### ISSUE THREAD

**Issue by jonasesolsson** [w3c/webrtc-pc#2020]
Quoting the spec:

>When the ICE Agent indicates that the RTCIceTransportState for an RTCIceTransport has changed, the user agent MUST queue a task that runs the following steps:
> ...
> 8. Update the connection state of connection.

> 4.4.1.3 Update the connection state
> An RTCPeerConnection object has an aggregated connection state. Whenever the state of an RTCDtlsTransport or RTCIceTransport changes or when the [[IsClosed]] slot turns true, the user agent MUST update the connection state by queueing a task that runs the following steps:

Here it looks like we are _required_ to queue a task that queues another task. Is that intended? Should we allow the steps in 4.4.1.3 to be run synchronously?

**Comment by steveanton** [comment]
Yeah, I think running the last two steps synchronously would be the right choice here.

**Comment by alvestrand** [comment]
A quick read (never trust quick reads!) says that "update the connection state" is only invoked from the step 8 quoted, so it's always in a queued task. Perhaps we can change 4.4.1.3 to remove the "by queueing a task to" and add a remark that "This process MUST be invoked from a queued task" to guard against later mistakes?

**Comment by jan-ivar** [comment]
What we did in [media-capture](https://w3c.github.io/mediacapture-main/getusermedia.html#media-flow) when *setRemoteDescription()* needed a synchronous algorithm was this:

> Whenever the User Agent initiates such a change, it MUST queue a task, using the user interaction task source, to [set a track's muted state](https://w3c.github.io/mediacapture-main/getusermedia.html#set-track-muted) to the state desired by the user.
> 
> To **set a track's muted state** to *newState*, the User Agent MUST run the following steps:

But we should have a good reason for doing this.

The advice I've gotten from DOM folks is it's generally preferable, predictable and safer to always queue a task to fire an event. This is because [event dispatch](https://dom.spec.whatwg.org/#concept-event-dispatch), in spite of its name, is a synchronous function call directly into content JS. This means implementations (and specs) must be super careful about not making *any* assumptions about state in subsequent steps in the algorithm, since content JS may have changed state on us in all sorts of ways in the callback. This has led to crashes, even UAFs.

What we had to do to make [set description](https://w3c.github.io/webrtc-pc/#set-description) safe, was write explicit steps that copied all state needed to fire the events, and then fire them all at once as the very last step. This way all observers experience the same state as well.  

In hindsight it would have been better if *setRemoteDescription()* fired a *single* event, but for compatibility reasons that was not a choice.

Do we want to do that here?
Does that reason hold here as well?

**Comment by dontcallmedom** [comment]
@jan-ivar I had marked this as editorial in March, but I'm no longer sure that this is correct.

Do we need to do something here?

**Comment by jan-ivar** [comment]
On reviewing this again, these events are all related, in that they report on the same thing essentially.

Given this, I see no reason to fire them at once. The extra queuing seems largely an artifact of a desire to break out highly related algorithms into separate pieces in the spec document. However, these are rarely called from anywhere else, so it seems simple enough to queue these events on the same task safely instead.

**Comment by jan-ivar** [comment]
Ugh, I see no reason to ***not*** fire them at once. Will update above comment.
