### ISSUE TITLE
Add RTCRtpSender.getSynchronizationSources() to expose audioLevel

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2103]
A lot of people poll getStats() frequently to obtain audio levels, which is supposedly inefficient to the point that it can make your laptop sound like a helicopter. We already have RTCRtpReceiver.getSynchronizationSources()[i].audioLevel, should we add getSynchronizationSources() to RTCRtpSender as well? It would represent the RTP packets sent instead of the ones received, so you can read the local audio levels without setting up a loopback connection.

Related question:
- Is this audioLevel "good enough" to replace getStats()'s audio level? This is an instantaneous value, and while it can be polled frequently without any significant overhead, it may be based on something other than what people are used to.

**Comment by alvestrand** [comment]
This need should be solved by reading back audio level on a MediaStreamTrack instead. It's more general, and doesn't depend on the vagaries of the particular RTP packetization regime in force.

If we ever get to sending pre-encoded audio streams, supporting sender's audio level would require re-decoding the audio packets in order to read the level; that sounds like an architecturally wrong approach.

**Comment by henbos** [comment]
Is there a reason why you can't simply do MediaStreamTrack.getSettings().audioLevel or MediaStreamTrack.audioLevel, or MediaStreamTrack.totalAudioEnergy, etc? I remember talking about this years ago, but kept getting referred to WebAudio...

**Comment by henbos** [comment]
Closing per @alvestrand's comment
