### ISSUE TITLE
pc.close() should null out currentDirection

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2122]
[stop()](https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-stop) will *"Set transceiver's [[CurrentDirection]] slot to null."*, whereas [close()](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-close) won't. Omission.

Would be great to find a way for *close* to reuse the [stop the transceiver](https://w3c.github.io/webrtc-pc/#dfn-stop-the-rtcrtptransceiver) algorithm *stop* uses here. Unfortunately, they differ on firing the *ended* event.

**Comment by jan-ivar** [comment]
Chrome already does this, and Firefox will after [bug 1531448](https://bugzilla.mozilla.org/show_bug.cgi?id=1531448).

**Comment by henbos** [comment]
My understanding of currentDirection is that it means the "direction currently negotiated", which is why it is updated at setLocalDescription(answer) and setRemoteDescription(answer). Stopping a transceiver is something that needs to be negotiated, which has not been done at either stop() or close(). Setting "stopped" to true is the right thing to do. But touching currentDirection? I'm not sure.

Probably direction should be made inactive and become readonly. But currentDirection? I can't say that it matters much and we can do "whatever shipped implementations does", but to me it does sound like it goes against what it is meant to mean.

**Comment by henbos** [comment]
New definition of currentDirection: "It is either the direction currently successfully negotiated, or if stopped is true it is null"?

**Comment by henbos** [comment]
Or perhaps the definition was always "what it is currently _doing_" in which case this makes perfect sense.

**Comment by henbos** [comment]
Nevermind, PR approved.

**Comment by jan-ivar** [comment]
@henbos Thanks, did you resolve it, or do you still have the above questions?
