### ISSUE TITLE
Clarify or fix racy peerIdentity validation failure

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2148]
I was reviewing [some identity code](https://github.com/web-platform-tests/wpt/blob/master/webrtc-identity/RTCPeerConnection-peerIdentity.html#L75) I think is racy on failure:
```js
const offer = await pc1.createOffer();
await pc2.setRemoteDescription(offer);
const identityAssertion = await pc2.peerIdentity; // hangs here on validation failure
```
...because `pc2` in this instance has no [target peer identity](http://w3c.github.io/webrtc-pc/#target-peer-identity) before [SRD](http://w3c.github.io/webrtc-pc/#dom-peerconnection-setremotedescription):

> *"If a target peer identity is set, then the identity validation MUST be completed before the promise returned setRemoteDescription is resolved. If identity validation fails, then the promise returned by setRemoteDescription is rejected.*
> 
> *If there is no target peer identity, then setRemoteDescription does not await the completion of identity validation."*

I read these two paragraphs to mean: when there's no target peer identity, then if identity validation fails, the promise returned by setRemoteDescription is **not** rejected.

**We should probably say that explicitly in the second paragraph, and not rely on people inferring this from *"not await the completion of"*.**

This is important, because when the [peerIdentity](https://w3c.github.io/webrtc-identity/identity.html#dom-rtcpeerconnection-peeridentity) *"promise is rejected, a new unresolved value is created, unless a target peer identity has been established."*

This means that if validation fails *before* SRD completes, then `pc2.peerIdentity` will have been set to a new unresolved value by the time we `await` it, and we hang forever.

The fix is:
```js
const offer = await pc1.createOffer();
const p = pc2.peerIdentity;
await pc2.setRemoteDescription(offer);
const identityAssertion = await p;
```
This seems like a bit of a footgun, but there's precedence here with the `track` event which also fires before SRD completes. Just filing this issue so we're all on the same page that this is the behavior we intended.

I'll provide a PR with the spec clarification. The wpt test is being fixed in [bug 1534692](https://bugzilla.mozilla.org/show_bug.cgi?id=1534692).

**Comment by guest271314** [comment]
@jan-ivar What is the correct approach as defined in this and/or the identity repository to set `peerIdentity` for the purpose of `MediaStreamTrack`s not being set to `"remote  "` and "isolated", where `MediaRecorder` throws a security error? Both `PeerConnection` streams are local. Read https://www.w3.org/TR/webrtc-identity/#dom-rtcidentityassertion, https://github.com/web-platform-tests/wpt/edit/master/.well-known/idp-proxy/mock-idp.js, the first test at http://w3c-test.org/webrtc-identity/RTCPeerConnection-peerIdentity.html fails. Is that expected? Also tried `await pc.peerIdentity` though the `Promise` was pending without being settled. Have not been able to perform the complete procedure due to lack of complete examples, or even verification that the specification is implemented. The context is attempting to utilize `replaceTrack()` to concatenate `MediaStreamTracks`, audio and video, played back at `<video>` with different `src`s set and captured with `.captureStream()` into a single file with `MediaRecorder`  https://bugzilla.mozilla.org/show_bug.cgi?id=1542616
