### ISSUE TITLE
Add a security/privacy note about remote SDP

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2193]
The spec guards against malformed SDP and SDP that violates the spec, but it does not do anything to guarantee that you get the SDP that you expected.

For example, you might offer sendrecv and assume that if the remote endpoint accepts your offer, they will answer with sendrecv. An application that is not prepared for one-way media might be surprised about this.

This is more of a note to users of the APIs than to the browser implementers. Does a security/note in the "Privacy and Security Considerations" section make sense?

**Comment by lgrahl** [comment]
Absolutely. Lack of integrity and authentication of the exchanged SDP allows for man-in-the-middle attacks. IMO the weakest point of WebRTC in regards to its end-to-end encryption claim.

**Comment by fippo** [comment]
the security model of the spec is "have the developers pass large blobs of SDP which they do not understand to the API without validating input". I am not sure that a note will help.

**Comment by lgrahl** [comment]
Understanding that the content is sensitive does not require understanding the content itself. :slightly_smiling_face:

**Comment by guest271314** [comment]
@fippo 

> "have the users of this API pass large blobs of SDP which they do not understand to the API without validating input"

Even where a user might try to understand SDP from a cursory point of view, by following the links, from, for example, a very basic web search - to the primary source - some of the descriptions of  [`<character>=<value>`](https://en.wikipedia.org/wiki/Session_Description_Protocol#cite_note-1) that a user might encounter at varying sources relevant to what is actually in the `sdp` at Chromium and Firefox could still potentially be outdated, or could change due to the activities of `WebRTC` developers/specification authors.

Consider the `<value>` `goog-remb`. [webrtcHacks](https://webrtchacks.com/wp-content/themes/parament/custom-pages/sdp/68.html) describes the value as 

> _Video > Codec Parameters_
> 
> **a=rtcp-fb:100 goog-remb**
> 
> This parameter is defined in draft-alvestrand-rmcat-remb. It defines the use of an RTCP message for Receiver Estimated Maximum Bitrate. The prefix goog- means that is still something implemented only by Google and non standard. 

The "Internet-Draft" https://tools.ietf.org/html/draft-alvestrand-rmcat-remb-03 itself does not detail why `"goog-remb"` was chosen as the prefix of the extension. Note also that Firefox 69 also contains such a value in `sdp` 

Chromium  `a=rtcp-fb:102 goog-remb`
Firefox `a=rtcp-fb:120 goog-remb`

which appears to indicate that *oogle products are not _now_ the exclusive implementers of that particular extension, or at least Mozilla is now using the value `"goog-remb"`, even if the actual implementation is dissimilar from that of *oogle.

**Comment by guest271314** [comment]
There is zero realistic expectation of "privacy" or "security" on the web. 

Any assertion of "security" or "privacy" within the scope of using the web in general - or any browser or browser API - particularly a browser API which requires any network, networking or signaling - should be carefully examined.

**Comment by guest271314** [comment]
[What does 'sdparta' stand for in a Firefox webRTC session description?](https://stackoverflow.com/q/52581525)
