### ISSUE TITLE
Order of multiple RTCDataChannel.send calls in case of blobs

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2215]
https://w3c.github.io/webrtc-pc/#datachannel-send defines how a blob is to be sent.
It is not clear though how blob data is retrieved.

Reading the spec, it seems that blob data retrieval is expected to happen synchronously.
This guarantees the sending order of the messages.
Sending (blob1, arrayBuffer1, blob2) would lead to three messages in the same order (blob1, arrayBuffer, blob2) on the receiving side for ordered channels.

Browsers usually do retrieve blob data asynchronously. If done so, the order of the messages is not guaranteed.
Taking the previous example, the order might actually be (arrayBuffer, blob1, blob2) or (arrayBuffer, blob2, blob1). This might be surprising to web authors.

My understanding of the intent of the spec is to guarantee order of sending.
Implementation-wise, this makes it somehow harder to implement since a queue of messages might be needed.
Clarification might be good in any case.

**Comment by youennf** [comment]
I did some testing.
Safari WebSocket implementation preserves the order of sending.
Firefox DataChannel implementation does not seem to preserve the order (https://jsfiddle.net/Lgmp2shu/).

**Comment by lgrahl** [comment]
I don't think we need to say anything about order since an ordered channel should always reflect order to the API. But a clarification note is never wrong.

You will always need a send queue with the high level API we have. Firefox has one, libwebrtc has one. It's just a matter of ensuring the order. The current behaviour should be fixed by Mozilla. /cc @nils-ohlmeier

**Comment by alvestrand** [comment]
Adding a note (making sure it's obvious that we intend ordered in -> ordered out) seems like the only reasonable spec change here.

**Comment by jan-ivar** [comment]
(A bit late, sorry) I'd prefer stronger language than a note, but I welcome the note.

> I don't think we need to say anything about order since an ordered channel should always reflect order to the API.

@lgrahl That's the desired outcome, but these are the instructions on how to make that happen on the sending side. As such, I think they fall short by treating Blobs—borne out of Files with asynchronous accessors—as having synchronously available data.

As you and @youennf point out, we want this solved in a way that doesn't block main thread, which requires either an additional level of queuing of *all* send data, or some placeholder in any existing queue.

**Comment by guest271314** [comment]
Re the test at https://github.com/web-platform-tests/wpt/pull/18770 when _**both**_ `data1` and `data2` are `Blob`s order _is_ preserved. The maximum `timeStramp` difference between `timeStamp` properties of `event` within `"message"` handler is `2`, e.g.

```
Blob { size: 4, type: "" } 334
Blob { size: 8, type: "" } 336
```

plnkr https://plnkr.co/edit/7oYM0i?p=preview

**Comment by jan-ivar** [comment]
Yeah the ill-sequencing in Firefox appears to only happen when sending blobs (which require asynchronous reads) ahead of non-blobs (which are synchronous).

**Comment by guest271314** [comment]
To preserve order at Firefox `async/await` and `arrayBuffer()` of `Blob` can also be used 

```
async function sendData()
{
  log("Sending data of size 4");
  channel1.send(await new Blob(['blob']));

  log("Sending data of size 8");
  channel1.send(new ArrayBuffer(8));
}
```
https://jsfiddle.net/jy4r3aqc/

See this [answer](https://stackoverflow.com/a/56419176) at [Where is Blob binary data stored?](https://stackoverflow.com/q/38239361)

> Blobs represent a bunch of data that could live anywhere. The [File API specification](https://www.w3.org/TR/FileAPI/) intentionally does not offer any synchronous way of reading a Blob's contents.

Given there is an expectation of order relevant to WebRTC specification the capability to set the input/output order of `MediaStreamTrack`s in a `MediaStream` (potentially recorded by `MediaRecorder` and output as a media file) should also be specified. 

Why should not order be considered important for all `MediaStream`s and data channels where the underlying source of the implemenation is WebRTC specification?

If order is important for data channel order must also be important for `MediaStreamTrack`s added to a `MediaStream`. 

At least in this case using an a single constructor or `async/await` and a single method of `Blob` can be applied to achieve the expected result rather than parsing files which have arbitrary track order set not inconsistently with the specification https://github.com/pthatcherg/web-codecs/issues/11#issuecomment-527698222.

**Comment by youennf** [comment]
Fixed by https://github.com/w3c/webrtc-pc/pull/2286 and https://github.com/web-platform-tests/wpt/pull/18770
