### ISSUE TITLE
RTCPeerConnectionIceErrorEvent: hostCandidate clarification

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#2230]
Currently, the explanatory test for hostCandidate states:

"The hostCandidate attribute is the local IP address and port used to communicate with the STUN or TURN server.

On a multihomed system, multiple interfaces may be used to contact the server, and this attribute allows the application to figure out on which one the failure occurred.

If use of multiple interfaces has been prohibited for privacy reasons, this attribute will be set to 0.0.0.0:0 or [::]:0, as appropriate."

Is an mDNS name ever placed in the hostCandidate field?

**Comment by youennf** [comment]
There does not seem to be any privacy issue since only mode 1 is allowing multiple interfaces and host candidates should already have exposed the IP address.
I would tend though to make it consistent with other parts of the spec and state that this field must remain null as long as the corresponding address is not already exposed to the web page as a host candidate.

This could for instance leak information in a weird case where only STUN/TURN is allowed but on multiple interfaces.

It seems that Chrome might be implementing this, @alvestrand, @tQsW?
Would it be possible to consider switching to a "DOMString? hostCandidate"?
Also, is it too late to have the port as another member field for consistency with other places, hence hostAddress, hostPort?

**Comment by dontcallmedom** [comment]
> [RESOLUTION](https://www.w3.org/2019/09/18-webrtc-minutes.html#item06):  empty string for null value, split port separately
> (make port nullable, find proper name for host attribute)

**Comment by jan-ivar** [comment]
@youennf to provide PR

**Comment by dontcallmedom** [comment]
I believe this was addressed by #2322 so closing
