### ISSUE TITLE
Rollback of pranswer is hard and unnecessary

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2235]
Rolling back back from `"have-remote-pranswer"`/`"have-local-pranswer"` can be as hard as rolling back from `"stable"`.

When an answer or pranswer comes in, stuff is set in motion in the transport & media stacks. To roll that back would require we:

 1. Undo "start transmitting RTP media" and/or "stop transmitting all RTP media" in [JSEP](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-26#section-5.11).
 2. Undo "prepare to initiate a SCTP association" and the [creation](http://w3c.github.io/webrtc-pc/#dfn-create-an-rtcsctptransport) of the `RTCSctpTransport`.
 3. Undo "discard any ICE components for the m= sections that will be bundled ... and begin muxing"
 4. Roll back any ICE restart, which [JSEP](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-26#section-5.10) finalized in pranswer. There's no way to rescind new `candidate` events that may have fired and been sent over the signaling channel to replace the current candidates.

It also hardly seems necessary. With [perfect negotiation](https://blog.mozilla.org/webrtc/perfect-negotiation-in-webrtc/) where both sides are browsers with state machines, glare is detected in earlier states.

Should one end up in this state, an [easier way back](https://jsfiddle.net/jib1/7ejav9y3/) to `"stable"` seems to be:
```js
await pc.setLocalDescription({type: "answer", pc.localDescription.sdp});
```
```js
await pc.setRemoteDescription({type: "answer", pc.remoteDescription.sdp});
```
I propose we drop rollback of pranswer and throw `InvalidStateError` instead.

**Comment by aboba** [comment]
I agree with your sentiments, but I might go even further. One could argue that with perfect negotiation glare would be detected in earlier states so that rollback of an answer is also unnecessary, and complex for the same reasons (e.g. not easy to rollback creation of IceTransport/DtlsTransport/SctpTransport objects).

**Comment by henbos** [comment]
Rollback when you are in the stable state (which you are if you apply an answer) is already rejected. Rejecting if you have "pranswer" sounds like a good idea to me, why would you rollback if you have reached the point of getting an answer?

That said, I might be missing something. Like, why do we need "pranswer" at all? Can someone remind me?

**Comment by jan-ivar** [comment]
Right, there's no rollback of an answer (just pranswer). No browser has implemented both rollback and pranswer, so removing this obstacle should help tremendously with finishing 1.0. 

As to why we need "pranswer", different thread please! 😉

**Comment by aboba** [comment]
@jan-ivar Eliminating rollback of a pranswer would eliminate a major obstacle to complete implementation of rollback and finishing 1.0 so it's a great idea. 

@henbos We have pranswer because in SIP an offer may receive a sequence of answers, which inform the client of the origins of successive early dialogs that it should listen to. Aside from the state, applying a pranswer has many of the effects of applying an answer in terms of object creation, ICE candidates, media in progress, etc. So as Jan-Ivar says, it's hard to do, and also somewhat removed from the core rollback use case, which is glare.

**Comment by henbos** [comment]
;D
