### ISSUE TITLE
Nulling mid when m-line is recycled is surprising.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2238]
Right now [mid](https://w3c.github.io/webrtc-pc/#dom-rtptransceiver-mid) says *"After rollbacks, the value may change from a non-null value to null."*—for good reason: if we kept a `mid` from a remote offer, we'd risk sharing that mid with the transceiver the remote offer ultimately associates with (not unique).

But there's another place it's set to `null` in [JSEP](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-24#section-5.10): *"If the m= section is being recycled (see Section 5.2.2), dissociate the currently associated RtpTransceiver by setting its mid property to null"*

Disassociating here may be important to JSEP's logic, but `null`ing the JS observable `transceiver.mid`  after `transceiver` has been stopped and removed from `pc.getTransceivers()` seems surprising and pointless (the mid can't be reused anyway).

In general, removing ids on users seems a bit like neener-neener. Let's not.

We can't touch JSEP, but I think we can work around it with an internal slot we don't touch past stopped.

cc @docfaraday

**Comment by alvestrand** [comment]
My intuition says that clearing the mid property was designed to maintain the property that "all transceivers have a mid that is either unique or null".

In particular, the offer/answer exchange:

-> offer: m=video port=5 / a=mid=a

creates a transceiver with mid=a

<- answer: m=video port=0

disassociates the transceiver from the m-line.
If a new offer comes in:

<- offer: m=video port=97 / a=mid=a

will create a new transceiver with mid=a

If we don't clear, we now have two transceivers with mid=a, one of them stopped.

My point of confusion may be the statement "the mid can't be reused anyway", which I can't remember offhand that we have an explicit agreement to (and since mid can come in from non-webrtc endpoints, that agreement needs to be in the sdp spec, not in webrtc spec).

**Comment by jan-ivar** [comment]
@alvestrand said he like the invariant that `mid` tracked association. I'm going to abandon this then, unless there's interest. cc @docfaraday
