### ISSUE TITLE
Racy setParameters()/getParameters() behavior

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2315]
### Problem A
The following may race with a remote simulcast offer:
```js
const params = pc.getParameters();
await wait(0);
await pc.setParameters(params); // Intermittent InvalidStateError
```
...because SRD clears [[[LastReturnedParameters]]](https://w3c.github.io/webrtc-pc/#dfn-lastreturnedparameters) if it gets an initial simulcast offer.

### Problem B
A related issue: *getParameters()* is not a true/idempotent getter, because it modifies state, which may cause surprising action at a distance:
```js
function foo(pc) {
  if (bar()) {
    console.log(JSON.stringify(pc.getParameters());
  }
}

const params = pc.getParameters();
foo();
await pc.setParameters(params); // InvalidStateError if bar() == true
```

### Proposed solutions

 1. Queue a task in *getParameters* to clear [[LastReturnedParameters]].
 2. Only increment [transactionId](https://w3c.github.io/webrtc-pc/#dom-rtcrtpsendparameters-transactionid) when [[LastReturnedParameters]] is `null`.

This makes **B** always work, and **A** always fail with `InvalidStateError` (not  intermittently).

**Comment by alvestrand** [comment]
This proposal will destroy the other use of [[LastReturnedParameters]] - checking that read-only parameters are unchanged.

Relevant text: "Any parameter in parameters is marked as a Read-only parameter (such as RID) and has a value that is different from the corresponding parameter value in sender.[[LastReturnedParameters]]. Note that this also applies to transactionId."

"Problem A" is exactly a case we want to prevent - since the changes to state done by SRD will make the parameters we returned in the first getParameters call inconsistent, and behavior if we set the parameters based on them is rather unpredictable.

**Comment by alvestrand** [comment]
If problem B's "foo" also calls setParameters(), we also exactly want this to fail.
So I think the cure is worse than the disease, but I'm willing to be convinced otherwise.

**Comment by alvestrand** [comment]
Queueing the clearing of LastReturnedParameters will have the effect of only allowing setParameters within the same execution unit or execution units that were already queued prior to calling getParameters, right?

We invented transactionId because this was felt to be too restrictive, I think. We could change that.

transactionId still matters because the sequence

a = getParameters()
await something
b = getParameters()
setParameters(a)

needs to fail.

**Comment by jan-ivar** [comment]
> This proposal will destroy the other use of [[LastReturnedParameters]] - checking that read-only parameters are unchanged.

That guarantee is still there. The only difference is [setParameters](https://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-setparameters) will fail more often, not be more permissive.

> "Problem A" is exactly a case we want to prevent - ... and behavior if we set the parameters based on them is rather unpredictable.

Exactly, which is why this proposal makes it _"always fail with `InvalidStateError` (not  intermittently)."_

**Comment by jan-ivar** [comment]
> Queueing the clearing of LastReturnedParameters will have the effect of only allowing setParameters within the same execution unit or execution units that were already queued prior to calling getParameters, right?

Right.

> We invented transactionId because this was felt to be too restrictive, I think. We could change that.

Expecting retrieved parameters to remain valid over async periods of time leads to intermittent problems. Any use case that needs this permissiveness, would be inherently racy, so I hope it doesn't exist. ;)

> transactionId still matters because the sequence
>
> a = getParameters()
> await something
> b = getParameters()
> setParameters(a)
> 
> needs to fail.

It will. We're not removing `transactionId`. See [slides](https://docs.google.com/presentation/d/1QEdMf6Ixg1NNvHoZUvO29njrSKn9pdF1WqcrFWI4uX8/edit?ts=5dbaf0b6#slide=id.g6b7f95ec98_5_33).

**Comment by jan-ivar** [comment]
I should clarify ambiguity in that last one:

> transactionId still matters because the sequence
>
> a = getParameters()
> await something
> b = getParameters()
> setParameters(a)
> 
> needs to fail.

It depends on what "`something`" is:
1. If it's `await 0` or e.g. `await Promise.resolve()`, then only a microtask is queued, and in that case it MUST NOT fail, because `a` and `b` are identical (no difference is possible since all modifiers (like *setParameters* and SRD) queue a task.
2. If it's `await pendingPromise` where `pendingPromise` is not resolved (and will not become resolved on this run or microtask run), then a task is queued, which means it will *always* fail (in fact `b` would have failed as well).

**Comment by henbos** [comment]
Nag ping ;)
