### ISSUE TITLE
Find a home for 1.1 features, extensions and features at risk (was: Move features at risk to an extension spec)

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2323]
I've [created a repository](https://github.com/henbos/webrtc-extensions) for [WebRTC Extensions](https://henbos.github.io/webrtc-extensions/). Currently it's on my github and it's a bit "Hello World"-like.

I just merged [webrtc-timing](https://henbos.github.io/webrtc-timing/) into it and me and @eladalon1983 are working on moving [adaptivePtime](https://github.com/w3c/webrtc-pc/pull/2309) there.

[Comment](https://github.com/w3c/webrtc-pc/pull/2309#issuecomment-538463368) by @jan-ivar :

> Since `ptime` is already a feature at risk, having both in the same extension spec would make sense.

Perhaps we want to move "ptime" to webrtc-extensions too?

Should we migrate features at risk to that spec?
Or should the spec not be listed on my personal github? If this remains a spec not officially recognized by any working group, perhaps @foolip can help me with incubation ([WICG](https://www.w3.org/community/wicg/)).

Trying to figure out what formalities I should go through

**Comment by foolip** [comment]
For moving things into the WICG, I'd poke one or more of the chairs listed at https://www.w3.org/community/wicg/participants.

**Comment by aboba** [comment]
@henbos My suggestion would be to create a "landing pad" extension document so that "features at risk" removed from WebRTC-PC can have some place to reside. This extension document could live in the WebRTC-PC repo which will make it easier to review removal PRs for features such as oauth and `ptime` that are already in the WebRTC-PC spec, but haven't been implemented.  Since the "features at risk" already have WG consensus, they don't need to be go back to the WICG.

I would suggest a separate document for features that aren't currently in WebRTC-PC, so that we aren't mixing features at different levels of maturity within the same document.

**Comment by henbos** [comment]
OK, so new features can go to "webrtc-extensions" (whether or not we move the repo at some point) and features at risk can go to a separate document on this repo.

**Comment by alvestrand** [comment]
Leave it in the private repo for now, pending Dom's advice. The tooling in W3C has had trouble in the past with multiple specs in a single repo. Once we have agreement (if we get it) that the WG wants to adopt the "extension" spec as a WG document (informative note?), we can move it to the W3C space. Or to the WICG space, if that's what we decide.

**Comment by henbos** [comment]
Ping @dontcallmedom for advice :)

**Comment by dontcallmedom** [comment]
I think there are 2 cases to distinguish:
* features that can reasonably easily be separated out into a different spec - for those, we should create one repo per spec and move the relevant spec section there
* features for which creating a separate spec would be impractical (either because they're deeply intertwined in the rest of the spec, or because they're a small addition that doesn't really make sense on its own); for these, I'm thinking of creating a convention whereby they can be put into our editors draft, but would only appear when picking a "webrtc 1.1" view of the spec via the ReSpec pill (the same way test annotations can be toggled on and off at the moment).

How does that sound?

**Comment by dontcallmedom** [comment]
(for sake of clarity, if that approach sounds good, I can provide the script and the markup convention that would make this work)

**Comment by henbos** [comment]
> - features that can reasonably easily be separated out into a different spec - for those, we should create one repo per spec and move the relevant spec section there

I think this makes sense for a substantial chunk, like a new interface, or several related methods. Like we did with identity, ice transport extensions, etc.

> - features for which creating a separate spec would be impractical (either because they're deeply intertwined in the rest of the spec, or because they're a small addition that doesn't really make sense on its own); for these, I'm thinking of creating a convention whereby they can be put into our editors draft, but would only appear when picking a "webrtc 1.1" view of the spec via the ReSpec pill (the same way test annotations can be toggled on and off at the moment).

This was what I had in mind, things like small mostly standalone additions to existing interfaces. the kind of stuff where you don't want to assemble a new working group, but priorities and commitments are uncertain because they're "1.1" type of things. If it was possible to do a ReSpec annotation to show or hide these features that would be great.

**Comment by henbos** [comment]
I think what @aboba said is important; there may be a distinction between more mature features that have not been implemented but have consensus, and less mature features that there is interest from at least one implementer to do, but commitment and priority is unclear from other implementers.

On the latter with my Chrome hat on, I want to unblock our engineers from shipping features that is of immediate interest to Chrome, but I do not want this to happen wild west style - we need a place of discussion and attempt at standardizing features that are still on their way to maturing, and minimize divergence and interop risks on our path to get there.

**Comment by yoavweiss** [comment]
The WICG will be happy to be a home for WebRTC related incubation work, assuming [there's enough support for that work](https://github.com/wicg/admin#contributing-new-proposals).

/cc @marcoscaceres @cwilso @travisleithead

**Comment by henbos** [comment]
In the [November 2019 Virtual Interim](https://www.youtube.com/watch?v=LxGiXdlOEr0) the WebRTC Working Group decided to take on the extension spec (#2378), so no incubation needed hopefully. Closing this issue :)
