### ISSUE TITLE
"Rollback" is under-specified

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2324]
How to correctly update transceivers is fairly well specified. But SDP changes a lot of things. What happens to transport, bundling, codec, stream association, etc changes? The spec does little to aid implementers, sentences like "cancel proposed changes" is really rather high level.

Quotes from a [code review](https://webrtc-review.googlesource.com/c/src/+/153525/7/pc/peer_connection.cc#7811):

> **Henrik Boström**
> There are various states that I wonder if they get properly rolled back or not.
> 
> Like, what happens if the transport's port changes?
> What happens if the set of negotiated codecs change?
> 
> +Steve, do you know how various m= section attributes get trickled down and could potentially need to be rolled back?
> +Harald for spec guidance. "Processing a Rollback" (https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-25#section-5.7) is very high level, stuff like "cancel proposed changes" or "Any resources or candidates that were allocated by the abandoned local description are discarded".
> There's also a part of webrtc-pc (https://w3c.github.io/webrtc-pc/#set-the-rtcsessiondescription) that says "Restore the value of connection.[[SctpTransport]] to its value at the last stable signaling state."
> 
> How deep does/should the rabbit hole go? A rollback affects many things and SDP is complicated.
> 
> **Steve Anton**
> I think it might be worth addressing those in follow-up CLs as this is already a decent-sized change.
> 
> In practice I'm not really sure how common it is to need to roll back changes to m= sections rather than newly-added m= sections.
> 
> A side note, what is supposed to happen if a m= section that was rejected is rolled back?
> 
> **Eldar Rello**
> Right, spec could be much more detailed and I must say it didn't help to write the implementation at all. Most of the understanding on how it should work has come from side discussions.

Unless this becomes more well-defined, it's hard to for implementers and code reviewers, and worse yet, it's hard to ensure interoperability if there is large room for interpretation with regards to how to implement "rollback".

How did Firefox implement it? @jan-ivar

**Comment by henbos** [comment]
We still have [ongoing spec discussions](https://github.com/w3c/webrtc-pc/pull/2298#discussion_r329533685) about how to apply a description to get back to the stable state.

Looking at implementing this, I wonder if we should "apply a description" to get back to stable, or if the right thing to do is to save a snapshot of all the transceivers and transports and to revert back to anything that wasn't subsequently modified locally (like addTrack after remote SDP creates a transceiver).

Also, how to rollback an ICE restart? How to revert stopping a transceiver?

**Comment by henbos** [comment]
We all agree that the following sender should not be rolled back:
```
pc.setRemoteDescription(offer);
sender = pc.addTrack(track);  // sender from the transceiver created by the offer
pc.setRemoteDescription(rollback);
```

But how about if we null the track?
```
pc.setRemoteDescription(offer);
sender = pc.addTrack(track);  // sender from the transceiver created by the offer
sender.replaceTrack(null);
pc.setRemoteDescription(rollback);
```
Probably we don't want to roll it back still?

How about this one?
```
pc.setRemoteDescription(offer);
pc.getTransceivers()[0].sender.replaceTrack(track);
pc.setRemoteDescription(rollback);
```
It's not an "addTrack-transceiver", but we're trying to use it.

What about this one?
```
pc.setRemoteDescription(offer);
pc.getTransceivers()[0].direction = 'sendrecv';
pc.setRemoteDescription(rollback);
```

**Comment by jan-ivar** [comment]
A lot of questions here. I'll try to answer them all below. But in general, rollback existed in the spec long before the transport APIs came about. Some of the questions here appear to be about ***when changes to exposed transport properties become observable***. I'd push back and ask those same questions wrt regular non-rollback negotiation methods, and look for answers there. If transports are under-specified, let's hope there's time to address that problem.

> How deep does/should the rabbit hole go? A rollback affects many things and SDP is complicated.

JSEP's *"cancel proposed changes"* may be high-level, but it's also unequivocal: if something was set using SDP, undo it. Fumigate all the rabbits (with a few exceptions¹)

Conversely, rollback is limited to *negotiated* changes. Things set outside JSEP is outside its purview.

> What happens to transport, bundling, codec, stream association, etc changes? 

I assume you're asking about effects on their (recently) exposed JS APIs from negotiation?

JSEP is done, and appears to follow a remote configuration principle of no dead-ends (except for `stopped` which cannot be rolled back). I.e. there's no change from SDP (except `stopped`) that cannot be undone by more SDP. Rollback thus shouldn't need more clarification in JSEP: just set everything back (except `stopped`, and run-ins with local JS changes) as if new SDP had told us to.

I've tried to capitalize on that principle in https://github.com/w3c/webrtc-pc/pull/2298 by re-running more of the [setting an RTCSessionDescription](https://pr-preview.s3.amazonaws.com/jan-ivar/webrtc-pc/pull/2298.html#set-description) algorithm to induce the right outcome from rollback wrt JS.

I also draw support from Firefox which internally uses rollback in-between multiple calls to SRD (the hoops in our [state diagram](http://w3c.github.io/webrtc-pc/images/peerstates.svg)), and the fact that the events fired then hold up in wpt.

> stream association

Covered by https://github.com/w3c/webrtc-pc/pull/2298. 

> Like, what happens if the transport's port changes?

What happens when the transport's port changes from non-rollback negotiation methods? How is this different?

> What happens if the set of negotiated codecs change?

When exactly are negotiated codecs changed by non-rollback negotiation methods? This seems under-specified. See https://github.com/w3c/webrtc-pc/issues/2313. How does Chrome work here? Hopefully changes don't "trickle down" before `"stable"` is reached?

> how to rollback an ICE restart?

`restartIce()` [survices rollback](https://github.com/web-platform-tests/wpt/blob/master/webrtc/RTCPeerConnection-restartIce.https.html#L344), `createOffer({iceRestart: true})` does not.

> How to revert stopping a transceiver?

You can rollback offers and answers, just not their stopping effect on transceivers. E.g. once SRD(offer) calls [stop the RTCRtpTransceiver](http://w3c.github.io/webrtc-pc/#dfn-stop-the-rtcrtptransceiver), that transceiver is irrevocably `stopped`.

> We all agree that the following sender should not be rolled back:
> ```
> pc.setRemoteDescription(offer);
> sender = pc.addTrack(track);  // sender from the transceiver created by the offer
> pc.setRemoteDescription(rollback);
> ```

When you say "rolled back" here I think you mean "deleted"? A provision was added to avoid surprises with the `addTrack` abstraction to not pull the rug out from under unsuspecting users of it. As your code comment illustrates, the abstraction obscures which transceiver they're working with. The rollback still completes, we just leave the JS object the user touched.

> But how about if we null the track?

Seems irrelevant.

> How about this one?
> ```
> pc.setRemoteDescription(offer);
> pc.getTransceivers()[0].sender.replaceTrack(track);
> pc.setRemoteDescription(rollback);
> ```
> It's not an "addTrack-transceiver", but we're trying to use it.

Seems well-defined. There's no confusing abstraction here of which transceiver is being worked on. JS asked to roll it back. It's gone. 

> What about this one?
> ```
> pc.setRemoteDescription(offer);
> pc.getTransceivers()[0].direction = 'sendrecv';
> pc.setRemoteDescription(rollback);
> ```

Same answer. Gone.

Hope that helps, and let me know if I got something wrong.

I think the next steps are to get https://github.com/w3c/webrtc-pc/pull/2298 merged and then work out when transport object properties updated in response to negotiation methods. Resolving https://github.com/w3c/webrtc-pc/issues/2313 seems a good place to start. We opened that issue because we're looking at implementing some transport objects. Even though we're approaching this from different ends (Firefox has rollback, not transports), we'll hopefully end up in the place in the end. 😉

---
<sub>1.) When touched by both JSEP and JS, JSEP seems to lean toward leaving things alone only to support the `addTrack` abstraction.</sub>

**Comment by aboba** [comment]
@jan-ivar 

"Some of the questions here appear to be about ***when changes to exposed transport properties become observable***. I'd push back and ask those same questions wrt regular non-rollback negotiation methods, and look for answers there. If transports are under-specified, let's hope there's time to address that problem."

[BA] This makes sense to me.  Since we've worked through a number of issues relating to exposed transport properties, we should be able to figure out the implications for rollback.  For example, Section 4.4.1.6 Step 8 "setting a local description" (sub-bullets 1.1.4 and 1.1.5) talks about setting the `transport` and `rtcpTransport` attributes representing `RTCDtlsTransport` objects, each with their underlying `RTCIceTransport`.

**Comment by aboba** [comment]
@jan-ivar @henbos Is this issue worthy of further discussion at the November interim?

**Comment by henbos** [comment]
Let's keep the Virtual Interim label for now, to give me a deadline. Then whether what I come up for is best addressed at the Virtual Interim or offline, we'll see

**Comment by henbos** [comment]
Time has passed since this issue was filed, and after having reviewed the webrtc.org implementation I think I have a better idea about what needs or doesn't need rolling back. Transports on offer will need to be rolled back ([slide](https://docs.google.com/presentation/d/1QEdMf6Ixg1NNvHoZUvO29njrSKn9pdF1WqcrFWI4uX8/edit#slide=id.g6b7f95ec98_0_6)), for example. As well as mid, and created-and-not-blessed-by-addTrack transceivers. direction/currentDirection is a non-issue, because direction is the control surface (not affected by O/A) and currentDirection is only set in answers, i.e. never needs to be rolled back. For bundling, there are multiple transports on offers, it's not a case of re-configuring them I don't think.

So ignoring editorial issue #2332, I'm happy with "rollback" . There are only a couple of question marks in my head, that I think require clarification by the spec:

1. What is the effect of ICE restart? Does this need to be rolled back? What happens with generated candidates, will they get rejected by addIceCandidate? Is this something the app needs to be prepared for? Should we add a "note"?

2. What happens if you swap out codecs? Early media-reasoning would suggest that codecs are applied at SLD(offer) rather than SRD(answer). This implies that existing packets on the wire with an old codec would get dropped while have-local-offer. If offers were proposed to be changed and we roll back, then what we need to do on rollback is the revert codec settings.
This assumes we don't do anything special for smooth transition when changing codecs.

**Comment by henbos** [comment]
Follow-up issues for 1) and 2) [above](https://github.com/w3c/webrtc-pc/issues/2324#issuecomment-558127202) filed, continuing the discussion at #2367 and #2368.
