### ISSUE TITLE
Section 4.4.1.6: Set the RTCSessionDescription (Object visibility)

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#2338]
Section 4.4.1.6 specifies when the DtlsTransport and IceTransport objects become visible to JS. A portion of the specified behavior does not appear to be implemented in any browser.  The behavior has implications for re-negotiation and rollback, so it is important that we understand it.

In Bullet 9, sub-bullet 1, it is stated: 

"9. If description is not null, then run the following steps:

1. If remote is false, then run the following steps for each media description in description:
1. If the media description is not yet associated with an RTCRtpTransceiver object then run the following steps:

...

If the media description is indicated as using an existing media transport according to [BUNDLE], let transport and rtcpTransport be the RTCDtlsTransport objects representing the RTP and RTCP components of that transport, respectively.

Otherwise, let transport and rtcpTransport be newly created RTCDtlsTransport objects, each with a new underlying RTCIceTransport. If RTCP multiplexing is negotiated according to [RFC5761], or if connection's RTCRtcpMuxPolicy is require, do not create any RTCP-specific transport objects, and instead let rtcpTransport be null.

Set transceiver.[[Sender]].[[SenderTransport]] to transport.
Set transceiver.[[Sender]].[[SenderRtcpTransport]] to rtcpTransport.
Set transceiver.[[Receiver]].[[ReceiverTransport]] to transport.
Set transceiver.[[Receiver]].[[ReceiverRtcpTransport]] to rtcpTransport."

[BA] If I read this correctly, after calling addTrack() and then setLocalDescription(await createOffer()), examining the resulting transceiver object should show transceiver.sender.transport, transceiver.sender.transport.iceTransport, transceiver.receiver.transport and transceiver.receiver.transport,iceTransport being non-null.  This is not observed. 

On the other hand, the behavior specified later in the section **_is_** observed. 

"2. Otherwise, (if remote is true) run the following steps for each media description in description:

...

15. If description is of type "answer" or "pranswer", then run the following steps:

Set transceiver.[[Sender]].[[SendCodecs]] to the codecs that description negotiates for sending, and which the user agent is currently capable of sending.

Set transceiver.[[Receiver]].[[ReceiveCodecs]] to the codecs that description negotiates for receiving, and which the user agent is currently prepared to receive.

Set transceiver.[[CurrentDirection]] and transceiver.[[Direction]]s to direction.

Let transport and rtcpTransport be the RTCDtlsTransport objects representing the RTP and RTCP components of the media transport used by transceiver's associated media description, according to [BUNDLE].

Set transceiver.[[Sender]].[[SenderTransport]] to transport.
Set transceiver.[[Sender]].[[SenderRtcpTransport]] to rtcpTransport.
Set transceiver.[[Receiver]].[[ReceiverTransport]] to transport.
Set transceiver.[[Receiver]].[[ReceiverRtcpTransport]] to rtcpTransport."

**Comment by henbos** [comment]
According to spec, the transport objects are created even at SLD(offer). If I understand correctly, in the case of bundling, you'd at least conceptually have transport objects for each m= section until you receive SRD(answer) to find out that bundling was indeed accepted, in which case you discard all but one transport to be used for all senders and receivers.

I don't know about the various webrtc-layer transport objects how offer/answer of transports is implemented, but Chrome [only exposes transports at SRD(answer)](https://codepen.io/henbos/pen/NWWjgXw?editors=1010), so I would think that transports are not fully created until answer?

Does it make sense to update the spec to only expose transport objects at the "answer" step? @steveanton
This would probably make "rollback" easier, since you wouldn't have to deal with rolling back transports. Though I don't know, maybe conceptually you would have to roll back some sort of JSEP layer transport anyway? I don't know.

**Comment by steveanton** [comment]
At the very least ICE transports are created in setLocalDescription before the answer is received so that gathering ICE candidates can start. Some applications wait for ICE gathering to finish before sending the initial offer even.

DTLS/SRTP need information from the remote side to start so there's not much use seeing them early. Though the DTLS transport could be created before the answer to cache any early CHLO packets.

**Comment by aboba** [comment]
@steveanton @henbos While the ICE transports exist after `setLocalDescription` is called so that gathering can begin, the IceTransport objects aren't visible to JS at that point. Since the DtlsTransport object is not created before SRD(answer), before that `transceiver.sender.transport` is null and there is no way to obtain `transceiver.sender.transport.iceTransport`.

**Comment by henbos** [comment]
OK. So it sounds like there may be some use of transports internally (JSEP layer - at least ICE, but possibly DTLS for early CHLO packets), but there would be little use in exposing them in JS early, it's not what we're currently doing, and if we were to start doing it that might add confusion in the case of bundle and transport.iceTransport?

**Comment by aboba** [comment]
@alvestrand Can you post a link to your updated pen?  I am getting the same results as @henbos did (no DtlsTransport or IceTransport visible until 'stable' state).

**Comment by aboba** [comment]
@henbos @alvestrand It appears that the current Chrome behavior matches the specification.  While there is some inconsistency between the behavior on the local and remote peer, this doesn't seem like a serious problem to me. The peer applying a remote offer will find that the objects become visible after calling createAnswer() and then setLocalDescription(Answer), so the delay in visibility is only due to execution time, not network delays.
