### ISSUE TITLE
Clarify what happens when rolling back an ICE restart

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2367]
Spin-off from [here](https://github.com/w3c/webrtc-pc/issues/2324#issuecomment-558127202):

> What is the effect of ICE restart? Does this need to be rolled back? What happens with generated candidates, will they get rejected by addIceCandidate? Is this something the app needs to be prepared for? Should we add a "note"?

@jan-ivar clarified that "restartIce() [survives rollback](https://github.com/web-platform-tests/wpt/blob/master/webrtc/RTCPeerConnection-restartIce.https.html#L344), createOffer({iceRestart: true}) does not."

I don't think clarification is needed for the fact that negotiation is still needed and iceRestart will be re-generated in the next offer.

What I am concerned about in this issue is what happens with candidates, old and new.
- If a candidate is generated that is then rolled back, are there any potential races with onicecandidate and addIceCandidate that we need to guard against or add a "note" for?
- What happens when you have candidates from both old and new generation? Do we need a step that says to revert the state of the ICE agent, etc?

Questions asked, I don't know the answer. Please take a look at this issue @jan-ivar

**Comment by henbos** [comment]
I'm guessing that the ice candidate that is generated becomes invalid. The remote endpoint would have to discard the candidate if it discarded the associated offer, or just be prepared for addIceCandidate throwing?

**Comment by henbos** [comment]
Interim [slide](https://docs.google.com/presentation/d/1QEdMf6Ixg1NNvHoZUvO29njrSKn9pdF1WqcrFWI4uX8/edit#slide=id.g6fb942d0d7_0_33): Works as intended, let's add a "note" that addIceCandidate may throw

**Comment by jan-ivar** [comment]
> The remote endpoint would have to discard the candidate if it discarded the associated offer, or just be prepared for addIceCandidate throwing?

Yes, except there's no need to throw. JS did everything right, and the user agent knows the new and old ufrags in this case, and can (and should) silently accept the old ones and silently ignore the new ones.

**Comment by jan-ivar** [comment]
We should add a test for this.

**Comment by jan-ivar** [comment]
>  are there any potential races 

There are no races thanks to the peer connection's [operations](https://w3c.github.io/webrtc-pc/#dfn-operations-chain) chain.

>  Do we need a step that says to revert the state of the ICE agent, etc?

Should already be covered by [JSEP](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-25#section-5.7): _"Any resources or candidates that were allocated by the abandoned local description are discarded"_

**Comment by henbos** [comment]
@jan-ivar What about the other endpoint?

pc1 generates ice candidates from an ICE restart and sends the offer to pc2.
pc2 creates an offer and discards pc1's offer because it is the unpolite peer.
pc1.onicecandidate fires and it sends the candidate to pc2. Would pc2.addIceCandidate() throw since it has not set the pc1 offer because it is unpolite?
pc1 receives the pc2 offer and, because it is polite, rolls back.
O/A exchange
pc1 will re-offer, resetting ICE again, and fire new candidates. The offer and candidates will be sent to pc2 and this time pc2 accepts then, everything is good.

**Comment by jan-ivar** [comment]
> pc2 creates an offer and discards pc1's offer because it is the unpolite peer. the ufrags will not be known by pc2.

There is a minor issue here with the impolite peer strategy, but it's unrelated to rollback.

To explain: Perfect negotiation involves two components that in concert avoid glare:
1. The polite peer uses rollback to avoid incoming offer collision
2. The impolite peer ignores the incoming offer to avoid collision

The first (rollback) part is fine, as I [mention above](https://github.com/w3c/webrtc-pc/issues/2367#issuecomment-558201617).

The second part does cause *addIceCandidate* errors, because an "impolite peer" is merely
`if (!polite) return`, so its peer connection object never learns about the would-be offer—there's no such thing as `pc.ignoreRemoteDescription(offer)`—so its *addIceCandidate* doesn't have enough info to silence the obsolete candidates. We first ran into this in https://github.com/w3c/webrtc-pc/issues/2164.

But this is true for any regular incoming offer collision, and not unique to offers with new ufrags.

I was planning to blog about this as a follow-up once perfect negotiation was further along. Unless we want to advocate for the aforementioned method, I vote we let JS handle this as best it can. The errors are harmless noise.

My current strategy—which I plan to blog about once perfect negotiation works in Firefox, to reduce complexity—is for the impolite JS to set a temporary `ignoredRemoteDescription` boolean to quelch *addIceCandidate* errors for a brief while after collision ([still-ugly fiddle](https://jsfiddle.net/jib1/uxdLzfh4/)):
```js
if (description) {
  if (!polite && description.type == "offer" && pc.signalingState != "stable") {
    ignoredRemoteDescription = true;
    return;
  }
  await pc.setRemoteDescription(description);
  ignoredRemoteDescription = false;
  if (description.type == "offer") {
    await pc.setLocalDescription(await pc.createAnswer());
    send({description: pc.localDescription});
  }
} else if (candidate) {
  try {
    await pc.addIceCandidate(candidate);
  } catch (e) {
    if (!ignoredRemoteDescription) throw e;
  }
}
```
Almost-perfect negotiation.

**Comment by jan-ivar** [comment]
If you run that fiddle in Firefox, I believe the `OperationError`s you get are from [bug 1542370](https://bugzilla.mozilla.org/show_bug.cgi?id=1542370).

**Comment by henbos** [comment]
OK thank you very much, so my assumption that this could catch you off-guard is correct, and given that we don't want to add pc.ignoreRemoteDescription(offer), a "note" is the way forward? The slide currently just says to add a note.

**Comment by henbos** [comment]
> But this is true for any regular incoming offer collision, and not unique to offers with new ufrags.

The note would belong to addIceCandidate, and "rollback" would just be possible way to trigger it.

**Comment by jan-ivar** [comment]
I don't know that we need to add a note to implementers over this, but it can't hurt I suppose.

**Comment by jan-ivar** [comment]
The spec doesn't really discuss perfect negotiation. Perhaps it should? I've opened https://github.com/w3c/webrtc-pc/issues/2370.

**Comment by henbos** [comment]
You know what, the clarification was less for implementers and more for "how to use these APIs". With your comment I am confident that this issue is a non-issue for "rollback". I think that if we add a Perfect Negotiation example as per #2370 then we can simply close this issue without adding a note. The issue only comes up when you have a real example (several APIs interacting with each other), so mentioning this inside of an example seems like the right thing to do.

**Comment by henbos** [comment]
Closing this in favor of #2370
