### ISSUE TITLE
new is not valid for SctpTransportState 

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#2422]
The algorithm to create an `RTCSctpTransport` asks to
> Let transport have a [[SctpTransportState]] internal slot initialized to initialState, if provided, otherwise "new".

But "new" is not a valid value of the `RTCSctpTransportState` enum

**Comment by alvestrand** [comment]
This algorithm seems to be called in a single place. Should we just remove "if provided, otherwise", and thus say that the argument is not optional?
(When implementing this in webrtc, I actually added a "new" state for my own convenience. I wouldn't mind adding it to the enum either.)

https://source.chromium.org/chromium/chromium/src/+/master:third_party/webrtc/api/sctp_transport_interface.h;l=25

**Comment by aboba** [comment]
The "new" state was defined in ORTC, so I'd also vote for adding it.

**Comment by dontcallmedom** [comment]
As Harald said, there is only one instance calling that algorithm, and it is called with initialState set to "connecting", so there is no way that I can think of that "new" will ever be an exposed value. If so, it sounds like rather than adding an untestable/invisible state, we should remove the "initialState" parameter, and have create an RTCSctpTransport always use "connecting" as its initialState.

I imagine the reason not to do that is if we plan on re-using this interface out of PeerConnection in a later version - if so, adding "new" is probably OK, although maybe somewhat premature. @alvestrand can you comment as to why you had added the "new" state in your Chromium implementation?
