### ISSUE TITLE
RTCAudioReceiverStats and RTCAudioSenderStats aren't MTI

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#2458]
`RTCVideoReceiverStats` and `RTCVideoSenderStats` are listed as mandatory to implement but their audio equivalent `RTCAudioReceiverStats`  and `RTCAudioSenderStats` aren't - I assume this isn't intended.

**Comment by jan-ivar** [comment]
[RTCAudioReceiverStats](https://w3c.github.io/webrtc-stats/#raststats-dict*) is empty,  but [RTCVideoReceiverStats](https://w3c.github.io/webrtc-stats/#asstats-dict*) is not.

In looking at this, the wording _"with all required attributes from its inherited dictionaries"_ seems unclear in hindsight. I think we mean s/required/mandatory/ and not e.g. the `required` WebIDL attribute.

Otherwise I think we'd need to explicitly exclude [obsolete members](https://w3c.github.io/webrtc-stats/#obsolete-stats).

**Comment by dontcallmedom** [comment]
Did you mean (as you linked to) `RTCAudioSenderStats` rather than  `RTCVideoReceiverStats`?

in any case, there are other empty dictionaries listed as MTI, so I'm not sure it's an argument for or against inclusion (if you were suggesting it, which I'm not sure either :)

(separately, I wonder if the MTI stats should also list the `RTCStatsType` entries that are expected - listing dictionaries only very indirectly answer the questions of which objects need to appear in an MTI-compliant `getStats()`.)

**Comment by alvestrand** [comment]
Seems that we should remove all empty dictionaries from the list. They don't add anything to requirements.

**Comment by jan-ivar** [comment]
Also, s/required/mandatory/

**Comment by henbos** [comment]
I suggest listing stats object (instances) rather than dictionaries
