### ISSUE TITLE
What direction should a stopped transceiver have? #661

### ISSUE THREAD

**Issue by armax00** [w3c/webrtc-pc#2479]
When stop() is executed, or more precisely when the "stop the RTCRtpTransceiver" step[2] is executed, the CurrentDirection slot is updated with a null value. Later, however, is indicated that currentDirection[1] should return "stopped" as a direction if the [[Stopped]] state is true.

This means that while currentDirection is null, the actual value returned would be "stopped".

Shouldn't it make more sense to set the currentDirection state to "stopped" rather then null when RTCRtpTransceiver is executed?

[1] https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-currentdirection
[2] https://w3c.github.io/webrtc-pc/#dfn-stop-the-rtcrtptransceiver

**Comment by henbos** [comment]
The [[CurrentDirection]] slot reflects what has been negotiated in SDP, meaning any of the values "sendrecv", "sendonly", "recvonly", "inactive", or if negotiation has not happened we use the value null.

Note that "stopped" is _not_ a direction that is used in SDP, it's something that we invented in webrtc-pc.

This is why currentDirection is implemented as:

- If transceiver.[[Stopped]] is true, return "stopped".
- Otherwise, return the value of the [[CurrentDirection]] slot.

This means that editorial-wise, we have two variables to represent a single state (currentDirection). Implementation-wise, it would probably be equally valid to have a single state (currentDirection) that also includes the value "stopped".

**Comment by henbos** [comment]
The decision to have a separate [[CurrentDireciton]] slot from the [[Stopped]] slot rather than a single slot that can be "stopped" was editorial and to separate what part correspond to JSEP and what part is invented by webrtc-pc.

**Comment by henbos** [comment]
I think the question was answered and that there is no immediate need to reformulate the spec.
