### ISSUE TITLE
Section 5.4.1 Simulcast functionality

### ISSUE THREAD

**Issue by 63isOK** [w3c/webrtc-pc#2480]
> This specification does not define how to configure **createOffer** to receive multiple RTP encodings. However when setRemoteDescription is called with a corresponding remote description that is able to send multiple RTP encodings as defined in [JSEP], the RTCRtpReceiver may receive multiple RTP encodings and the parameters retrieved via the transceiver's receiver.getParameters() will reflect the encodings negotiated.

createOffer or createAnswer?

This specification does not define how to configure **createAnswer** to receive multiple RTP encodings.

**Comment by aboba** [comment]
There is no way to configure a transceiver to receive multiple RTP encodings using `createOffer`, `createAnswer` or `setParameters`. This is because the `RTCRtpReceiver` has no `setParameters` method, and `addTransceiver` takes an optional `RTCRtpTransceiverInit` dictionary as an argument, which includes a `sendEncodings` member, but not `receiveEncodings`.
