### ISSUE TITLE
Assurance that requests to IdP proxy originate from the user agent

### ISSUE THREAD

**Issue by tidoust** [w3c/webrtc-pc#253]
In [section 9.1.2 Instantiating an IdP Proxy](http://w3c.github.io/webrtc-pc/#instantiating-an-idp-proxy), the spec claims that "A global property can only be set by the user agent or the IdP proxy itself. Therefore, the IdP proxy can be assured that requests it receives originate from the user agent. This ensures that an arbitrary origin is unable to instantiate an IdP proxy and impersonate this API in order obtain identity assertions".

It is true if the IdP JavaScript is loaded in the "isolated interpreted context" that the specification defines. However, what prevents an arbitrary origin from loading the IdP script in a regular window environment after having set "rtcIdentityProvider" to a fake value, thus impersonating the API?

There may be a way for the IdP proxy to validate the fact that it is running in an isolated interpreted context and/or that "rtcIdentityProvider" is indeed a platform object under the control of the user agent but I don't understand why the user agent can be the only one able to instantiate an IdP proxy. Did I miss something?

**Comment by martinthomson** [comment]
The theory here is that since the IdP is operating in the other origin, then the IdP loses access to information that only its origin knows.  The attack we need to be concerned about is where the attacker convinces the IdP to generate an assertion over an arbitrary input.  If the IdP does that without relying on information that only the real origin knows, then it will fool a genuine instance of itself into accepting the assertion.

However, it's possible that an IdP could be implemented in a way that does not rely on information provided by its origin (or it does not protect that information properly by enabling CORS).

I will note that this kind of attack makes the choice of using /.well-known/ less good from a security perspective.  A page on the same origin can mount this sort of attack.

This needs some text.  @alvestrand, please assign this one to me.  I'm not going to be able to get to this in the next two weeks, but I do want to address it.

cc @ekr

**Comment by alvestrand** [comment]
@martinthomson @ekr anything more to say on this one?

**Comment by martinthomson** [comment]
It's on the back-burner.  The explanation needs to be carefully constructed and I haven't had a good slice of time yet.

**Comment by elagerway** [comment]
In the editor's call today there was concern from everyone on the call regarding the current status surrounding identity in the draft. We are marking all identity-related issues for discussion at the next virtual interim.
