### ISSUE TITLE
Cannot create offer after stop transceiver

### ISSUE THREAD

**Issue by medved276** [w3c/webrtc-pc#2638]
I use peerConnection with some transceivers.
When I stop 2 of them...
`pc.getTransceivers()[0].stop()
`
...I try to createOffer at some moment.
But I got
`Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: The m= section with mid='2' should be rejected.`
What incorrect?

**Comment by henbos** [comment]
If you believe you have found a bug in a chromium-based browser, you may file a bug report over at https://crbug.com/.
But if you do, please provide a code snippet for example using https://codepen.io/ or https://jsfiddle.net/ that reproduces the problem so that one of the engineers can take a look.
