### ISSUE TITLE
Add Privacy/security review questions

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#265]
We should add a section with answers to the questions at https://w3ctag.github.io/security-questionnaire/. See https://github.com/w3c/mediacapture-main/issues/212 for more info.

**Comment by alvestrand** [comment]
I don't like adding questionnaire answers; they tend to become form letters rather than meaningful info. But anyone with the questionnaire should be able to get the answers to his questions from the security considerations section.

**Comment by gaperik** [comment]
The list of questions in the 'self-review' is quite long. Could be it may be well to encourage people to have a look at them individually and file issues. A kind of community self-review, :-)!

**Comment by dontcallmedom** [comment]
Here is a first stab at answering the questions (with the idea that we would want to check that the substance of the answers appear in the specs, and are referenced from the security/privacy considerations); corrections and feedback welcome.

> Does this specification deal with personally-identifiable information?

The specification defines a way to validate the user's identity via a third party identity provider. In addition, the protocol on which the specification is built exposes  IP addresses (which are in some case PII) of the user that are not exposed by the HTTP protocol. The exact scope of which IP addressed are thus revealed is still being discussed, with the hope of limiting it to private IP addresses (as defined in RTC1918) which are (ironically) less sensitive here than public IP addresses (e.g. from a split VPN connection).

> Does this specification deal with high-value data?

No (?)

> Does this specification introduce new state for an origin that persists across browsing sessions?

See answer to the question below.

> Does this specification expose persistent, cross-origin state to the web?

Yes, the exposure of private IP addresses can create a persistent state across origins since the IP addresses exposed will stay the same from one origin to another; this remains true across browsing session if the said IP addresses remain the same across browsing sessions.

The `getCapabilities()` static method of `RTCRtpSender` gives information about the underlying media system, in particular detailed information about the codecs that the media system is able to produce; in most cases, this constitutes a persistent and cross-origin state.

> Does this specification expose any other data to an origin that it doesn’t currently have access to?

None beyond the ones describe above.

> Does this specification enable new script execution/loading mechanisms?

Yes, this specification enables loading script for an identity provider in a separate JavaScript realm to enable validation of assertions by the identity provider.

> Does this specification allow an origin access to a user’s location?

No, although the protocol underlying this specification exposes more IP addresses than available via the HTTP protocol, and these additional IP addresses may bring more information that enable locating the user.

> Does this specification allow an origin access to sensors on a user’s device?

No.

> Does this specification allow an origin access to aspects of a user’s local computing environment?

See the answer to the question above about cross-origin persistent state — they are also information about the user's local computing environment.

> Does this specification allow an origin access to other devices?

No.

> Does this specification allow an origin some measure of control over a user agent’s native UI?

No.

> Does this specification expose temporary identifiers to the web?

Yes, it exposes the fingerprints of certificates used to establish a DTLS connection with a peer (?).

> Does this specification distinguish between behavior in first-party and third-party contexts?

No.

> How should this specification work in the context of a user agent’s "incognito" mode?

*I don't know*

> Does this specification persist data to a user’s local device?

No

> Does this specification have a "Security Considerations" and "Privacy Considerations" section?

It has a "Security Considerations" section, but does not have a "privacy considerations" section.

> Does this specification allow downgrading default security characteristics?

No

**Comment by alvestrand** [comment]
TPAC: @ekr has promised to take a look at this.

**Comment by alvestrand** [comment]
Ping @ekr again

**Comment by dontcallmedom** [comment]
I believe this can be closed now.

**Comment by stefhak** [comment]
Closing, I think the PRs https://github.com/w3c/webrtc-pc/pull/439 and https://github.com/tobie/specref/issues/230 addresses this Issue.
