### ISSUE TITLE
Need a bitrate definition

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#267]
#254 defines a max bitrate, but there isn't a definition for the term in the spec. Need to point to one (preferably one that the IETF agrees is relevant).

**Comment by alvestrand** [comment]
One possibility is to reuse the TIAS definition from RFC 3890 section 6.2.2.

Note that this definition doesn't say what period it's calculated over, nor does it say how to deal with undershoots and overshoots. If the IETF can live without these parts of the definition, can the W3C do likewise?

**Comment by juberti** [comment]
TIAS seems like the clear winner out of all the possible bitrate specifications. Agree the details can be left somewhat vague for now.

**Comment by aboba** [comment]
Here is an excerpt from RFC 3890 Section 6.2.2: 

The Transport Independent Application Specific Maximum (TIAS) bandwidth .... is the maximum needed ... without counting IP or other transport layers like TCP or UDP.

At the SDP session level, the TIAS value is the maximal amount of bandwidth needed when all declared media streams are used.  This MAY  be less than the sum of all the individual media streams values. This is due to the possibility that not all streams have their maximum at the same point in time.  This can normally only be verified for stored media streams.

**Comment by alvestrand** [comment]
The discussion at TPAC and IETF invoked the question of what timeframe we should look for a bitrate to be satisfied over - one second was proposed, but seemed to be thought a bit arbitrary. (Obviously it's not smooth at timescales less than the video frame size or audio packet time.)

**Comment by aboba** [comment]
Left in the note about "TODO: Find or create a definition for bitrate (how much header overhead is included, for example). Should be aligned with RTCOutboundRTPStreamStats.targetBitrate in webrtc-stats.".  Do we need another PR for targetBitrate?
