### ISSUE TITLE
insertDTMF is synchronous, but relies on asynchronous state-checking logic

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2738]
The steps for insertDTMF include the following:

"If [determine if DTMF can be sent](https://w3c.github.io/webrtc-pc/#dfn-determine-if-dtmf-can-be-sent) for dtmf returns false, [throw](https://webidl.spec.whatwg.org/#dfn-throw) an [InvalidStateError](https://webidl.spec.whatwg.org/#invalidstateerror)."

However, [determine if DTMF can be sent](https://w3c.github.io/webrtc-pc/#dfn-determine-if-dtmf-can-be-sent) says it is performed in a queued task.

We either need to make "determine if DTMF can be sent" synchronous, or we need to make insertDTMF return a promise, and make its validation logic async.

**Comment by alvestrand** [comment]
On reading through the validation steps, I don't see anything that would require them to be async, and it's referenced from 2 places - once from a sync method, and one from reading an attribute.

I suggest removing the "queue a task" part from "determine if DTMF can be sent".

**Comment by jan-ivar** [comment]
> I suggest removing the "queue a task" part from "determine if DTMF can be sent".

I agree. A return value from a queued task goes into the void, so this isn't implementable as written. Since browsers [appear to have done this correctly](https://wpt.fyi/results/webrtc/RTCDTMFSender-insertDTMF.https.html)¹ in spite of this, I'd call fixing this non-normative, since the intent seemed clear, and tests don't need to be changed.

---
<sub>1. WPT tests could be improved however, e.g. the sync attribute (`canInsertDTMF`) is only tested in a helper right now, with a carveout to help Firefox succeed where it shouldn't. Maybe @docfaraday could split this out as part of his work?</sub>
