### ISSUE TITLE
RTCStatsReport seems broken

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#275]
[RTCStatsReport](http://w3c.github.io/webrtc-pc/#idl-def-RTCStatsReport) is defined as:

    interface RTCStatsReport {
      getter RTCStats (DOMString id);
    };

From my understanding of WebIDL, dictionaries produced by this getter will contain `timestamp`, `type` and `id`, and *no other members*.

Since the intent here is to return dictionaries *derived* from `RTCStats`, I think it needs to be:

    interface RTCStatsReport {
      getter object (DOMString id);
    };

@bzbarsky, is that right?

**Comment by alvestrand** [comment]
Every time I have to resort to "object", @annevk or someone else usually comes up with a new way of doing things that I have not heard of before.... is there a way to do this in another way than "object"?

**Comment by annevk** [comment]
What is wrong with `RTCStats`? Derived from means they're still the same type. Using `getter` however is problematic actually. That should really be `legacygetter` in IDL, but that hasn't been fixed yet.

**Comment by alvestrand** [comment]
@annevk @jan-ivar you seem to have opposite opinions on what the legal return values from a function that returns a dictionary are. Could you cite WebIDL chapter and verse for that? (note that we're using the work-in-progress WebIDL, not the approved WebIDL, for lots of reasons).

@annevk why is getter problematic? Is it a technical issue or an "I don't like this style" issue?

**Comment by annevk** [comment]
It's technical in the sense that if we ever use JavaScript to implement these objects this would require a proxy. Which are quite complicated. It's also hard to extend this going forward.

**Comment by annevk** [comment]
I'm not really sure where https://heycam.github.io/webidl/ defines this, but dictionaries shouldn't be different from classes in this respect.

**Comment by jan-ivar** [comment]
Under [3.3. Dictionaries](https://heycam.github.io/webidl/#idl-dictionaries) it says: "any dictionary returned from a platform object will be a copy and modifications made to it will not be visible to the platform object".

Under [4.2.21 dictionary types](https://heycam.github.io/webidl/#es-dictionary) it says:

"An IDL dictionary value V is converted to an ECMAScript Object value by running the following algorithm (where D is the dictionary)"

where the copy algorithm uses this starting point:
* "Let dictionaries be a list consisting of D and all of D’s inherited dictionaries, in order from least to most derived."

I interpret this to mean "D + all dictionaries that D inherits from", meaning dictionaries derived from D are not included.

**Comment by annevk** [comment]
D should just be the type of V, unless I'm missing something.

**Comment by alvestrand** [comment]
So D is the type of the object V that the platform actually returns, and not the return type of the function?

That makes sense to me (and seems to match what other languages do with types of returned values).

**Comment by jan-ivar** [comment]
If V is an "IDL dictionary value", isn't that the IDL definition (RTCStats) rather than the implementation object? E.g. if this were implemented in c++, the binding code would expect a non-virtual RTCStats& which, while it would accept derived types like RTCRTPStreamStats, would not know how to copy more than the base class.

**Comment by annevk** [comment]
V is the "internal" IDL object. See the other convert operations.

**Comment by bzbarsky** [comment]
In this case the conversion will be done to the type declared in the IDL, not whatever subtype we happen to have, as far as I can tell.  So @jan-ivar is correct: if you want to return different dictionary subtypes you need to use `object`.  @annevk is also right that we shouldn't be adding new `getter` uses.

**Comment by annevk** [comment]
@bzbarsky can we change how IDL works for dictionaries then? It seems weird that dictionaries and classes have different rules.

**Comment by bzbarsky** [comment]
Classes have actual object identity, unlike dictionaries...

**Comment by bzbarsky** [comment]
Or, put another way, given a method that claims to return a dictionary `Foo`, an implementation that makes a copy of the `Foo` before returning it is not black-box distinguishable from one that does not, because there is no object identity involved.  The copy will obviously only copy things in `Foo` not in some sort of subclasses.

But more to the point, dictionaries are mostly designed to be used as options objects.  If you're using them as return values, chances are you're doing it wrong.  See https://lists.w3.org/Archives/Public/public-script-coord/2014JanMar/0201.html for my general feelings on the topic (and I didn't even write the post!).

**Comment by alvestrand** [comment]
@bzbarsky my opinion of "dictionary" is being rapidly confused.
What we want at this interface is something with return-by-value semantics (because we don't want any confusion about the JS changing stats values and having effects on anything internal). So "interface" has semantics we don't like; we're told to use "dictionary".
We want something that JS programmers can treat like a bag of values, with all the usual JS tricks for iterating over values, checking if values are present and so on; we're told to use "dictionary".

And now you come and tell us that you can't return a dictionary from a function and have the "dictionary" be polymorphic, because of this idea that dictionaries don't have object semantics.
We don't want object semantics. We want a bag of attribute name/value pairs. And we want it returned from a platform function.

The semantics of "interface" doesn't match. We don't want to carry implementation details into the object that's returned, and we want to *promise* that it's a dead object, not a live one.

The semantics of "object" are completely wrong. It doesn't guarantee anything.

And it's trivial to have the semantics we want in a pure Javascript object.

Have we really defined an interface language that is incapable of returning a data object that contains a type:value collection to the user?

(Dictionaries are also wrong for option objects, for other reasons. Different topic.)

**Comment by bzbarsky** [comment]
@alvestrand You can get return-by-value semantics with an interface return type: just return a new object each time.  That said, if you want to also allow sane iteration over the keys and values of the stats object then you probably do _not_ want return-by-value semantics.  You definitely don't want them for an IDL `getter`, because then you get `foo[bar] == foo[bar]` testing false, which is totally not something people would expect.  The fact that IDL allows this at all while disallowing dictionary-type attributes is just a bug in IDL that we should probably fix...

> And now you come and tell us that you can't return a dictionary from a function

You can.  You just have to write it as `object` in the IDL and then write prose defining exacty what gets returned.  That said, the IDL snippet above doesn't have a function.  It has a `[[GetOwnProperty]]` override, which is quite a different beastie.

> The semantics of "object" are completely wrong.

The semantics would then just be defined by the prose defining what the method actually does.

> Have we really defined an interface language that is incapable of returning a data object that
> contains a type:value collection to the user?

We designed an interface language that does not have simple syntax for doing that, because doing that is typically bad API design.  See the post I linked to above.  Of course the interface language is rich enough to allow you to express pretty much any weird behavior you want: you just end up having to define it in prose instead of using a predefined syntax.

**Comment by bzbarsky** [comment]
> (Dictionaries are also wrong for option objects, for other reasons. Different topic.)

I would appreciate you writing up what the issue is there and posting to public-script-coord.  Options objects are _the_ reason dictionaries exist in IDL at all.

**Comment by jan-ivar** [comment]
@bzbarsky why do dictionaries support inheritance?

I ask, because an obvious workaround to the dictionary inheritance problem here would be to define a single giant dictionary that encompasses all stats. That would work just great, yet hardly seems ideal or readable, as it would obscure what structure there is here.

It also seems to me that, since a webidl compiler already knows everything that's derived from dictionary X, recognizing that union as a type doesn't seem far fetched. I.e. *a union of all known descendants of dictionary X*. That would solve the readability problem (that is, if you agree with the use case, which it sounds like you don't).

As for the `getter` problem (getters being a legacy thing we want to avoid), you'd mentioned `maplike` to me on irc. If we did that, then we'd still have this union problem:

    interface RTCStatsReport {
      readonly maplike<DOMString, object>;
   }

I.e. we'd wish there was a way to say:

    typedef (RTCStats or RTCRTPStreamStats) AllRTCStats; // apologies for the spit-balling!

    interface RTCStatsReport {
      readonly maplike<DOMString, AllRTCStats>;
   };

Does this seem like a terrible use of maplike?

**Comment by martinthomson** [comment]
This conversation is giving me flashbacks to the unique particle attribute problem.

**Comment by jan-ivar** [comment]
(still spitballing) the typedef could error on conflicting member names that aren't a result of common inheritance.

**Comment by bzbarsky** [comment]
@jan-ivar Dictionaries support inheritance so that you can have `interface X : Y` and then have `dictionary XInit : YInit` and then pass instances of `XInit` to the `X` constructor, which will then pass them to the `Y` constructor, which will only look at the `YInit` bits of them.

As far as unions of dictionaries...  IDL doesn't support them because for _arguments_ they make no sense.  That said, for return values that would not be an unreasonable thing to do, and I thought there was an existing request for IDL to support that, but I'm not seeing it right now.  Again, you can already do this via prose; we're just talking syntactic sugar here.

> If we did that, then we'd still have this union problem

Yes, the `getter` business is orthogonal to the type the getter returns, except for the fact that having the `getter` return a dictionary is particularly bad as noted above.

The maplike use you propose seems fine, and would work fine with `object` too.  Again, you'd just need a bit of prose defining what gets stored in the backing `Map` is all.

**Comment by alvestrand** [comment]
Actually maplike sounds much more like what we wanted than a getter.
I'll create another bug for that change (getter to maplike). As far as I can tell, that won't change Javascript code using this API at all. #285 filed.

What to return from the API is still an open question. "interface" seems to have the right semantics for its inheritance - we can return a subclass object from a superclass function, I think.

**Comment by bzbarsky** [comment]
Maplike and `getter` look pretty different from a consumer's point of view.  It's the difference between `foo["bar"]` and `foo.get("bar")`,

**Comment by martinthomson** [comment]
I think that we can tolerate that difference.  We don't have a lot of interoperability on `getStats` right now.

**Comment by jan-ivar** [comment]
I agree with Martin.

**Comment by jan-ivar** [comment]
See https://github.com/w3c/webrtc-pc/issues/285 which would solve this.

**Comment by alvestrand** [comment]
Seems solved by #301
