### ISSUE TITLE
We should specify the intended behavior of addTrack, then setParameters(unicast), then sRD(simulcast offer)

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2777]
There are two options here:

1. The setParameters (which by necessity will be unicast) establishes a unicast envelope; the sender should reject any new encodings in an sRD.
2. The setParameters does not set the simulcast envelope; a sRD(simulcast offer) can cause simulcast to happen, just like it could have if there was no setParameters call.

On the one hand, performing a unicast setParameters likely means that the user wants to do unicast. On the other hand, receiving a sRD(simulcast offer) might mean the opposite. The user is probably confused in some way here.

**Comment by jan-ivar** [comment]
Option 2 because nothing in the spec so far indicates setParameters establishes any simulcast envelope, so that would be surprising new behavior I think.

setParameters promises to modify the (in this case one) layer(s) you told it to, and I see no reason why it cannot succeed at that just because new layers pop up. If you mix ice cream and dirt, POLA is you get dirt ice cream.

**Comment by jan-ivar** [comment]
With https://github.com/w3c/webrtc-pc/pull/2758 fixed, I believe with the spec now works like option 2.

**Comment by jan-ivar** [comment]
To be clear, I claim the spec worked like option 2 beforehand as well.

**Comment by jan-ivar** [comment]
Closing based on offline conversation with @docfaraday.
