### ISSUE TITLE
scaleResolutionDownBy's odd-resolution requirement trips up HW encoders

### ISSUE THREAD

**Issue by Drekabi** [w3c/webrtc-pc#2802]
Some hardware encoders require specific alignment values that need to be taken into consideration when requesting specific resolutions.

https://w3c.github.io/webrtc-pc/#dfn-rtp-media-api  says:
"When video is rescaled, for example for certain combinations of width or height and [scaleResolutionDownBy](https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-scaleresolutiondownby) values, situations when the resulting width or height is not an integer may occur. In such situations the user agent MUST use [the integer part of the result](https://tc39.github.io/ecma262/#eqn-floor)."

I would like to propose that this text be amended to support selecting a resolution supported by the encoder greater than the calculated scaled resolution. It appears the [Chrome implementation](https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/video/config/encoder_stream_factory.cc;l=452;drc=2df668b7cbf6c1d0766b6ee0ae8147adc8830f2e) may already be doing this.

**Comment by jan-ivar** [comment]
Hmm, should we decrease the resolution instead? cc @Pehrsons 

Encoders may vary across devices, so predictable and consistent behavior across devices seems desirable. Which way provides it?

My initial thought was to guarantee JS a minimum resolution, thinking this would at least give JS the amount of pixels it asked for. I figured JS could use layout or cropping to remove excess pixels to achieve behavior parity* across devices. Seems to work well for cameras at least.

But unless the user agent left a black border in the alignment area (centering video scaled to pre-alignment dimensions), then the image will be marginally bigger, and JS doing such cropping would be chipping away (or obscuring) actual data. This may not be evident with a camera, but with a screen-sharing presentation it might cause loss of visible borders for instance (downscaling may cause this anyway, but this may exacerbate the effect perhaps?)

Would providing a maximum (smaller) resolution instead be better? If so, we'd need to address what happens if realignment drops one dimension to 0.

**Comment by jan-ivar** [comment]
> There are more reasons why the send resolution could be decimated than just scaleResolutionDownBy

Good point. In fact, the source resolution itself may need alignment, and it would seem unexpected to upscale in that case IMHO. I'll update the PR to round down.

**Comment by jan-ivar** [comment]
> ... should the spec mention other reasons the resolution could get affected?

The preceding paragraph seems to cover this by referencing RFC8829. LMK if it should say more. On reading up on this, downscaling definitely seem to be the way to go. Thanks for catching that!

PR updated. PTAL
