### ISSUE TITLE
Stats return object should have maplike, not getter

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#285]
The current getStats spec says:

interface RTCStatsReport {
    getter RTCStats (DOMString id);
};

It's been suggested that we should use the new WebIDL feature called "maplike":

interface RTCStatsReport {
  readonly maplike<DOMString, RTCStats>;
};

(The particular type returned is a different problem due to dictiionary semantics; this is being discussed in #275.)

Offhand, I *think* this would result in no change to the Javascript code that uses the feature, avoid the use of the seemingly-deprecated "getter", and document a little more neatly what we're trying to do here.

**Comment by alvestrand** [comment]
@bzbarsky says

"Maplike and getter look pretty different from a consumer's point of view. It's the difference between foo["bar"] and foo.get("bar"),"

Which is which? I thought a named property getter supported foo["bar"]; does maplike require one to use the "get" pseudo-operation?

**Comment by alvestrand** [comment]
It seems that https://github.com/w3c/encrypted-media/issues/25 concluded that maplike was a bad idea for their usage.

**Comment by bzbarsky** [comment]
@alvestrand maplike requires "get"; it basically looks just like a JS `Map`.  And it's a better idea than `getter` for the same exact reasons that `Map` is a better idea than using objects as hashtables in JS, including key name collisions with methods on the object and whatnot.

Maplike is not a good fit if you want a key comparison function other than JS `===`, which is what encrypted media ran into: they wanted typed array keys with the comparison function being data equality not object equality.  But your keys are strings, so that's not a problem for you.

**Comment by jan-ivar** [comment]
> It seems that w3c/encrypted-media#25 concluded that maplike was a bad idea for their usage.

@alvestrand from https://github.com/w3c/encrypted-media/issues/25#issue-55440887 their usage seems to involve using an object as a key and expecting `{ key: 1 } ==  { key: 1 }`. We don't have that problem here.

**Comment by alvestrand** [comment]
Solved by #301
