### ISSUE TITLE
Is it illegal to modify sdp between createOffer and setLocalDescription?

### ISSUE THREAD

**Issue by y-i** [w3c/webrtc-pc#2907]
I read "4.4.2 Interface Definition" and have a question about [[LastCreatedOffer]].

```js
const offer = await pc.createOffer();
// modify sdp
await pc.setLocalDescription(offer);
```

Considering the behavior of the above code, according to step 5 of createOffer, the value will be set in [[LastCreatedOffer]] when createOffer is called.

If setLocalDescription is called after editing the SDP, it appears to be rejected with an InvalidModificationError because an sdp different from [[LastCreatedOffer]] is passed in step 4.2.
However, when I actually run it, all modern browsers (Chrome/Firefox/Safari) resolve it.

Am I misunderstanding something about this?
Or do all browsers violate the spec?

**Comment by henbos** [comment]
All browsers are violating the spec. Modifying SDP is not allowed.

**Comment by henbos** [comment]
Historically, features have been shipped via SDP modifications rather than APIs. The API side of things have been playing catch-up, e.g. [setCodecPreferences()](https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-setcodecpreferences) to allow modifying codecs that way instead of "[SDP munging](https://webrtc.github.io/samples/src/content/peerconnection/munge-sdp/)" or [modifying header extensions to negotiating in the extension spec](https://w3c.github.io/webrtc-extensions/#rtp-header-extension-control). So the list of reasons for SDP munging is quite small these days, but I'm not sure all holes have been plugged just yet.

**Comment by henbos** [comment]
@jan-ivar @alvestrand Should we make an official list of "holes that needs to be plugged"?

**Comment by y-i** [comment]
Thank you for explaining the detail.
In my case, I modified a SDP directly to use L16 to use Lyra codec over WebRTC.

**Comment by alvestrand** [comment]
Enabling encoding/decoding of non-default-enabled but implemented codecs is
a missing piece of API, so yes.
I *think* you can get it by manipulating the remote SDP instead of the
local SDP (which is allowed) but that may require that the remote end sends
the offer, which may be a nonstarter for your particular use case.

**Comment by henbos** [comment]
We should add a test for this (that would fail)

**Comment by fippo** [comment]
Discussion how to enable codecs like L16 should now happen in #2925
