### ISSUE TITLE
WebRTC/WebCrypto mismatch: AlgorithmIdentifier is missing 'hash', WebCrypto normalization unhappy

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#322]
The following AlgorithmIdentifier value must be supported by the user agent for generateCertificate:
{ name: "RSASSA-PKCS1-v1_5", modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]) }

But it must also produce a non-error result when normalized according to the WebCrypto normalization process with an operation name of generateKey. However, see https://dvcs.w3.org/hg/webcrypto-api/raw-file/tip/spec/Overview.html#rsassa-pkcs1. Normalizing with generateKey takes parameters RsaHashedKeyGenParams, which are the expected parameters (name, modulusLength, publicExponent) plus "HashAlgorithmIdentifier hash".

Is this a WebCryptoAPI or WebRTC bug? In order to pass the normalization process one could add hash:"SHA-1" to our AlgorithmIdentifier, but that would force WebRTC implementations to use a certain hash algorithm (I don't know how or when this applies, but current chromium webrtc code does not have a hash alg parameter of any kind).

(This issue is similar/related to https://github.com/w3c/webrtc-pc/issues/310 which updated publicExponent from an integer to Uint8Array.)

**Comment by henbos** [comment]
The WebRTC spec (http://w3c.github.io/webrtc-pc/#widl-RTCPeerConnection-generateCertificate-Promise-RTCCertificate--AlgorithmIdentifier-keygenAlgorithm) says "The browser selects the algorithm used to sign the certificate; a browser should select SHA-256 if a hash algorithm is needed."

Is this the same use of "hash" or something else? If so the WebRTC spec could be updated to require hash: "SHA-256", with the same behavior, and the normalization process will be happy.

(Interestingly, the "18.5.2. For Implementers" of the WebCryptoAPI spec suggests RSASSA-PKCS1-v1_5 with SHA-1 for initial implementations but we're not using webcrypto generation code, just normalization.)

**Comment by pthatcherg** [comment]
I believe you are correct that {hash: "sha-256"} or similar needs to be passed into the normalizeAlgorithm internal to the browser, but the spec leaves it up to the browser to choose which algorithm to use.   You are correct that this is the hash used to sign the certificate, and the place where it says "should select SHA-256" is referring to the same algorithm as should be passed into {hash: ...}.  

FYI, Chrome currently uses sha-256 for the signing here:

https://code.google.com/p/chromium/codesearch#chromium/src/third_party/webrtc/base/opensslidentity.cc&l=132&rcl=1444246385

**Comment by henbos** [comment]
Ok thanks.
The spec leaving it up to the browser to choose which algorithm to use is problematic though because webcrypto demands the user to specify a hash. We must either oblige or have a specific hash that is required. Or WebCryptoAPI should update as to support not specifying hash (have it be optional), such is the case with other algorithm identifiers I believe.

**Comment by pthatcherg** [comment]
WebCrypto demands a hash be passed in, but can't the WebRTC parts of the browser put in a hash between when it gets the rest of the parameters and when it passes it into WebCrypto?

**Comment by henbos** [comment]
Sure I can inject a hash value and "trick" WebCrypto but this workaround introduces an inconsistency between the two specs. The WebRTC spec says that the AlgorithmIdentifier [must] be produce a non-error result according to the WebCrypto algorithm normalization process. If we're making it work without the hash then we're allowing values that would produce an error result. I agree that we don't want that hash member, but as a matter of spec consistency and spec compliance... :/
I could do the "hash injection" for now.

**Comment by pthatcherg** [comment]
Yes, that's a good point about the non-error result.  If the browser will inject an option automatically, we should make that clear.  And if we require JS to pass in a hash, we should make it clear what values are allowed.  And we should make it consistent across browsers.

**Comment by martinthomson** [comment]
I could go either way on this.  Firefox currently insists on receiving a hash for the RSA options, but could easily be changed to be more permissive.  I haven't actually checked what happens with the hash, but I believe that it is ignored.  Here's how I see the alternatives:

1. Requiring the hash means that the hash needs to be checked against what the browser is willing to produce.  A hash parameter could enable some control over hashes, but since that only applies to RSA, that's not really a meaningful advantage; rather, I see that as problematic.

2. Injecting the hash means that this is less like WebCrypto, but it does mean that it is marginally easier to use.  However, we have to deal with the possibility that a hash parameter is provided.  In that case, you don't avoid the need to check.

I think that I'm leaning toward the injection option.

**Comment by alvestrand** [comment]
I would tend towards specifying the hash explicitly - the fewer gratuitous mismatches we have between WebCrypto and what we have, the better. It takes more lines to specify "and when you use this with WebCrypto, specify the hash SHA-256" than to add ", hash=SHA-256" to the specification of the "MUST be supported" algorithm.
(specifying SHA-1 is going to require adding more lines in order to justify choosing an obsolete algorithm, even if the justification is "it's going to be ignored").
