### ISSUE TITLE
Consider using the streams API for DataChannel instead of basing on Web Sockets

### ISSUE THREAD

**Issue by domenic** [w3c/webrtc-pc#334]
The web sockets API suffers from some major flaws, in particular its lack of backpressure support. We are hoping to replace it with a streams-based alternative [in the near-ish future](https://www.w3.org/Bugs/Public/show_bug.cgi?id=23992). It is a shame that Web RTC is on track to inherit that API's mistakes.

Right now the web platform contains a number of disparate and subpar strategies for streaming data; the web socket API is one of them. This is similar to [the situation we used to have with promises](http://www.w3.org/2001/tag/doc/promises-guide#legacy).

The [Streams Standard](https://streams.spec.whatwg.org/) provides a unifying primitive for all such cases, similar to how promises gave us a uniform primitive for single one-and-done asynchronous operations. Ideally, DataChannel would be a duplex stream, consisting of { readable, writable } pairs. You can see an example of this in the [TCP/UDP Sockets API draft](http://www.w3.org/2012/sysapps/tcp-udp-sockets/).

However, I understand if there's a desire to proceed with DataChannel as currently specced, since I think it has one or two interoperable implementations. In the future a stream-based version could be worked on as an addition. We are just in the early stages of the streams renaissance, with specs like Fetch leading the way; it's understandable if you don't want to be part of the first wave. I just wanted to bring this up, since the public-webapps email specifically mentioned the desire for feedback on "the DataChannel API which is heavily inspired from the WebSockets API".

**Comment by alvestrand** [comment]
Considered at TPAC, we are not considering this for WebRTC 1.0.

**Comment by domenic** [comment]
Is there a reason to close the issue, instead of leaving it open for future versions of Web RTC?

**Comment by alvestrand** [comment]
We have adopted the style of leaving issues open only if we are intending to do something about them in the current version; for suggestions for later versions, we are assigning the LATER label and closing them.
The thought is that we'll look at the LATER label when we reopen the spec.

(BTW, I think the streams interface may need some work in order to make it intuitive when dealing with asynchronous and/or unreliable channels - which WebRTC apps will be using - but I have to study the streams interface more before I can make any sensible suggestions here.)

(BTW(2) a data channel is one-way, not two-way. Apps can choose to make pairs of them if they need pairs - or not make pairs of them if that makes sense for their app. We'd like to keep it that way.)

**Comment by domenic** [comment]
> We have adopted the style of leaving issues open only if we are intending to do something about them in the current version

OK, cool, thanks for explaining.

> BTW, I think the streams interface may need some work in order to make it intuitive when dealing with asynchronous and/or unreliable channels - which WebRTC apps will be using - but I have to study the streams interface more before I can make any sensible suggestions here.
