### ISSUE TITLE
[clarification] may iceServers in RTCConfiguration be null?

### ISSUE THREAD

**Issue by AVGP** [w3c/webrtc-pc#34]
In 4.2.1.1 the spec reads:

    iceServers of type sequence<RTCIceServer>
    An array containing URIs of servers available to be used by ICE, such as STUN and TURN server.

which doesn't specify that it may be "null" as well. At least that's what Chrome seems to allow me to do just fine. So I'm wondering if it's just me being too easily surprised here, the spec being a tad fuzzy or the implementation being off...

Sorry if this is a silly question :/

**Comment by dontcallmedom** [comment]
as far as I can tell, Chrome now barfs if iceServers is null:
```javascript
new webkitRTCPeerConnection({iceServers:null});
//VM124:2 Uncaught TypeError: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration```

That being said, I'm not sure why the spec requires iceServers, or RTCConfiguration at all.

**Comment by jan-ivar** [comment]
I think RTCConfiguration is required because without iceServers, connections will always fail (except to peers inside the same LAN), a common pilot error.

Firefox does let you omit RTCConfiguration because Mozilla has a default stun server [but we're in the process of removing it](https://bugzilla.mozilla.org/show_bug.cgi?id=1143827).

Enforcing invariants: No reason to support `{ iceServers:null }` over `{ iceServers:[] }`

All that said, I believe Firefox currently allows allow passing in `{ iceServers:[] }` for LAN-only use, and that seems like a good idea to me. Not sure why we're disallowing it.

**Comment by juberti** [comment]
For demo pages, e.g. two PCs in the same page, there is no need for a STUN server.

I think iceServers:[] should be tolerated, along with iceServers being omitted completely, or even a null RTCConfiguration, since use of null is common in many of the existing demo pages. 

I don't see a need to allow iceServers:null, since there are simpler ways of expressing the same thing.

**Comment by jan-ivar** [comment]
Firefox does not allow a `null` RTCConfiguration, never has, but agree with everything else.

**Comment by juberti** [comment]
http://webrtc.github.io/samples/src/content/peerconnection/pc1/ passes null and seems to work OK in FF.

**Comment by jan-ivar** [comment]
Indeed it does. I asked our resident guru and just learned that dictionary arguments are always nullable, and that passing `null` is the same as passing `{}`. So problem solved.

**Comment by alvestrand** [comment]
Closing as resolved - dictionary arguments are always nullable, and when we know that, the spec is unambiguous.

**Comment by AVGP** [comment]
Thanks for clarification! :)

**Comment by jan-ivar** [comment]
Note that the spec disallows `{ iceServers:[] }` which means the lone way to turn off Ice is to omit `RTCConfiguration` entirely, which leaves a way to turn off Ice, just not way to off Ice ***and*** set other things, which seems inconsistent.
