### ISSUE TITLE
Should references to RFC5506 and  RFC3550 be normative?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#344]
the reducedSize attribute of the RTCRtcpParameters dictionary refers to these RFCs, but non-normatively.

**Comment by dontcallmedom** [comment]
the same question applies for RFC5285 referenced from RTCRtpHeaderExtensionCapability, and IANA-RTP-2

**Comment by aboba** [comment]
The RTP-Usage document includes normative requirements for RTP functionality including RFC 3550 (Section 4.1 and other sections), RFC 5506 (Section 4.6) and RFC 5285 (Section 5.2).  Since RTP-Usage describes the requirements in such detail, it is the appropriate normative reference, and other RTP-related RFCs including 3550, 5506, 5285, etc. can be referenced informatively.  IANA-RTP-2 is a reference to a registry not a specification.

**Comment by dontcallmedom** [comment]
OK, sounds reasonable to me, thanks. Closing.
