### ISSUE TITLE
true as default values for dictionary is bad practice

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#375]
The [WebIDL spec](http://heycam.github.io/webidl/#idl-dictionaries) warns that:
> [it] is strongly suggested not to use of true as the default value for boolean-typed dictionary members, as this can be confusing for authors who might otherwise expect the default conversion of undefined to be used (i.e., false). 

We have true as default of:
* `ordered` in `RTCDataChannelInit`
* `voiceActivityDetection` in `RTCOfferAnswerOptions`
* `send` and `receive` in `RTCRtpTransceiverInit`

This means that e.g. `createOffer({voiceActivityDetection:undefined})` keeps voice activity detection on, which is indeed confusing.

I'm not sure if we still have room for change here; one option would be invert the property names (e.g. unordered, disableVoiceActivityDetection, receiveOnly, sendOnly).

**Comment by alvestrand** [comment]
We also have some places that exhort against negative truth values (don't use "disable"). And receiveOnly = true, sendOnly = true as a synonym for "inactive" would just look weird, so it would have to be full inversion and say "disableSend" / "disableReceive".

Can we make undefined (as opposed to "missing") a TypeError somehow, so that createOffer({voiceActivityDetection: undefined}) fails fast?

**Comment by martinthomson** [comment]
An `undefined` value and omission from the dictionary are undetectably identical.

One approach would be to use enumerated strings rather than booleans:

```js
createOffer({voiceActivityDetection: 'disabled'})
RTCRtpTransceiverInit('sendonly'||'recvonly'||'sendrecv'||'inactive')
```

Given that each of these is only set to something other than a default rarely, I think that this would be OK.  Also, an enumerated value will make the API use more clearly self-documenting.

**Comment by dontcallmedom** [comment]
I've created a pull request for `RTCRTCTransceiverInit` and `RTCOfferOptions`, where I think the backwards compat risk is low.

But I'm not sure we can still afford to change `RTCDataChannelInit.ordered` — I assume this one is already in wide use.

**Comment by martinthomson** [comment]
@jesup would know better than I, but I think that ordered could be dealt with in a backwards-compatible fashion by defining a union of bool and a new enumeration.  Or we can leave browsers to deal with the mess and just move to a new enumeration.

**Comment by dontcallmedom** [comment]
in PR #471 I've used a union of Boolean and enum in the init dictionary, and set the type of the attribute in the interface to the enum.

**Comment by alvestrand** [comment]
Den 18. jan. 2016 10:33, skrev Dominique Hazael-Massieux:
> in PR #471 <https://github.com/w3c/webrtc-pc/pull/471> I've used a union
> of Boolean and enum in the init dictionary, and set the type of the
> attribute in the interface to the enum.

<standard worry>
Does this have the right characteristics if we want to extend the enum?

(I think it does - these are "if you ask for it, you probably want it hard")

**Comment by dontcallmedom** [comment]
Yes, I think it has the right characteristics: if you want to init a data channel with the new value "reverse" and the browser doesn't know it, it will abort with a TypeError.

**Comment by fluffy** [comment]
I'll note that voiceActivityDetection is a pretty confusing name to start with.

**Comment by alvestrand** [comment]
This seems to be closable now, with the resolution proposed on the list, and its response.
