### ISSUE TITLE
Should have a "closed" RTCPeerConnectionState

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#389]
[The spec says](http://w3c.github.io/webrtc-pc/#idl-def-RTCIceConnectionState): [RTCIceConnectionState's] "`closed` occurs only if `RTCPeerConnection.close()` has been called."

With "closed" having more to do with the peer connection as a whole rather than the ICE agent specifically, and the rationale AFAIR for `connectionState` being to cover the peer connection as a whole more so than `iceConnectionState`, then it seems to follow that "closed" needs to be surfaced in (moved to) the RTCPeerConnectionState.

**Comment by elagerway** [comment]
@pthatcherg This issue has been flagged for discussion at the interim on Thursday, do you plan on speaking to this? Slides placeholder: https://docs.google.com/presentation/d/1qfaxn8GMplm__s_ejMq6C3atA_pBnGXsjmAkKNIh3Ds/edit#slide=id.gf7328a83a_1_32

**Comment by pthatcherg** [comment]
ORTC has IceTransport.close() to close/stop the IceTransport, and so also has a "closed" state.

WebRTC doesn't have IceTransport.close, because the PeerConnection closes the IceTransport instead of the application directly.  But the state still makes sense if an application could ever see an IceTransport by doing pc.getSenders()[0].transport.transport after the PeerConnection is closed.

**Comment by elagerway** [comment]
@pthatcherg as we discussed at the interim last week, it's on you to create a PR for this:
https://www.w3.org/2016/01/14-webrtc-minutes.html#item03.6

**Comment by alvestrand** [comment]
It's been suggested (in #530) that removing "closed" from RTCPeerConnectionState is reasonable too.

**Comment by dontcallmedom** [comment]
#553 is the relevant PR
