### ISSUE TITLE
Framerate knob for simulcast

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#412]
The discussion at TPAC concluded that we need a knob to control framerate per stream when simulcast is used.

**Comment by aboba** [comment]
How about this? 

partial dictionary RTCRtpEncodingParameters {
             unsigned long       maxFramerate;
};

maxFramerate of type unsigned long
The maximum framerate to use for this encoding. 

A remaining question:  how is the receiver's maximum framerate determined?  This could be codec-specific, because a device might support hardware decoding for one codec, but not another.  

 Since not all codecs include a max-fr SDP parameter (e.g. VP8 does, but H.264 does not), this value cannot be determined from SDP for all codecs. 

Do this imply that we need to add maxFramerate as a generic codec capability in RTCRtpCodecCapability?  Today, all we have is mimeType.

**Comment by elagerway** [comment]
This issue has been flagged for discussion at the interim on Thursday, Slides placeholder: https://docs.google.com/presentation/d/1qfaxn8GMplm__s_ejMq6C3atA_pBnGXsjmAkKNIh3Ds/edit#slide=id.gf7328a83a_1_27

**Comment by aboba** [comment]
At the interim, I believe that consensus was to leave maxFramerate in the spec, and not put in another framerate knob.  If so, this issue can be closed.
