### ISSUE TITLE
RTCSessionDescription should not allow nullable sdp

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#420]
Unless I missed something, I see no reason why the sdp attribute of `RTCSessionDescription` is marked as nullable.

From what I can tell, it was made nullable when `RTCSessionDescriptionInit` was introduced (commit fcda53c460a3f8e32db683f6284dfabed3688a3a), and that was probably needed to be compatible with dictionaries when they could not have required members.

But `RTCSessionDescriptionInit` has now `type` as required, and I think it should also have `sdp` as required, and the sdp attribute in `RTCSessionDescription` marked as non-nullable.

Happy to provide the PR if I get confirmation the reasoning is valid.

**Comment by jan-ivar** [comment]
Makes sense to me fwiw

**Comment by martinthomson** [comment]
A `type` of "rollback" requires a `null` value for `sdp`.  The interface never needs to have a type of "rollback" though, so the '?' can be dropped.

**Comment by dontcallmedom** [comment]
@martinthomson good point re rollback; that said, is nullable really needed for RTCSessionDescriptionInit.sdp or is it enough to not make it required?

**Comment by martinthomson** [comment]
I don't think we should ever have a nullable, non-required dictionary attribute.  So yes, remove the ? from both places.  I didn't even notice that `RTCSessionDescriptionInit` had a nullable `sdp`, because that's never a good idea.

@jan-ivar, just calling this to your attention, Firefox uses `DOMString? sdp = "";` which I think we should change to match the updated version of this PR.
