### ISSUE TITLE
Non-normative ICE state transition diagram

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#457]
Figure 2 does not show transitions between 'checking' and 'disconnected'  (and back).

The transition from 'disconnected' to 'checking' can occur if a new interface comes up, thereby providing new candidates (and pairs) to check.

A transition from 'checking' to 'disconnected' can occur if the new candidate pairs do not result in a successful connectivity check, but gathering is still going on, so 'failed' has not been reached. 

Related ORTC Issue: https://github.com/openpeer/ortc/issues/332

**Comment by aboba** [comment]
For reference, here is the non-normative ICE state transition diagram from ORTC. 
<img width="432" alt="icestates-cont" src="https://cloud.githubusercontent.com/assets/808811/12187131/e4db72f0-b55d-11e5-87c1-e5798d731890.png">

**Comment by taylor-b** [comment]
I don't see how you could transition from "disconnected" to "checking" or vice versa (at least, for a single IceTransport). As I understood it, "disconnected" means "was previously connected, but a liveness check failed", and "checking" means "was *never* connected, and are still checking".

So, if a new interface comes up while in "disconnected", I would expect the state to remain in "disconnected" until a connection is found, then transition to "connected" and eventually "completed".

And if the ICE agent finishes checking current candidate pairs, but hasn't finished gathering, I would expect it to remain in "checking", since the definition of "checking" includes "may also still be gathering."

This kind of confusion is why I think we need a more well-defined algorithm for determining the ICE state, similar to what Peter did for RTCPeerConnectionState. I'll work on a PR to show what I mean.

**Comment by aboba** [comment]
The ICE agent can find a successful candidate pair and use it to send media before completing checking.  In this situation, RTCIceTransport.getSelectedCandidatePair() will return the selected candidate pair.  If RTCIceTransport.state is "gathering" then the application won't know that outgoing media is permitted. To clarify this, ORTC uses the following state definitions: 

checking: In this state the RTCIceTransport is checking candidate pairs but has not yet found a successful candidate pair, or liveness checks have failed (such as those in [CONSENT]) on a previously successful candidate pair.

connected: The RTCIceTransport has received a response to an outgoing connectivity check, or has received incoming DTLS/media after a successful response to an incoming connectivity check, but is still checking other candidate pairs to see if there is a better connection. In this state outgoing media is permitted.

completed: all appropriate candidate pairs have been tested and at least one functioning candidate pair has been found.

disconnected: all appropriate candidate pairs thus far have been tested and failed (or consent checks [CONSENT], once successful, have now failed). Other candidate pairs may become available for testing as new candidates are trickled, and therefore the "failed" state has not been reached.

failed: all appropriate candidate pairs have been tested and failed.

**Comment by taylor-b** [comment]
> If RTCIceTransport.state is "gathering" then the application won't know that outgoing media is permitted.

I'm confused; `gathering` isn't a possible value for RTCIceConnectionState. In this case, RTCIceTransport.state would be `connected`, so it should be clear that outgoing media is permitted, right?

Also, these state definitions (especially `disconnected` and `checking`) seem very different than the WebRTC ones. If we want to change the WebRTC state definitions, I think we need to have that discussion separately, and think about the impact to existing applications.

**Comment by pthatcherg** [comment]
As Taylor points out, it looks like the ORTC and WebRTC states for
checking/disconnected are incompatible.  It appears that when the
IceTransport is disconnected and checking after having been connected
previously, the WebRTC state is "disconnected", whereas the ORTC state is
"checking".  Was it an oversight that the ORTC definition isn't the same,
or was it intentional?


I like Taylor's idea of having a more concrete algorithm for what the state
would be.  The way I'm thinking of it is to break down the inputs into the
function which determines the state:
- Locally gathering or done
- Remotely gathering or done
- Checks are being sent or not
- Checks are succeeding or not
- Checks have ever succeeded or not
- The IceTransport/PeerConnection was explicitly closed

I think our current algorithm is something like:

if explicitly closed:
  closed
else if checks are succeeding:
  if local gathering done and remote gathering done:
    completed
  else:
    connected
else if checks are being sent:
  if checks have ever succeeded:
    disconnected  // ORTC says "checking" here
  else:
    checking
else if checks have ever succeeded:
  disconnected
else if local gathering done and remote gathering done:
  failed
else:
  new

Does that look correct?  If so the application can't tell if checks are
still being sent or not when in the disconnected state.  Perhaps that's why
ORTC changed it.

And, as mentioned previously, if we don't have a way to signal "done
gathering" (which we don't), then the failed and completed states are
impossible to get to.

**Comment by aboba** [comment]
Peter Thatcher said: 

"As Taylor points out, it looks like the ORTC and WebRTC states for
checking/disconnected are incompatible... Was it an oversight that the 
ORTC definition isn't the same, or was it intentional?"

[BA] Prior to the addition of objects, WebRTC 1.0's RTCIceConnectionState represented the state of the ICE Agent (aggregated for all ICE transports) whereas  ORTC RTCIceTransport.state reflects only the state of an individual ICE transport.  

Now that WebRTC 1.0 has added RTCIceTransport, there is a need to represent the state of the individual transport.  While the RTCIceConnectionState enum has the same states as RTCIceTransportState, the RTCIceConnectionState definitions reflect the states of an ICE Agent (aggregated among all ICE transports) whereas RTCIceTransportState reflects those of an individual ICE transport. 

Because of that, the state definitions may not necessarily line up.  However, since the state transition diagrams reflect the underlying ICE protocol, there would not seem to be a reason for them to differ. 

That said, the ORTC diagrams were developed with the Trickle ICE and continuous nomination in mind.  I would feel more comfortable about both the diagrams and the state definitions if there were text in the Trickle ICE specification (or some other ICE WG specification) to refer to, but at the moment it isn't clear to me what that would be.

**Comment by pthatcherg** [comment]
I think we should make the WebRTC and ORTC states the same.  I see no
reason to have them be different.  And while it's true that continuous
nomination would render the completed and failed states mostly irrelevant,
continuous nomination isn't a standardized thing yet, so it may be
premature to model our states around it.

I think the real question is: which state definition for
checking/disconnected is most useful for applications?  Whichever it is, we
should make that the definition for both.  And I think we should change the
ORTC one to match the WebRTC one until we figure out which it is (unless we
can decided very quickly).

**Comment by alvestrand** [comment]
Seems to be two different discussions:
- Whether the state diagram is complete/correct
- Whether ORTC and WEBRTC diagrams need to be equal

On the last point, I think it is fine if ORTC permits transitions that WEBRTC doesn't. If it's the other way round, that's a problem.

**Comment by aboba** [comment]
Currently the ICE state diagram in WebRTC 1.0 refers to transitions of iceConnectionState, which does not exist in ORTC  (e.g. in ORTC there is no aggregated state for the ICE agent as a whole). 

Whereas the diagram in ORTC refers to RTCIceTransport.state, which also exists in WebRTC 1.0 (but does not have a related diagram or section on transitions).  

So to some extent there is an apples/oranges problems here.  However, assuming that both specifications were to have material and/or figures discussing the behavior of RTCIceTransport.state, it seems to me that they should align, assuming that both specifications are citing the same underlying ICE protocol specifications.

IMHO, the additional transitions in ORTC appear to originate from assumptions about the operation of Trickle ICE (and continuous nomination in particular).  So one way to resolve this is to include text in the Trickle ICE specification clarifying the state transitions.

**Comment by alvestrand** [comment]
That makes sense. The ICE state diagram predates Trickle ICE.

**Comment by alvestrand** [comment]
#459 has been merged, but we should discuss this some more to make sure we have it right before closing the issue.

**Comment by aboba** [comment]
On Jan 11, 2016, at 7:56 AM, Peter Thatcher <notifications@github.com> wrote:
> 
> continuous nomination isn't a standardized thing yet, so it may be premature to model our states around it.

[BA] Isn't continuous nomination just a potential behavior within the current Trickle-ICE spec? There are no time limits on gathering. While Trickle-ICE is still a draft, it does seem important to have clarity about how it works, since it is being implemented. 

> Whichever it is, we should make that the definition for both. And I think we should change the ORTC one to match the WebRTC one until we figure out which it is (unless we can decided very quickly).

[BA] Personally, I would prefer to have the Trickle-ICE spec to cover these issues well enough that both specs could reference it.  States for individual transports may seem like an odd concept for the Trickle-ICE spec, though.

**Comment by elagerway** [comment]
@aboba do you plan on proposing something for this? If so, please edit the slides accordingly.

**Comment by nils-ohlmeier** [comment]
One issue which is not clear to me which I brought up in #517 is what "liveness checks have failed (such as those in [CONSENT])" means. I'm only adding this here, because it makes sense to me to try address this together.
I'm assuming it refers to the 30s final timeout from [CONSENT]. But I'm assuming that users of the API would also like to know about single [CONSENT] STUN transaction timeouts. If that is the case then how are we going to represent these potentially intermittent failures in the ICE state?

**Comment by aboba** [comment]
@elagerway I believe that Taylor's slides from the last interim covered this.

**Comment by taylor-b** [comment]
@aboba My goal for the interim tomorrow is definitely to clarify the meanings of the WebRTC ICE states. If we end up deciding to add an API to trickle end-of-candidates, I think we should just adopt the ORTC state definitions. They're almost identical to what I had in mind.

**Comment by aboba** [comment]
@taylor-b The new ICE agent state definitions proposed in https://github.com/w3c/webrtc-pc/pull/527/ look good.  However, it is not clear to me that the ICE agent state definitions in RTCIceConnectionState apply to RTCIceTransport.state.

**Comment by taylor-b** [comment]
I plan to address that in a follow-up PR. #527 just focuses on addIceCandidate.

**Comment by elagerway** [comment]
@taylor-b any feedback on this one ?

**Comment by taylor-b** [comment]
Since PR #527 was just merged, here's the follow-up PR I promised: #557

**Comment by alvestrand** [comment]
#557 is merged. Can someone propopse a diagram? Assigning to Taylor. (Please?)

**Comment by aboba** [comment]
@taylor-b With the clarifications proposed in PR https://github.com/w3c/webrtc-pc/pull/611 we may have a way forward. 

Specifically, the PR describes potential transitions from "connected" to "disconnected" or "checking" and from "completed" to "failed". 

A transition from "disconnected" to "checking" can occur if new candidate pairs become available. For example, if we were "connected" but consent fails, then a transition occurs to "disconnected" and from there to "checking" if new local candidates and/or remote candidates become available.

**Comment by aboba** [comment]
Given the potential transition between "completed" and "failed", is this diagram closer to correct?  If not, what do we need to add or remove? 
<img width="449" alt="ice-transition-state-newest" src="https://cloud.githubusercontent.com/assets/808811/15026000/e1353916-11f0-11e6-883a-8d8a4b7ca0ed.png">

**Comment by nils-ohlmeier** [comment]
The one transition in the diagram which is not clear to me is from "failed" to "disconnected". Because my current understanding is that difference between the two is if both sides have signaled end of candidates and so you either have more pairs to check or not.
I would expected that if any new candidate shows up in the "failed" state you would transition from "failed" to "checking".

**Comment by aboba** [comment]
@nils-ohlmeier  Yes, don't think you can go from "failed" to "disconnected".  So perhaps it should look like this: 
<img width="450" alt="ice-transition-state-newest" src="https://cloud.githubusercontent.com/assets/808811/15027597/786a296a-11f9-11e6-8094-39ffb7cf49ed.png">

**Comment by alvestrand** [comment]
PR #668 is expected to fix this.

**Comment by alvestrand** [comment]
Fixed by #668
