### ISSUE TITLE
Signaling a=end-of-candidates

### ISSUE THREAD

**Issue by martinthomson** [w3c/webrtc-pc#483]
Trickle ICE has a signal that says that there are no more candidates coming.  I can never remember whether it is per-component or per-agent, I think that it's the latter.

We currently do not have a way of providing that signal.  I believe that an `RTCIceCandidate` with a null `candidate` attribute has been suggested and maybe even implemented by some.  That doesn't require any new code paths in (most) clients, which would seem to be a virtue.

Current the `candidate` attribute is both mandatory and not nullable.

(I couldn't find an open issue on this, so here 'tis.)

**Comment by stefhak** [comment]
@martinthomson there is some related discussion in #442.

**Comment by aboba** [comment]
Section 4.9.2.2 permits the candidate attribute to be null: 

"The candidate attribute is the RTCIceCandidate object with the new ICE candidate that caused the event.  This attribute is set to null when an event is generated to indicate the end of candidate gathering."

However, as noted in Section 4.3.2.3, the candidate attribute supplied to addIceCandidate() cannot be null. 

Is this the missing functionality you are proposing to add?

**Comment by pthatcherg** [comment]
There's something for sending out an "end of candidates", but nothing for taking it in.  But it's not clear whether that's needed for anything anyway.  In fact, it's not clear whether the "end of candidates" signal coming out is needed for anything, since the application can just get the same information from the gathering state.

But this is one of the topics for the upcoming virtual interim (as part of the discussion of the failed ICE connection state).  Hopefully we can resolve it then.​

**Comment by elagerway** [comment]
@aboba 9 days to virtual interim, if there is a new proposal forthcoming please edit the slides https://docs.google.com/presentation/d/1R7lQeo4LNGu0KKW9GLdkwJ5x8FUmR4qrnhfPFZO3WS8/edit#slide=id.g828c698ba_0_25

**Comment by alvestrand** [comment]
Merged #527
