### ISSUE TITLE
Certificate API: Do we need certificate introspection?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#496]
At the moment, the certificate API we provide is this:

interface RTCCertificate {
    readonly        attribute DOMTimeStamp expires;
};

A question was raised on whether we could tell if a given cert was RSA or ECDSA - there doesn't seem to be one.

Would it be reasonable to require an introspection API that is able to tell something about it (possibly a subset of its keygen parameters)?

**Comment by henbos** [comment]
Getting an AlgorithmIdentifier, same format as the input for RTCPeerConnection.generateCertificate, makes sense to me. That is an established format and allows you to tell the difference between, say, RSA-1024 and RSA-2048.

**Comment by martinthomson** [comment]
I couldn't think of a reason that this would be needed in practice, hence my initial patch not including anything.  It's easy to implement, I think, but much harder to un-implement.  Does anyone have a use case?

**Comment by henbos** [comment]
I'm thinking it would probably be most useful for debugging or unit tests. I don't think this is strictly necessary, just that it might be nice to have in some cases. Like if you're generating multiple certificates it might be nice to be able to tell them apart based on inspection, not just based on which promise was resolved. Or debugging, being able to print "this is the cert we use" and that actually meaning something. And its funny you can do getConfiguration to get the list of certificates, but you can't tell anything about them.

If you don't specify which certificate(s) to use, RTCPeerConnection constructor creates certificate(s) for you. In this case, getConfiguration to get a set of certificates tells you nothing about which certificates are used. But I suppose you shouldn't have to know?

**Comment by aboba** [comment]
The use case would probably involve situations where the same certificate is used in multiple calls so that it might be handy not to have to store the associated keygenAlgorithm values. 

An example came up in ORTC to support forking, where multiple DtlsTransport objects would need to use the same certificate/fingerprint.  This lead to RTCCertificate being extended with the fingerprint (RSA vs. ECDSA wasn't relevant in that case): 

partial interface RTCCertificate {
    readonly        attribute RTCDtlsFingerprint fingerprint;
};

dictionary RTCDtlsFingerprint {
             DOMString algorithm;
             DOMString value;
};

**Comment by martinthomson** [comment]
Regarding fingerprint, I think that's a fine thing to add.  However, note that the same comments apply to that attribute as I made on #499.

**Comment by martinthomson** [comment]
Oh, and the formulation Bernard describes doesn't work if we have to entertain the notion of hash agility.

**Comment by aboba** [comment]
@martinthomson Can you explain the hash agility issue?

To generate a certificate/fingerprint with a new hash algorithm, we would presumably call generateCertificate() with a new value of keygenAlgorithm.hash.  

In contrast, this issue is about how to retrieve information about the algorithms used in an existing certificate.

**Comment by alvestrand** [comment]
Fix merged.
