### ISSUE TITLE
PING review of webrtc-pc spec

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#518]
The PING group has started discussing webrtc-pc here:

https://lists.w3.org/Archives/Public/public-privacy/2016JanMar/0019.html

This bug is intended to make sure we track what they discuss.

**Comment by alvestrand** [comment]
Still waiting for formal feedback.

**Comment by stefhak** [comment]
First, and still informal, feedback:
Questions summarized from the PING discussion:

1. In reading privacy/security considerations of the spec, the group recognized the various issues, but it was not always clear how issues were solved or mitigated. Can you provide more documentation on countermeasures and why certain decisions were made? Examples:  the concrete reasons to accept changes to the same-origin policy. (e.g., not only because websocket does it.)

2. Related items that were of concern, for which a response would be helpful: leaking of local IP addresses; change to the same-origin policy because of p2p communication; client-side or device id leakage; ad networks using WebRTC for accessing IP address.

3. As a user, I have concerns about wanting to know, for example, in WebEx: when I am speaking and where the data is going. Which items (indicators) are going to left up to the application, and which in the user agent? For example, camera light should be on when the camera is active--that shouldn't be left up to the application.
What would be helpful here is to describe what kind of risks exist and how they are prevented or solved.

4. It is troubling that once a WebRTC connection has been granted, could be very difficult for a non-expert user to discover/revoke -- how is this concern being addressed?

5.  What information is available prior to a permission prompt? Example: for a Tor activist user, what would they do when they might have to choose between communicating and revealing sensitive local information?

**Comment by stefhak** [comment]
We still have not received any formal feedback. Should we ping(sic) PING?

**Comment by dontcallmedom** [comment]
Looks like it was the formal feedback after all :)

I suggest splitting up the 5 aspects in 5 different issues (and close this one)

**Comment by stefhak** [comment]
@dontcallmedom I agree, and I think you took on filing those 5 separate Issues, right?

**Comment by dontcallmedom** [comment]
closing, since the 4 separate issues have been created: #687, #688, #689, #690
