### ISSUE TITLE
A data channel protocol can be "(╯°□°）╯︵ ┻━┻)"

### ISSUE THREAD

**Issue by martinthomson** [w3c/webrtc-pc#546]
...but that can't be registered according to RFC6455.  Should we throw if someone tries to exercise freedom of Unicode?  Or don't we care for compatibility with thewebsocketprotocol?

**Comment by stefhak** [comment]
Being compatible makes sense to me.

**Comment by dontcallmedom** [comment]
I can't see any reason why throwing on un-registrable protocols would be useful, since there is no intent on throwing on un-registered protocols either.
The RTCWeb datachannel draft says
> The protocol field [...] may be useful for homogeneous applications which may create more than one type of Data Channel

which suggests that the registry of subprotocols is useful for cross-app interop, but certainly not the only expected usage of the protocol field. Incidentally, the Web Sockets API doesn't throw on non-ASCII protocols either.

**Comment by alvestrand** [comment]
the data channel protocol should be fine with carrying this protocol. Using non-registered stuff is OK.

**Comment by martinthomson** [comment]
So we are OK with accepting values that the web socket protocol cannot.  Shouldn't that at least require a small note?

**Comment by alvestrand** [comment]
My reading of RFC 6455 is that sending unregistered values is fine in Websockets. (╯°□°）╯︵ ┻━┻) can be sent, but can't be registered.

**Comment by martinthomson** [comment]
I don't know how you could get "(╯°□°）╯︵ ┻━┻)" in the Sec-Websocket-Protocol header field given that it has a constrained syntax and no escaping rules.
