### ISSUE TITLE
Separate sender and receiver sets are unnecessary when we have a transceiver set

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#566]
For example, getSenders() can be defined as a new sequence containing all senders in the transceiver set.

**Comment by alvestrand** [comment]
Do you mean that the spec should define getSenders() in terms of transceivers, or that we should remove the getSenders() call? I'm in favor of the first, but not the last.

**Comment by adam-be** [comment]
The first. I.e., we don't need to keep track of senders/receivers separately.

**Comment by alvestrand** [comment]
"Add this sender to the sender set" is a hint that the spec hasn't been updated for transceivers; it can be a good exercise to clear this up.

**Comment by burnburn** [comment]
After making the change you suggest to getSenders() and getReceivers() (see commit 503c9aa40e233bec07f8bbdbf515bbf4b9f1a170) I took a look at other uses of "set of senders" such as in addTrack().  I believe it may still be useful to either keep an explicit list of senders and receivers or create some internal function that generates the list on the fly from the transceivers.  Otherwise, changing the wording in addTrack, removeTrack, and close to talk about "all the senders in all of the transceivers in connection's set of transceivers" is both imprecise, wordy, and difficult to work into the text in those sections.

**Comment by burnburn** [comment]
Decision on editor's call was to create internal functions for getSenders and getReceivers that we can reference in addTrack, removeTrack, etc.  I will do this.

**Comment by burnburn** [comment]
PR 739 added algorithms and removed "set of senders" everywhere but not "set of receivers".  See the PR for details.

**Comment by adam-be** [comment]
Remaining work will be tracked by issue #788.
