### ISSUE TITLE
Fob on RTCRtpEncodingParameters to turn on and off sending CN / DTX 

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#644]
In the case where SDP negotiated CN allowed int he envelope, folks still want a FOB to turn on and off sending the RTP for it. (Relates to JSEP issue 202 and 233 )

**Comment by alvestrand** [comment]
Hm. Doesn't look like an appropriate RTPSender surface. More like an encoding parameter, or even an audio track thingy. 

But sure, people do ask for it.

**Comment by alvestrand** [comment]
Seems like multiple people want this. Encoding parameter "feels" right.
Proposal needed.

**Comment by aboba** [comment]
In the meeting today, it was pointed out that it is possible to turn CN on/off by adding/removing the CN codec from parameters.codecs[] and calling setParameters().  However, this does not work for DTX, because in WebRTC 1.0 (unlike in ORTC) there is no useDtx parameter than be set for a codec such as Opus. 

So it occurs to me that an alternative way of addressing this need would be to add such an Opus parameter.

**Comment by juberti** [comment]
Having the CN codec and the FMTP param just means that DTX is possible, not that it is active. Same for the use of FEC (i.e., with negotiation of FEC 'codecs').

I think we want RtpEncodingParameters.vad or some such, similar to RtpEncodingParameters.fec.

**Comment by alvestrand** [comment]
Closed by #734
