### ISSUE TITLE
mimeType Clarification

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#650]
Currently, we have mimeType attributes within RTCRtpCodecParameters as well as RTCRtpCodecCapability.

The definition of the mimeType attribute is as follows:

"The codec MIME type.  Valid types are listed in [IANA-RTP-2]."

A question has arisen as to exactly what should be included within the mimeType attributes.

Is this the Media Type (e.g. "application", "audio", "video", etc.),  the Subtype ("ulpfec", "CN", "G722", "PCMA", etc.) or both (e.g. "audio/PCMA")?

See related thread on the mailing list: 
https://lists.w3.org/Archives/Public/public-webrtc/2016May/0069.html
https://lists.w3.org/Archives/Public/public-ortc/2016May/0027.html

**Comment by pthatcherg** [comment]
I was under the impression that mimeType == $mediaType/$subType, but perhaps that understanding it too simplistic.  As has been mentioned $mediaType == $kind, so that's a bit redundant.  So it would make more sense to just have the $subType on the parameters.

But, you know, we could just have both for convenience:

.mimeType = $mediaType/$subType
.name = $subType

**Comment by pthatcherg** [comment]
Given that we realized that the media type doesn't always match the kind, I withdraw my suggestion about having the "name".
