### ISSUE TITLE
An event for when a Circuit Breaker is triggered

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-pc#700]
We need to trigger an event, when a circuit breaker is triggered, so that the application would know the reason for terminating the connection.

Consequently, to restart the media flow, would it be similar to an ice restart?

Requirement for implementing Circuit Breaker is made in RTP-USAGE: https://tools.ietf.org/html/draft-ietf-rtcweb-rtp-usage-26#section-7.1

**Comment by stefhak** [comment]
Is there a good reason to single out circuit breaker as reason?

**Comment by aboba** [comment]
Is any browser implementing or planning to implement circuit breakers?

**Comment by vr000m** [comment]
Clarification, the circuit breaker does not need to terminate a connection, it will just cease sending media. When the circuit breaker is triggered, it could invoke an event (oncircuitbreaker), which the app can expose to the user or do some checks at this point. For example, by observing the RTT and losses for the consent checks and attempting to restarting the media, when it feels that the congestion has abated.

**Comment by stefhak** [comment]
If we consider adding something like this, there are a couple of things to consider (apologies if I have gotten things wrong):
- how would the app restart media? Would it kick on the sender, or create a new one (via addTrack)?
- or should a sender re-start automatically when congestion has cleared?
- how different is this to the rate adaptation estimating a very low throughput (just as example say 60 kbps and you want to get video over)?

**Comment by vr000m** [comment]
The recommendation from the circuit breaker draft is that the stack should not restart by itself. However an app could restart the streams automatically for example by looking at other metrics or performing measurements. 

The restart mechanism depends a bit on what happens when the browsers ceases transmission. If it implemented as a hold, i.e., the stream is not destroyed when the circuit breaker triggers, just paused, then restarting them by unpausing would work. 

 it is likely that once the circuit breaker triggers, consequently a few seconds later the consent checks may trigger an ICE state change because repeated checks have also failed. 

Circuit breakers may only trigger if the rate adaptation or congestion control is much more aggressive than TCP. The threshold in the draft days 10 times more, I.e., the media rate is 10 times of what TFRC (TCP friendly rate control) for example would estimate.

**Comment by stefhak** [comment]
It sounds like we should first define and specify what browsers must do if circuit breaker is triggered.

**Comment by aboba** [comment]
@vr000m We could define an event (onactive?) that occurs when the value of .active transitions.  This could be due to circuit breakers, or just due to congestion control. For example, the browser could have negotiated the sending of two simulcast streams, but due to congestion, the browser decides to inactivate the higher resolution stream (e.g. .active transitions from "true" to "false"). .  There could also be an event when the browser activates a stream that had previously been inactive (e.g. .active transitions from "false" to "true").  Along with the new value of active, the event might include information on whether activation can occur automatically, or needs to be done manually.

**Comment by vr000m** [comment]
@aboba onactive may be sufficient. 

The proposal is:
.onactive transitions to false, when the
* browser's internals: circuit breaker fires
* browser's internals: congestion control unset a particular simulcast stream
* user actions?

.onactive transitions to true, when the
* browser internals: when congestion control decides to send an additional stream?
* user actions?

Clarification: I do not quite understand how the browser would turn on/off the high resolution stream, is it because of the degradation preference? I suppose an argument could be made for preferring different attributes of the stream (rather than resolution).

**Comment by aboba** [comment]
@vr000m  Not sure we need a new attribute here, since we already have a .active attribute. 

Two interims ago, we discussed how a browser might make a decision on turning off a simulcast stream.   RTCRtpParameters.degradationPreference operates at the level of an entire RtpSender.  So it could be used to determine whether to maintain framerate or resolution, but it does not indicate which streams are preferred.  There seemed to be consensus to leave this unspecified (e.g. no requirement that preference be governed by RTCRtpEncodingParameters.priority or another encoding parameters attribute).

**Comment by stefhak** [comment]
With this approach I see some similarity with MediaStreamTracks. The have two attributes 'enabled' and 'muted'. The first one is controlled by the application (indicating its wish), while the second one is controlled by the UA. This is because even if the application wants the track to be active this could be overridden by e.g. the user.
I think we would need something similar here: even if the application wants the sender to be active (and puts active=true) it could because of e.g. circuit breakers be inactive at the moment.

**Comment by vr000m** [comment]
@aboba priority could be leveraged here, but not sure. because the circuit breaker draft is very specific in this case, turn off the stream. I assume that the stream did try to reduce the rate by 10x before the CB triggered.

**Comment by stefhak** [comment]
Quoting from "[Decisions reached](https://lists.w3.org/Archives/Public/public-webrtc/2016Aug/0083.html)" sent out after interim meeting held Aug 23rd: 

"There was no consensus after discussion. No decision was reached."

I guess no consensus means no change to the spec for now.

**Comment by alvestrand** [comment]
With the lack of implementation experience, it seems premature to get an event into WebRTC 1.0.
Closing for now, with the LATER label.

**Comment by vr000m** [comment]
I'll take an action point to run through the metrics in the stats API to make sure we have sufficient information.
