### ISSUE TITLE
How does setDirection interact with active/inactive sender/receivers?

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#706]
The description of setDirection says
"The setDirection method sets the direction of the RTCRtpTransceiver. Calls to setDirection() do not take effect immediately. Instead, future calls to createOffer and createAnswer mark the corresponding media description as sendrecv, sendonly, recvonly or inactive as defined in [JSEP] (section 5.2.2. and section 5.3.2.). Calling setDirection() sets the negotiation-needed flag."

However, there is no mention of setDirection anywhere in JSEP.  In fact, section 5.2.4 (https://rtcweb-wg.github.io/jsep/#rfc.section.5.2.4) explains how sender/receiver (in)activity sets this value.  How does setDirection interact with what is described in JSEP?

This is a work item of issue #337.

**Comment by aboba** [comment]
Looking at the text relating to direction in both documents, there are a number of potential grey areas.

JSEP refers to "states of the RtpSender and RtpReceiver" in Section 5.2.4. However, it is not clear to me what attribute this is referring to (the .active attribute?).  WebRTC 1.0 Section 5 does relate RTCRtpTransceiverDirection to the .active attribute so possibly this is what is being referred to. 

JSEP Section 5.3.1 refers to a "A direction attribute for the associated RtpTransceiver", which is also described in JSEP Section 5.3.4. This is defined in WebRTC 1.0 Section 5.4: 

interface RTCRtpTransceiver {
    readonly attribute RTCRtpTransceiverDirection direction;
};

**Comment by pthatcherg** [comment]
I propose we not have RtpSender/RtpReceiver.active.  It's just duplicate information with RtpTransceiver.direction. 

I think it's fairly understand the following:
- RtpSender/RtpReceiver controls don't affect signaling/negotiation
- RtpSender.encodings[i].active controls sending without affecting signaling/negotation

- RtpTransceiver controls do affect signaling/negotiation
- RtpTransceiver.setDirection controls sending/receiving and affects signaling/negotiation

- You're sending if and only if RtpTransceiver.direction is "sendrecv" or "sendonly" and RtpSender.encodings[i].active is true.
- You're receving if and only if RtpTransceiver.direction is "sendrecv" or "recvonly" (and RtpReceiver.encodings[i].active is true?  Not sure if that's necessary since it can't be set to false).

**Comment by alvestrand** [comment]
Fixed by #722
