### ISSUE TITLE
RTCStats timestamp source ambiguous

### ISSUE THREAD

**Issue by jesup** [w3c/webrtc-pc#729]
RTCStats has a timestamp member -- "has a timestamp value [...] associated with this object".  It's somewhat unclear what the source of this timestamp should be - perhaps the time the data returned for the child object of RTCStats was last updated.  Even that has some ambiguity in the case of remote RTP stats - is it the time they were measured (NTP time from the RTCP packet they came in on), or the time they were received locally?

Currently in Firefox we use the RTCP NTP time.  I haven't reviewed where we get the timestamp values for other stats.

We could expand this definition slightly, or push that down to the Stats spec to define for each derived dictionary what RTCStats.timestamp should be sourced from.

**Comment by vr000m** [comment]
I do not think there is a send NTP timestamp for when the RTCP packet was sent.
IMO, it is the time at which the RTCP packet was received from the remote side.

**Comment by jan-ivar** [comment]
The sender info part of 6.4.1 SR: Sender Report RTCP Packet in https://www.ietf.org/rfc/rfc3550.txt appears to have an NTP timestamp...

```
        0                   1                   2                   3
        0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
header |V=2|P|    RC   |   PT=SR=200   |             length            |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |                         SSRC of sender                        |
       +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
sender |              NTP timestamp, most significant word             |
info   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |             NTP timestamp, least significant word             |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |                         RTP timestamp                         |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

**Comment by vr000m** [comment]
The NTP timestamp in the sender report is related to the RTP timestamp. It is used by the receiver to correlate the RTP timestamps from two different media steams coming from the same sender. Example the audio and video sources. 

The rfc3550 explains the usage of the NTP and RTP timestamp for inter- and intra- media synchronization.

**Comment by vr000m** [comment]
Just to make sure that this is understood. The RTP timestamps for a stream start with random number and then increment based on the media clock rate. So the RTP timestamps for a video and audio stream generated by an endpoint start with random timestamps and a receiver does not have sufficient information to synchronize the a/V playback. The sr report provides the relationship of RTP to NTP for the streams. Since they come from the same endpoint, the receiver just needs to make the correlation between these timestamps to playback the streams in sync.

**Comment by jesup** [comment]
Yes, the NTP vale is the matching value for the timestamp in the RTCP.  RFC 3550: "NTP timestamp: 64 bits --   Indicates the wallclock time (see Section 4) when this report was sent".  Thus it tells you when the RTCP report was generated - the time associated with the data within the report.  Thus my question, and thus my point that as of now RTCStats.timestamp is under-specified.

**Comment by vr000m** [comment]
Ok, I see. Indeed the NTP timestamp is used for the RTT calculation. In the SR there is the NTP timestamp and in the RR there is the LSR (i.e., the middle 32 bit of the NTP in the SR) and DLSR (the time since receiving an SR and sending the RR).

Since there is confusion between the timestamps in the payload of the SR and RR, perhaps this needs to be clarified.

My interpretation of the RTCStats.timestamp for the remote reports has been the reception time of those RTCP packets. And for the local reports is the timestamp when the local snapshot was created.

Is this is the interpretation, we are shooting for?

**Comment by jan-ivar** [comment]
Good, we seem to agree it is under-specified. I vote for the earliest timestamp closest to when the data was sampled, be it time of sampling, time of sending, time of receipt, time of calculation, or time of query, whichever is sooner and available. This may need to be specified individually.

I guess the alternative would be that the timestamps are all time of query, always, but then why do we have a timestamp in each record, rather than a single timestamp at the head of the snowball?

**Comment by jan-ivar** [comment]
This happens to be what Firefox implements.

**Comment by jesup** [comment]
What does Chrome implement/prefer here for the remote stats timestamp?  Is it what Firefox implements? (based on NTP time from remote RTCP block)

**Comment by vr000m** [comment]
The NTP timestamp is available in the RTCP SR and not in the RTCP RR. 

What does FF use for the timestamp for the RTCP RR data?

**Comment by jan-ivar** [comment]
@vr000m Good catch, the time the RTCP RR packet was received, if I recall correctly.

**Comment by vr000m** [comment]
Is there a good reason not to do the same for the SR? i.e., rather than use the NTP timestamp in the payload for the timestamp.

**Comment by jan-ivar** [comment]
@vr000m I suspect the answer to that may be the same as the answer to: Why is there an NTP timestamp in the SR?

Is there a good reason not to use the NTP timestamp in the SR? I stated my preference [above](https://github.com/w3c/webrtc-pc/issues/729#issuecomment-234544926).

**Comment by vr000m** [comment]
The reason the NTP timestamp exists in the RTCP SR is two fold:
1. To compute RTT. 
2. To synchronize media playback of media streams (RTP timestamps) with different clock rates, e.g., audio and video. 

In the case of calculating RTT, the SR carries the NTP timestamp, and the RTCP RR echos the lower 32-bit of the NTP timestamp (LSR) in the SR and the time since it received the RTCP SR and sends the corresponding RTCP RR (DLSR). Explained on page 40 of https://tools.ietf.org/html/rfc3550.

**Comment by vr000m** [comment]
I think a related question would be if I poll the getStats more often than SR and RR is received, what is the expectation for the timestamp in the remote stats? In this case the local stats would change depending on the state of the streams.

**Comment by jan-ivar** [comment]
If we could get the exact prose into the spec that would be great.

**Comment by vr000m** [comment]
Hmmm.. I am not sure if this would work for the SR:

The endpoint receiving the SR has the NTP timestamp of the sender and can log the reception time of the SR, however it does not have the RTT estimate for that particular SSRC. 
Although, it could infer the RTT from the SRs the endpoint sent on other SSRCs, then it could do remote NTP timestamp + 1/2 RTT -- I am not sure how accurate this is.

The endpoint receiving the RR has the NTP timestamp when it received the RR and an RTT estimate based on the info in the RR, essentially, if it wanted to represent the generation time of the RR, it would do reception NTP timestamp - 1/2 RTT.

**Comment by jesup** [comment]
Putting pseudo-clock synchronization into this report seems like a bit of a swamp and source of subtle differences in implementation.  And what do you do when you've received a SR, as mentioned, especially for sendonly streams?  and 1/2 RTT is only an approximation anyways.  I lean towards "time sampled", with the NTP time of the sender (which makes looking at deltas more  consistent, since it's a stable base, if not synced with local times).  Or use the reception time, and include an entry for the sender's time.  

And we should generally define what the time should be; either some default (time data was measured?) or explicitly for each stat.

Most of all I want something stable defined people can build against (and complain about if they don't like it).

**Comment by alvestrand** [comment]
"something stable defined people can build against" - me too!

I don't think we have a chance in hell of defining a timestamp for remote data that is both useful and sometimes (for the case of wrong remote system clocks) completely not comparable to any other time on the system - so I think the timestamp has to be defined in terms of the local clock.

By far the simplest is the (local) time of reception of the RR/SR that registered the data - but that time is also absolutely certainly wrong, since it's <delay in sending + transit time> later than when it was actually produced.

Second simplest is time of reception + 1/2 RTT. (*all* RTCWeb implementations that send anything have an RTT estimate. Otherwise, congestion control doesn't work.)

Third simplest (where "simplest" is looking quite iffy) is having a local estimation of local/remote NTP offset, and using the NTP time of the incoming report (either directly from a timestamp or indirectly via the NTP/RTP clock calculation).

Unidirectional streams make my head hurt for this particular case :-(

**Comment by vr000m** [comment]
We do have the case of asterisk and freeswitch do not send any RTCPs or only RTCP SRs. RTT estimates are unavailable in these cases, I suppose for G.711 there's isn't much of congestion control except modulating the packetization interval. 

And I'm not sure if time of reception + 1/2 RTT is correct. Is the Time of reception local NTP clock or the NTP time in the SR? If it's the former, the time is in the future rather than in the past.

**Comment by jesup** [comment]
I think we simply define that the time associated with a stats entry is the time the data was sampled.  In many (local) cases this will be the time we asked for it, or the time a periodic process within the webrtc impl queried the lower layers.  In the specific case of remote stats, I'm (as I said) fine with either:
a) stat time is time of reception, and add an entry to the stats with the remote NTP time.  RTT is already available elsewhere so the app (if it wants) can offset.  Importantly, the NTP time at the sender side lets you compare subsequent reports knowing the interval they correspond to.
or
b) stat time is remote NTP time, unmolested, and we define it as such.  This is what Mozilla has been doing.  Most (if not all) uses of the stats time would look at deltas anyways.

Trying to infer an offset is fraught with problems, and gains little or nothing I think.

**Comment by vr000m** [comment]
I prefer a) because it will always be consistent for the data coming from an SR or an RR. Adding an extra entry for NTP time which will only appear for the SR data and not for RR data seems consistent as well. Apps can do the offset as they deem fit.

**Comment by vr000m** [comment]
Anyway things that do not send SRs or RRs won't have remote entries. I suppose remote inbound and outbound is just null.

**Comment by jan-ivar** [comment]
Is there value in having both reception time and NTP time for sender reports?

**Comment by alvestrand** [comment]
@jan-ivar They may be different, and there may be value in knowing the difference (and changes in the difference).

**Comment by juberti** [comment]
Did we manage to resolve this issue?

**Comment by vr000m** [comment]
Yes. Local reception time stamp value as the time stamp in the stats. The NTP in the RTCP SR as a separate key value within the appropriate stats dictionary.

**Comment by jan-ivar** [comment]
We haven't heard what Chrome implements, but we seem to be leaning toward time of reception, on account of it being the earliest local time that is stable in all cases.

**Comment by jan-ivar** [comment]
(I suspect this will fix some intermittents on our test servers)

**Comment by stefhak** [comment]
Can we close this one? Seems resolved.

**Comment by jan-ivar** [comment]
@stefhak I think we need a PR to clarify that RTCStats timestamps are time of reception, and a new member in RTCInboundRTPStreamStats for raw RTCP SR NTP timestamps.

**Comment by jesup** [comment]
@stefhak  Didn't we come to a resolution on this at one of the virtual interims?

**Comment by stefhak** [comment]
@jesup my memory says we did, and my memory says @vr000m got it right in https://github.com/w3c/webrtc-pc/issues/729#issuecomment-241963760 - and I think that is what https://lists.w3.org/Archives/Public/public-webrtc/2016Aug/0083.html (last item) says too (referencing slide 24 in https://www.w3.org/2016/08/WebRTCWG-2016-08-23.pdf).

**Comment by jesup** [comment]
@stefhak Right (missed that comment).  So, we just need to fix it in the spec then (need a PR)

**Comment by stefhak** [comment]
@taylor-b or @alvestrand : can one of you do a PR?

**Comment by taylor-b** [comment]
PRs made

**Comment by stefhak** [comment]
Thanks @taylor-b
