### ISSUE TITLE
RTP Sender and Receiver API needs bool for "active"

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#781]

**Comment by fluffy** [comment]
See definition of active/inactive in JSEP

**Comment by fluffy** [comment]
This is in the RTCRtpEncodingParameters

**Comment by aboba** [comment]
@fluffy  @pthatcherg RTCRtpEncodingParameters.active only affects whether a given stream is active, and in WebRTC 1.0, can only be set on an RtpSender.  Rather than talking about "active", JSEP Section 5.2.4 should instead refer to the setDirection() method.  

See the June 28 virtual interim slides relating to Issue 706/PR 787:
https://www.w3.org/2011/04/webrtc/wiki/images/1/12/WebRTCWG-2016-06-28.pdf

Points from those slides: 

○ RtpSender.encodings[i].active controls sending without affecting signaling/negotiation
○ RtpTransceiver.setDirection() controls sending/receiving and affects signaling/negotiation
○ RtpSender sends iff RtpTransceiver.direction is “sendrecv” or “sendonly” and RtpSender.encodings[i].active is true
○ RtpReceiver receives iff RtpTransceiver.direction is “sendrecv” or “recvonly” (RtpReceiver.encodings[i].active can’t be set to false)

**Comment by fluffy** [comment]
@aboba - good point - next version of jsep has done this and removed the direction tables and overal made it simpler to understand.
