### ISSUE TITLE
What happens if removeTrack() is called when DTMF tones are still in the toneBuffer?

### ISSUE THREAD

**Issue by dminor** [w3c/webrtc-pc#800]
I assume that we would not play any remaining tones in the toneBuffer, but that is not specified.

**Comment by jan-ivar** [comment]
http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-removetrack says it will [stop](http://w3c.github.io/webrtc-pc/#sender-stopped) the sender, *"which indicates that it will no longer send any media"*, so that seems to be the intent.

The [insertDTMF](http://w3c.github.io/webrtc-pc/#dom-rtcdtmfsender-insertdtmf) steps need to specify how to deal with stopped senders.

**Comment by alvestrand** [comment]
Fixed in #809
