### ISSUE TITLE
getConfiguration doesn't include all of RTCConfiguration

### ISSUE THREAD

**Issue by pthatcherg** [w3c/webrtc-pc#813]
getConfiguration is weird in that it makes a new RTCConfiguration object to return and explicitly fills in a few of the fields (ICE transports, ICE servers, certificates), but not others (bundlePolicy, rtcpMuxPolicy, iceCandidatePoolSize).  Should we just have a blanket "copy everything" statement, which would include any future things?  Or should we explicitly add the things that are missing?

**Comment by aboba** [comment]
@pthatcherg  The method description says "Returns a RTCConfiguration object representing the current configuration of this RTCPeerConnection object."  Based on that, I'd expect it to "copy everything". Otherwise it would have said "representing some of the current configuration (in an inconsistent way, to keep you guessing)."

**Comment by aboba** [comment]
Can we close this now?
