### ISSUE TITLE
Not clear how data channel errors are reported, with ErrorEvent interface.

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#846]
The `RTCDataChannel` has an `EventHandler` of type `error`, which uses the `ErrorEvent` interface. However, this interface is used for reporting script errors associated with specific line/column numbers. So for an error that originates from background processing, it doesn't really make sense (to me). Do we just leave those attributes as the defaults?

In looking for an answer, the text that describes firing an error is somewhat lacking. It's simply:

> Fire a NetworkError event at _channel_.

Which I can extrapolate to mean:

> Fire an event named "error" which does not bubble, is not cancelable, and which uses the ErrorEvent interface with _message_ set to a user agent defined string (fingerprint warning?), with _filename_, _lineno_ and _colno_ left as the default values, and with _error_ set to a newly [created](https://heycam.github.io/webidl/#dfn-create-exception) NetworkError.

Is that what we want?

It looks like this topic also came up with mediacapture-main (https://github.com/w3c/mediacapture-main/issues/337), and the solution there was to use a simple event. But in this case we do want additional error information, or at least I assume.

If RTCDataChannels are meant to be similar to WebSockets, could we do the same thing they do, and put the additional information on the close event (in their case, a code and reason)?

**Comment by gunnarhm** [comment]
I can just agree. It needs to be clear how various kinds of communication errors are reported, and how to find complementing information. 

draft-ietf-rtcweb-data-channel  gives some vague information.

Communication errors can cause the SCTP association to break so that all data channels using the association need to be closed. It would then be important to know that that had happened and which data was successfully transferred and not. I assume that this will happen e.g. when the connectivity watchdog acts on a failing association. 

If the channel is opened for reliable communication, then communication errors in the channel will cause the channel to be closed and indication on the error provided to applications. Information on how far the transmission was successful should also be provided to the application. 

If the channel is opened for partially reliable communication, then some general association errors will cause the association and channel to close, while transmission errors in the channel should cause an error indication without any channel closure. Instead, information on how far transmissions had succeeded should be available to the application.    

I assume that a lot of the above should be indicated through
https://www.w3.org/TR/webrtc/#rtcdatachannelevent
and that that specification needs to be more clear about how te different situations are signaled to te application.

**Comment by taylor-b** [comment]
It sounds like this is a duplicate of issue #526 then. I'll close it.
