### ISSUE TITLE
Further generateCertificate changes required

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#891]
A follow-up to https://github.com/w3c/webrtc-pc/issues/879 and https://github.com/w3c/webrtc-pc/pull/880:

A WebIDL dictionary doesn't allow for anything "extra", so using the `RTCGenerateCertificateOptions` dictionary, the only possible members would be `name` and `expires`. But the spec requires at least these things to work:
- `{ name: "RSASSA-PKCS1-v1_5", modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: "SHA-256" }`
- `{ name: "ECDSA", namedCurve: "P-256" }`

The [algorithm normalization process](https://dvcs.w3.org/hg/webcrypto-api/raw-file/tip/spec/Overview.html#algorithm-normalization) link is stale, but must mean that [normalize an algorithm](https://w3c.github.io/webcrypto/Overview.html#dfn-normalize-an-algorithm) should be used, which requires an `AlgorithmIdentifier` as its input. That's how it's implemented (@henbos) in Blink. (The prose for `generateCertificate` still refers to `AlgorithmIdentifier`, but that's an oversight I think.)

Paging @ericroman920 and @mwatson2 for advice on how to do this.

**Comment by ericroman920** [comment]
Some general feedback on `generateCertificate()`.

`generateCertificate()` takes a `RTCGenerateCertificateOptions` -- could this instead `generateCertificate()` just have a second parameter for the expiration time?

Here is how things currently read:

```
dictionary RTCGenerateCertificateOptions : Algorithm {
    DOMTimeStamp expires;
};
```

```
partial interface RTCPeerConnection {
    static Promise<RTCCertificate> generateCertificate(RTCGenerateCertificateOptions keygenAlgorithm);
};
```

* If Web Crypto ever introduced an algorithm that contained the name "expires" in its (generateKey) parameters, it will break this, since now there is a conflict of naming.
* It is inconsistent with how the expiration and algorithm of the certificate are reflected by `RTCCertificate`. That doesn't re-use `RTCGenerateCertificateOptions`.

```
interface RTCCertificate {
    readonly attribute DOMTimeStamp                    expires;
    readonly attribute FrozenArray<RTCDtlsFingerprint> fingerprints;
    AlgorithmIdentifier getAlgorithm();
};
```

My next confusion while reading through things is how `generateCertificate()` deals with hashes.

A certificate containing an RSA key gets generated by specifying a hash to use when signing. Whereas a certificate containing an EC key does not specify the hash. This oddity stems from Web Crypto's distinction that ECDSA takes the hash as a parameter for the sign() operation, whereas for RSASSA-PKCS1-v1_5 and RSA-PSS the hash it expected when generating the key.

The spec says:
> a browser should select SHA-256 [FIPS-180-4] if a hash algorithm is needed.

What does that mean in the RSA case? Is the user-provided hash disregarded? Should `generateCertificate()` fail if something other than SHA-256 was not provided? Is it implementation specific behavior? Should the reflected certificate algorithm normalize the hash to read SHA-256 (or whatever the implementation will be using) ?

`RTCCertificate.getAlgorithm()` is defined to:

> Returns the value of keygenAlgorithm passed in the call to generateCertificate().
> No parameters.
> Return type: AlgorithmIdentifier

Which has some ambiguity -- does this imply it returns the exact same object as originally passed in, or an object with equivalent properties to those in the algorithm, etc. For reasons mentioned in the other thread, I think the only reasonable thing is to reflect back a *normalized* algorithm. And for that a read-only attribute is consistent with the approach taken by Web Crypto in `CryptoKey`.

I realize there is some history with the integrations here, apologies if I am "rehashing" past discussions.

**Comment by martinthomson** [comment]
As @ericroman920 points out, and as I found when I tried to land code based on this, you really need to use `AlgorithmIdentifier` here.  There is no other way for the random gunk that the WebCrypto API depends on to traverse the interface otherwise.

We could move `expires` to a new parameter, and that might be ideal if preserving the ability for the WebCrypto API to add a parameter by that name were critical.  But we've already got shipped code that does this.

As for hashes, WebCrypto is a mess, so I won't pretend to understand how hashes work, but the intent here is that the browser is responsible for choosing a hash algorithm when it comes to *using* the key.  The suggestion to use SHA-256 is just a guideline (though that doesn't work for P-521 because it's too small).

@ericroman920 also points out that `getAlgorithm()` is rotten.  I agree that it should be normalized, since otherwise the browser would be required to remember junk that it didn't use or support - keep in mind that this also has to be persisted in indexedDB.
