### ISSUE TITLE
Need to replace references to "stopped sender" with "recvonly/inactive transceiver"

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#908]
We used to have the concept of stopped/unstopped senders and receivers, which determined the direction of an m= section. But now we have the `RTCRtpTransceiver.setDirection` API for that. So I think the following changes are necessary:

- Remove the paragraph "An RTCRtpSender can be stopped, which indicates that it will no longer send any media.", or rewrite it in terms of transceiver direction.
- In the `removeTrack` steps:
  - Add a step for changing the transceiver's direction
  - Remove or rephrase the "Stop sender" step (which has a dead link to "Stop").

**Comment by aboba** [comment]
@taylor-b  We can probably remove the paragraph starting with "An RTCRtpSender can be stopped" without losing anything.  

The description of transceiver.sender.removeTrack seems quite similar to that of transceiver.setDirection("inactive") with the exception that transceiver.setDirection would also affect transceiver.receiver.  Do you see any problem with removeTrack also affecting the receiver?

With respect to the now outmoded concept of stopped/unstopped senders and receivers, there is an  odd bit of text in the description of transceiver.stopped: 

stopped of type boolean, readonly
The stopped attribute ... is true if either stop has been called or if setting the local or remote description has caused the RTCRtpReceiver to be stopped.

Could we change this to "is true if stop has been called" and delete the rest?  I think this text was originally meant to describe how the effect of removeTrack would propagate to the remote peer, but reformulating things in terms of setDirection should take care of that.

**Comment by taylor-b** [comment]
> Do you see any problem with removeTrack also affecting the receiver?

I don't think that should be possible, since it only modifies the "send" bit of the direction.

> Could we change this to "is true if stop has been called" and delete the rest?

No, because a transceiver being stopped means "transceiver will permanently stop sending/receiving RTP/RTCP packets". Even if the application didn't call "stop", if a remote offer or answer rejected the m= section, the transceiver will be stopped and there's nothing that can be done but create a new one.

Though this text *does* need to be changed to say RTCRtp**Trans**ceiver instead of RTCRtp**Re**ceiver...

**Comment by alvestrand** [comment]
Note: I think a sender should be stoppable.
The chief role of the transceiver (to my mind) is to store the per-m-line information that came in on the previous SDP offer/answer, apply the needed changes to senders & receivers when that happens, and return the (possibly modified) information needed when createOffer/createAnswer is called.

If the sender or receiver have to consult the transceiver at runtime to figure out what to do, we have a problem in the design.

When sending media, it's a perfectly legititmate operation that doesn't require negotiation to stop sending media, and  to start sending media again later.

Therefore, there should be a "stop" method (or an "active" writable attribute, or however we want to represent it) on the sender. The transceiver description should document that when SetLocalDescription sets the direction of a transceiver to "receiveonly" or "inactive", it stops the RTPSender.

We might have to specify that it "stops and locks the sender", in a similar way that "muted" works for tracks, since it should leave the sender in a state where the JS can't turn it on again. But the idea of a stopped sender needs, in my mind, to remain in the spec.

(I see much less need for a stopped receiver).

**Comment by aboba** [comment]
@taylor-b Stopping a transceiver causes transceiver.sender to no longer send and transceiver.receiver to no longer receive.  There does not appear to be a way to reverse the effect of transceiver.stop() so it seems that it is irreversible.  Is that correct? We have sender.setParameters() but not receiver.setParameters(), so we can't set  [`RTCRtpEncodingParameters.active`](https://www.w3.org/TR/webrtc/#dom-rtcrtpencodingparameters-active)  to false on an RtpReceiver.

**Comment by taylor-b** [comment]
Yes, transceiver.stop() is irreversible.
