### ISSUE TITLE
CaptureStream adds mediaTracks with delay, we need a callback?

### ISSUE THREAD

**Issue by IvRRimum** [w3c/webrtc-pc#923]
When calling video.captureStream() getTracks() returns empty array, but after 1.5 seconds, it returns tracks as expected.

Error produced if no tracks are added: http://stackoverflow.com/questions/40472743/webrtc111-error-domexception-internalerror-cannot-create-an-offer-with-no-lo

Adding this for doc purposes, as others might find this confusing.

Solution:

setInterval(function(){
      // We wait till the mediaTracks are added to mediaStream
      console.log(stream.getTracks());
      // Further actions with the mediaStream
}, 1000);

Thanks!

**Comment by alvestrand** [comment]
Doesn't the addtrack event fire?

The API is described as a synchronoous interface, so if the tracks aren't present at the beginning, they need to fire the addtrack event when added.

This should probably be a bug on the mediacapture-fromelement spec: https://w3c.github.io/mediacapture-fromelement/

**Comment by alvestrand** [comment]
Closing as "wrong spec".

**Comment by zaidiqbalsoftech** [comment]
This is because you are capturing stream before video is played. So you need to capture stream after video has started playing to avoid delay in stream tracks.

**A better way instead of setInterval is to use:**
1- Use await on video.play() method and capture stream after that.
2- Use 'onplay' event of video element to capture stream when video is played.
