### ISSUE TITLE
When is an RTCSctpTransport created and destroyed?

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#979]
This should be documented more clearly. Things that aren't obvious to me right now:

1. Is the SctpTransport created after applying an offer, or only after applying an answer?
2. If the data "m=" section is rejected, does the SctpTransport go away? I'd guess yes.
3. If the SCTP port ("a=sctp-port") is changed, and a new SCTP association is formed, is a new SctpTransport created to represent that association? I'd lean towards "yes".
4. Secondary question: Do we even want to support changing the SCTP port? It's not clear we have any use case for this.

**Comment by aboba** [comment]
@taylor-b  I'd assume that the SctpTransport is created/destroyed at the same time that the DtlsTransport is created/destroyed. 

1. My assumption has been that for both the Offerer and Answerer the local DtlsTransport/SctpTransport is created by calling setLocalDescription.  

2. I'd assume that there was no SctpTransport created on the Answering side (since the section was rejected).  On the Offering side, an SctpTransport was created.  If it is permanently stopped by the rejection, then application of another offer would presumably create a new SctpTransport. 
Would the port also change in that situation?

3. I would also lean toward creating a new SCTP association in this case.  

4. I don't think there's a need to change the port on an existing SctpTransport.

**Comment by taylor-b** [comment]
It looks like our assumptions match; I'll work on a pull request then that tries to address these things.

> If it is permanently stopped by the rejection, then application of another offer would presumably create a new SctpTransport. Would the port also change in that situation?

In practice, everyone uses a default port of 5000. Though I don't see this documented anywhere.

> I don't think there's a need to change the port on an existing SctpTransport.

If so, we should explicitly disallow this in JSEP.

**Comment by pthatcherg** [comment]
I agree that:

1.  The SctpTransport is created by setLocalDescription (like the other transports)

2.  Rejecting an m-line permanently stops an SctpTransport.

3.  A new port creates a new SCTP association and SctpTransport. 

4.  There is no reason to change a port of an existing SctpTransport.


As to the question of what happens when an m-line rejection closes an SctpTransport and then a second SctpTransport is created later, I don't see why the new SctpTransport can't have the same port.  Just like if you stopped an RtpTransceiver and created a new one with the same SSRCs.   As long as we don't have two SctpTransports at the same time with the same port, it shouldn't matter that the port is reused.

**Comment by aboba** [comment]
@taylor-b In looking into the operation of the SctpTransport, it is helpful to understand things in a bit more detail.  Does the following make sense?

a. When an SctpTransport is created by setLocalDescription, the local port is allocated and can be determined from the SDP provided to setLocalDescription.  In ORTC this means that SctpTransport.port is non-null. 
b. If setRemoteDescription has been called prior to setLocalDescription, then when the SctpTransport is created, the remote port is known, and can be determined from the SDP provided to setRemoteDescription.  Therefore, the SctpTransport starts negotiating an SCTP association.  In ORTC, this implies that start(SctpCapabilities, remote.port) is called, and SctpTransport.state transitions from new to connecting and eventually, connected.
c. If setRemoteDescription has not been called prior to setLocalDescription, then when the SctpTransport is created the remote port is not known, and so when the SctpTransport is created it cannot begin to negotiate an SCTP association until setRemoteDescription is called. In ORTC this implies that SctpTransport.start is new.

**Comment by taylor-b** [comment]
@aboba Yes, that's how I thought of this mapping to ORTC. Does that work for you?
