### ISSUE TITLE
RTCIceCandidateInit's required DOMString ufrag will throw for all existing content

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#983]
This issue was raised in https://github.com/w3c/webrtc-pc/pull/968#pullrequestreview-13093177 but not resolved before merging.

Perhaps @henbos or @jan-ivar can verify, but it looks to me like it's a bad idea to attempt implementing the current spec, as any existing use of the RTCIceCandidateInit dictionary will start throwing TypeError.

**Comment by jan-ivar** [comment]
I agree with @foolip. Most scripts still use the explicit `RTCIceCandidate` constructor since most browsers still require it (few know adapter.js removes the need for it).

Even scripts that stringify whatever comes out of `onicecandidate` would throw in a connection between an old and a new browser, due to signaling. E.g. between Chrome and Firefox, unless we implemented ufrag at the same time and eradicate all old versions.

**Comment by alvestrand** [comment]
@taylor-b can you write a PR that makes it not mandatory in IDL and instead specifies in text what to do if it's missing?
That seems the sensible solution.

**Comment by taylor-b** [comment]
Sure. I still would find it helpful to know the general policy on backwards compatibility though (see my comment on PR #968).

**Comment by alvestrand** [comment]
Solved by #987

**Comment by foolip** [comment]
Thanks for fixing, @taylor-b!

> I still would find it helpful to know the general policy on backwards compatibility though

I can't speak for the WebRTC WG, but in all web standards work the approach I take is to ask "can this be implemented and shipped by everyone?" And to answer that question, one has to look into existing usage of an API, and whether some browsers might be constrained by web compat in ways that others are not, e.g. due to engine-specific code paths.
