### ISSUE TITLE
RTCRtcpMuxPolicy of "negotiate" should be marked as an "at-risk" feature

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#997]
JSEP allows implementations to not implement the "negotiate" RTCP mux policy (meaning they don't support non-muxed RTCP). Chrome and Firefox developers have expressed willingness to do this, so it's likely that the "negotiate" policy will not end up implemented in an interoperable way.

**Comment by alvestrand** [comment]
This is a process thing; Dan will make the marker in the document after seeking advice from @dontcallmedom on how we're supposed to do this in current process / ReSpec.

**Comment by foolip** [comment]
There's an Intent do Deprecate about "negotiate" on blink-dev relevant to this:
https://groups.google.com/a/chromium.org/d/msg/blink-dev/OP2SGSWF5lo/v7GOaWt_CQAJ

What is the current state of interop with regards to "negotiate"? (Here "interop" means "works the same", not two browsers talking to each other.) Is it safe to assume that it works roughly the same in Chrome and Firefox due to the shared libwebrtc code?

@ShijunS, will Edge support "negotiate" when RTCPeerConnection ships, or is this something that would be valuable to get rid of?

**Comment by foolip** [comment]
Ping @ShijunS ^

**Comment by ShijunS** [comment]
@foolip, sorry for the slow response. We don't support non-muxed RTCP.

**Comment by foolip** [comment]
Thanks @ShijunS, is it safe to assume you are not excited to support non-muxed RTCP, i.e. that you'd be happy if the `rtcpMuxPolicy` option went away entirely? Trying to figure out how high the value would be in getting it removed from Blink, vs. how hard it would be to get it implemented interoperably everywhere.

**Comment by ShijunS** [comment]
@foolip, yup, we are fine to remove that option.
